# syntax=docker/dockerfile:1

# Fido — GoProgram (finite map of paths to raw file ASTs) -> GoCompile -> GoSafe -> GoRender -> GoEmit
# (finite-map DirectoryImage), then standard extraction + one tiny dirty-directory filesystem sink + the
# pinned Go toolchain.  Stages: (prover) dune-compiles the theory and the always-run assumptions gate
# confirms every declared surface axiom-free; (emit) extracts the final (path,bytes) image and runs the
# sink, which synchronizes it into a dirty output directory from proved bytes; (go-e2e) the pinned Go
# toolchain builds+runs the emitted main.go vs goldens.

# ── Stage 1: Rocq/OCaml toolchain ─────────────────────────────────────────────
FROM ocaml/opam:debian-12-ocaml-5.3@sha256:bbaac53e502f6602013d8967c3a54cfcb898b556f453ab72e8e23966c3c681df AS rocq-builder
RUN --mount=type=cache,id=fido-apt-builder,target=/var/cache/apt,sharing=locked \
    sudo apt-get update \
    && sudo apt-get install -y --no-install-recommends \
        make build-essential pkg-config libgmp-dev linux-libc-dev ca-certificates \
    && sudo rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
# Install the pinned Rocq/Dune; the retry loop must FAIL if every attempt failed (not fall through to clean).
RUN --mount=type=cache,id=fido-opam,uid=1000,gid=1000,target=/home/opam/.opam/download-cache \
    opam repo add rocq-released https://rocq-prover.org/opam/released \
    && installed=false \
    && for attempt in 1 2 3; do \
         if opam install -y rocq-core.9.2.0 rocq-stdlib.9.1.0 dune.3.21.1; then installed=true; break; fi; \
         echo "attempt $attempt failed — retrying in 20 s..."; sleep 20; \
       done \
    && test "$installed" = true \
    && opam clean --all

# ── Stage 2: minimal Rocq runtime ─────────────────────────────────────────────
FROM debian:12-slim@sha256:60eac759739651111db372c07be67863818726f754804b8707c90979bda511df AS rocq-base
RUN --mount=type=cache,id=fido-apt-base,target=/var/cache/apt,sharing=locked \
    apt-get update \
    && apt-get install -y --no-install-recommends \
        bash ca-certificates gcc libc6-dev libgmp-dev linux-libc-dev make pkg-config tar \
    && rm -rf /var/lib/apt/lists/* \
       /usr/share/doc/* /usr/share/info/* /usr/share/locale/* /usr/share/man/* \
    && useradd -m -s /bin/bash opam
COPY --from=rocq-builder --chown=opam:opam /home/opam/.opam/5.3 /home/opam/.opam/5.3
ENV OPAM_SWITCH_PREFIX="/home/opam/.opam/5.3"
ENV CAML_LD_LIBRARY_PATH="/home/opam/.opam/5.3/lib/stublibs"
ENV PATH="/home/opam/.opam/5.3/bin:${PATH}"
RUN mkdir -p /workspace && chown opam:opam /workspace
WORKDIR /workspace
USER opam

# ── Stage 3: prove — dune compiles the modules; the assumptions gate (gate/axiom_gate.v — the sole
#    Print-Assumptions target) is compiled fresh against the dune-built .vo and is fail-closed both ways:
#    zero '^Axioms:' AND exactly as many 'Closed under the global context' lines as declared surfaces.
FROM rocq-base AS prover
ARG TARGETARCH
COPY --chown=opam:opam dune-project dune ./
COPY --chown=opam:opam *.v ./
COPY --chown=opam:opam gate/ gate/
RUN --mount=type=cache,id=fido-dune-rocq-9.2.0-${TARGETARCH},uid=1000,gid=1000,target=/workspace/_build,sharing=locked \
    if dune build > /tmp/build.log 2>&1; then cat /tmp/build.log; else cat /tmp/build.log; echo "fido: dune build FAILED"; exit 1; fi \
    && rm -f gate/*.vo gate/*.glob gate/.*.aux \
    && if ! rocq c -Q _build/default Fido gate/axiom_gate.v > /tmp/gate.log 2>&1; then \
         cat /tmp/gate.log; echo "fido: ASSUMPTIONS GATE failed to compile"; exit 1; \
       fi \
    && if grep -q '^Axioms:' /tmp/gate.log; then \
         echo "fido: AXIOM — a gated surface depends on an assumption:"; grep -A3 '^Axioms:' /tmp/gate.log; exit 1; \
       fi \
    && want=$(grep -c '^Print Assumptions' gate/axiom_gate.v) \
    && got=$(grep -c '^Closed under the global context' /tmp/gate.log) \
    && if [ "$want" -ne "$got" ]; then \
         echo "fido: ASSUMPTIONS GATE INCOMPLETE — $want surfaces declared, only $got confirmed closed"; exit 1; \
       fi \
    && echo "fido: prove OK — dune compiled the theory (cached in _build); assumptions gate confirmed $got/$want surfaces closed"

# ── Stage 4: emit — the theory is compiled/cached by Dune (the SAME shared cache id as the prover
#    stage); then, in an EXPLICIT always-run step (never a Dune side-effect), standard Rocq extraction
#    produces the final (path,bytes) image and the tiny GENERIC dirty-directory sink synchronizes it.
#    The image's `Print Assumptions` output is checked here (axiom-forged image → red).  The sink is
#    exercised against a DIRTY directory (a stale Fido-owned file + foreign files it must not touch) to
#    prove it is a real synchronizer: it cleans its own stale output, preserves everything foreign, and
#    is idempotent.  All structural decoding is generated by Rocq extraction; the sink decodes nothing.
FROM rocq-base AS emit
ARG TARGETARCH
COPY --chown=opam:opam dune-project dune ./
COPY --chown=opam:opam *.v ./
COPY --chown=opam:opam gate/ gate/
COPY --chown=opam:opam e2e/ e2e/
RUN --mount=type=cache,id=fido-dune-rocq-9.2.0-${TARGETARCH},uid=1000,gid=1000,target=/workspace/_build,sharing=locked <<'SH'
set -eu
rm -rf /workspace/e2e-out
# cached: compile the proved theory (Dune owns the module graph + .vo cache)
if ! dune build > /tmp/emit-build.log 2>&1; then cat /tmp/emit-build.log; echo "fido: emit theory build FAILED"; exit 1; fi
# always-run: extract the final image (writes emit_out.ml), assert the image is axiom-free
if ! rocq c -Q _build/default Fido e2e/Extract.v > /tmp/extract.log 2>&1; then cat /tmp/extract.log; echo "fido: extraction FAILED"; exit 1; fi
if grep -q '^Axioms:' /tmp/extract.log; then echo "fido: emit FAILED — the emitted image depends on axioms:"; grep -A3 '^Axioms:' /tmp/extract.log; exit 1; fi
if ! grep -q 'Closed under the global context' /tmp/extract.log; then echo "fido: emit FAILED — the image assumption closure was not confirmed"; exit 1; fi
# compile the one handwritten dirty-directory sink against the GENERATED image
if ! ocamlfind ocamlopt -package unix -linkpkg emit_out.mli emit_out.ml e2e/writer.ml -o fido_writer > /tmp/writer.log 2>&1; then cat /tmp/writer.log; echo "fido: writer compile FAILED"; exit 1; fi

# make the output directory DIRTY before syncing:
mkdir -p /workspace/e2e-out
#   a STALE Fido-owned file (carries the exact header) that the image no longer contains -> must be removed
printf '// fido generated.  do not edit.\n\npackage main\n' > /workspace/e2e-out/stale.go
#   FOREIGN files (no header) that the sink must never touch -> must survive verbatim
printf 'hand-written notes, keep me\n' > /workspace/e2e-out/keep.txt
printf 'package other\n' > /workspace/e2e-out/foreign.go
foreign_before=$(cat /workspace/e2e-out/foreign.go)

./fido_writer /workspace/e2e-out

# the sink must have produced the desired file, cleaned its stale output, and preserved everything foreign
[ -f /workspace/e2e-out/main.go ]     || { echo "fido: emit FAILED — main.go was not written"; exit 1; }
[ ! -e /workspace/e2e-out/stale.go ]  || { echo "fido: emit FAILED — stale Fido-owned file was not cleaned"; exit 1; }
[ -f /workspace/e2e-out/keep.txt ]    || { echo "fido: emit FAILED — a foreign file was deleted"; exit 1; }
[ -f /workspace/e2e-out/foreign.go ]  || { echo "fido: emit FAILED — a foreign .go file was deleted"; exit 1; }
[ "$(cat /workspace/e2e-out/foreign.go)" = "$foreign_before" ] || { echo "fido: emit FAILED — a foreign file was altered"; exit 1; }
[ "$(head -1 /workspace/e2e-out/main.go)" = "// fido generated.  do not edit." ] || { echo "fido: emit FAILED — main.go is missing the generated header"; exit 1; }
# idempotence: a second sync of the same image is a no-op that preserves foreign files and errors on nothing
./fido_writer /workspace/e2e-out
[ -f /workspace/e2e-out/main.go ] && [ -f /workspace/e2e-out/keep.txt ] && [ -f /workspace/e2e-out/foreign.go ] \
  || { echo "fido: emit FAILED — second (idempotent) sync disturbed the directory"; exit 1; }
echo "fido: emit OK — dirty-directory sync installed main.go, cleaned stale output, preserved foreign files, idempotent; contents:"; echo ----; cat /workspace/e2e-out/main.go; echo ----
SH

# ── Stage 5: go-e2e — the LAST-MILE integration check (never a proof).  The pinned Go toolchain
#    builds and runs the emitted program; stdout/stderr/exit must match the reviewed goldens.
#    gofmt is a NO-OP CHECK (never a rewrite).  A Go build/run failure here is a hard red — it
#    means GoCompile, rendering, target facts, or the transport is wrong, never a "known issue".
FROM golang:1.23-alpine@sha256:383395b794dffa5b53012a212365d40c8e37109a626ca30d6151c8348d380b5f AS go-e2e
WORKDIR /e2e
COPY --from=emit /workspace/e2e-out/main.go ./main.go
COPY e2e/golden.stdout e2e/golden.stderr e2e/golden.exit ./
RUN <<'SH'
set -u
echo "fido e2e: emitted program under test:"; echo ----; cat main.go; echo ----
# The integration toolchain is pinned OPERATIONALLY to the 64-bit target the theory assumes (Ints.v:
# int/uint are 64-bit).  A drift on the running toolchain must fail here rather than silently exercise a
# different word size than the proofs assume.  (This is an operational pin, not a certified TargetConfig.)
gv=$(go env GOVERSION); goos=$(go env GOOS); goarch=$(go env GOARCH)
echo "fido e2e: toolchain GOVERSION=$gv GOOS=$goos GOARCH=$goarch (operational pin: go1.23/linux/amd64, a 64-bit target)"
case "$gv" in go1.23*) : ;; *) echo "fido e2e: Go version $gv != pinned go1.23"; exit 1;; esac
[ "$goos" = linux ]  || { echo "fido e2e: GOOS $goos != pinned linux"; exit 1; }
[ "$goarch" = amd64 ] || { echo "fido e2e: GOARCH $goarch != pinned amd64"; exit 1; }
if [ -n "$(gofmt -l main.go)" ]; then echo "fido e2e: emitted main.go is not gofmt-clean (gofmt is a check, never a rewrite)"; exit 1; fi
printf 'module fidoe2e\n\ngo 1.23\n' > go.mod
if ! go vet ./...; then echo "fido e2e: go vet failed on the emitted program"; exit 1; fi
if ! go build -o prog .; then echo "fido e2e: go build FAILED (a certified artifact must always compile)"; exit 1; fi
./prog > out.stdout 2> out.stderr; ec=$?
echo "fido e2e: exit=$ec stdout=[$(cat out.stdout)] stderr=[$(cat out.stderr)]"
printf '%s\n' "$ec" > out.exit
diff golden.exit   out.exit   || { echo "fido e2e: EXIT mismatch";   exit 1; }
diff golden.stdout out.stdout || { echo "fido e2e: STDOUT mismatch"; exit 1; }
diff golden.stderr out.stderr || { echo "fido e2e: STDERR mismatch"; exit 1; }
echo "fido e2e OK — pinned Go built + ran the emitted program; stdout/stderr/exit match the reviewed goldens"
SH
