// Code generated by rocq-go-extraction; DO NOT EDIT.

package main

func Add(n int64, m int64) int64 {
	return n + m
}

func Panic_and_recover(n int64) {
	defer func() {
		if v := recover(); v != nil {
			recovered := v.(int64)
			println(recovered, Add(recovered, 1))
		}
	}()
	panic(n)
}

func Map_demo() {
	m := make(map[int64]int64)
	m[1] = 100
	m[2] = 200
	m[3] = 300
	m[2] = 999
	sz := len(m)
	var hit any = int64(0)
	if _v, _ok := m[2]; _ok {
		hit = _v
	}
	var mis any = int64(0)
	if _v, _ok := m[9]; _ok {
		mis = _v
	}
	hit64 := hit.(int64)
	mis64 := mis.(int64)
	println(sz, hit64, mis64)
}

func Slice_demo() {
	xs := []int64{1, 2, 3, 4, 5}
	n := len(xs)
	v := xs[2]
	println(n, v)
	func() {
		defer func() {
			if x := recover(); x != nil {
				println(false)
			}
		}()
		_ = xs[9]
	}()
}

func main() {
	println(Add(1, 2))
	Panic_and_recover(Add(40, 2))
	Map_demo()
	Slice_demo()
}
