// Code generated by rocq-go-extraction; DO NOT EDIT.

package main

func I64_abs(a int64) int64 {
	if a < 0 {
		return 0 - a
	} else {
		return a
	}
}

func U64_of_i64(a int64) uint64 {
	return uint64(a)
}

func I64_of_u64(a uint64) int64 {
	return int64(a)
}

func Add(n int64, m int64) int64 {
	return n + m
}

func Sub(n int64, m int64) int64 {
	return n - m
}

func Overflow_safe_demo() {
	println(1000000000000+2000000000000, 1000*1000)
}

func I64_abs_demo() {
	println(I64_abs(-7), I64_abs(7), I64_abs(-9223372036854775808))
}

func Neg_op_demo() {
	println(-5, -(0 - 7))
}

func Conv64_demo() {
	println(U64_of_i64(-1), I64_of_u64(18446744073709551615), U64_of_i64(255))
}

func Cmp_ops_demo() {
	println(5 > 3, 5 >= 5, 5 != 3, 18446744073709551615 > 1)
}

func Div_nz(n int64, d int64) int64 {
	return n / d
}

func Mod_nz(n int64, d int64) int64 {
	return n % d
}

func Div_demo() {
	println(Div_nz(17, 5), Mod_nz(17, 5))
}

func Float_demo() {
	println(1.5+2.25, 1.0/4.0)
}

func Float_cmp_demo() {
	println(1.5 < 2.5)
	println(2.5 <= 2.5)
	println(1.5 == 1.5)
	println(3.0 < 2.0)
}

func Float_nan_demo(z float64) {
	println(z/z == z/z)
	println(z/z < 1.0)
}

func Float_opp_demo() {
	println(-1.5)
	println(-(-2.0))
}

func Float_opp_sign_demo(z float64) {
	println(1.0/-z < 0.0)
}

func Fminmax_demo() {
	println(min(3.0, 5.0), max(3.0, 5.0))
}

func Fcmp_demo() {
	println(5.0 > 3.0, 3.0 >= 3.0, 5.0 != 3.0)
}

func U8_demo() {
	println((((200 & 0xff) + (100 & 0xff)) & 0xff))
	println((((255 & 0xff) * (255 & 0xff)) & 0xff))
	println((((0 & 0xff) - (1 & 0xff)) & 0xff))
	println((10 & 0xff) < (20 & 0xff))
}

func I8_demo() {
	println((((((((100 & 0xff) ^ 0x80) - 0x80) + (((50 & 0xff) ^ 0x80) - 0x80)) & 0xff) ^ 0x80) - 0x80))
	println((((((((-128 & 0xff) ^ 0x80) - 0x80) - (((1 & 0xff) ^ 0x80) - 0x80)) & 0xff) ^ 0x80) - 0x80))
	println((((-100 & 0xff) ^ 0x80) - 0x80))
	println((((-5 & 0xff) ^ 0x80) - 0x80) < (((3 & 0xff) ^ 0x80) - 0x80))
}

func Fw_cmp_demo() {
	println((200&0xff) > (100&0xff), (((5&0xff)^0x80)-0x80) >= (((5&0xff)^0x80)-0x80), (((5&0xff)^0x80)-0x80) != (((-5&0xff)^0x80)-0x80), (4000000000&0xffffffff) > (1&0xffffffff))
}

func U16_demo() {
	println((((60000 & 0xffff) + (10000 & 0xffff)) & 0xffff))
	println((((1000 & 0xffff) * (1000 & 0xffff)) & 0xffff))
	println((((((((30000 & 0xffff) ^ 0x8000) - 0x8000) + (((10000 & 0xffff) ^ 0x8000) - 0x8000)) & 0xffff) ^ 0x8000) - 0x8000))
}

func Bitwise_demo() {
	println((240&0xff)&(60&0xff), (240&0xff)|(60&0xff), (240&0xff)^(60&0xff))
	println((240&0xff)&^(60&0xff), (^(240 & 0xff) & 0xff))
	println((((^(((5 & 0xff) ^ 0x80) - 0x80) & 0xff) ^ 0x80) - 0x80), (((-1&0xff)^0x80)-0x80)&^(((5&0xff)^0x80)-0x80))
}

func Shift_demo() {
	println((((1 & 0xff) << 3) & 0xff), (((1 & 0xff) << 8) & 0xff), ((255 & 0xff) >> 4))
	println((((((((64 & 0xff) ^ 0x80) - 0x80) << 1) & 0xff) ^ 0x80) - 0x80), ((((-3 & 0xff) ^ 0x80) - 0x80) >> 1))
}

func Convert_demo() {
	a := (200 & 0xff)
	b := (((1000 & 0xffff) ^ 0x8000) - 0x8000)
	println(a, ((b) & 0xff))
	println(((((b + ((((a) & 0xffff) ^ 0x8000) - 0x8000)) & 0xffff) ^ 0x8000) - 0x8000))
}

func Divmod_demo() {
	println(((200 & 0xff) / (7 & 0xff)), ((200 & 0xff) % (7 & 0xff)), (((((((-128 & 0xff) ^ 0x80) - 0x80) / (((-1 & 0xff) ^ 0x80) - 0x80)) & 0xff) ^ 0x80) - 0x80))
}

func U32_demo() {
	println((((4000000000 & 0xffffffff) + (1000000000 & 0xffffffff)) & 0xffffffff), (((((((2000000000 & 0xffffffff) ^ 0x80000000) - 0x80000000) + (((2000000000 & 0xffffffff) ^ 0x80000000) - 0x80000000)) & 0xffffffff) ^ 0x80000000) - 0x80000000))
	println((((1 & 0xffffffff) << 31) & 0xffffffff))
	println((((100000 & 0xffffffff) * (100000 & 0xffffffff)) & 0xffffffff), (((((((46341 & 0xffffffff) ^ 0x80000000) - 0x80000000) * (((46341 & 0xffffffff) ^ 0x80000000) - 0x80000000)) & 0xffffffff) ^ 0x80000000) - 0x80000000))
}

func I64_demo() {
	println(9000000000000000000+200000000000000000, 3000000000*3000000000)
}

func I64_ops_demo() {
	println(9000000000000000000/7, 1<<40)
	println(-1&4294967295, ^(5))
}

func U64_demo() {
	println(5000000000000000000+3000000000000000000, 3000000000*3000000000)
}

func Recv_unused_ok_demo() {
	ch := make(chan int64, 1)
	ch <- 77
	x, _ := <-ch
	println(x)
}

func I64_pipeline_demo() {
	ch := make(chan int64, 1)
	ch <- 9000000000000000001
	x := <-ch
	m := make(map[int64]int64)
	m[42] = x
	hit := int64(0)
	if _v, _ok := m[42]; _ok {
		hit = _v
	}
	println(hit)
}

func U64_pipeline_demo() {
	ch := make(chan uint64, 1)
	ch <- 18000000000000000000
	x := <-ch
	m := make(map[uint64]uint64)
	m[7] = x
	hit := uint64(0)
	if _v, _ok := m[7]; _ok {
		hit = _v
	}
	println(hit)
}

func Const_demo() {
	println(1000000000000, 4611686018427387904)
}

func Minmax64_demo() {
	println(min(-2, 1), max(-2, 1), max(U64_of_i64(-1), 1))
}

func Builtins_demo() {
	println(min(3, 5), max(3, 5))
	println(len(make([]int64, 3)))
	m := make(map[int64]int64)
	m[1] = 10
	clear(m)
	n := len(m)
	println(n)
}

func Scmp_demo() {
	println("b" > "a", "a" >= "a", "a" != "b")
}

func Prec_demo() {
	a := 2
	b := 3
	c := 4
	println(a*b+c, (a+b)*c)
}

func Neglit_demo() {
	println(-7, -1, -2147483648)
}

func Panic_and_recover(n int64) {
	defer func() {
		if v := recover(); v != nil {
			recovered := v.(int64)
			println(recovered, recovered+1)
		}
	}()
	panic(n)
}

func Map_demo() {
	m := make(map[int64]int64)
	m[1] = 100
	m[2] = 200
	m[3] = 300
	m[2] = 999
	sz := len(m)
	hit := int64(0)
	if _v, _ok := m[2]; _ok {
		hit = _v
	}
	mis := int64(0)
	if _v, _ok := m[9]; _ok {
		mis = _v
	}
	println(sz, hit, mis)
}

func Slice_demo() {
	xs := []int64{1, 2, 3, 4, 5}
	n := len(xs)
	v := xs[2]
	println(n, v)
	func() {
		defer func() {
			if x := recover(); x != nil {
				println(false)
			}
		}()
		_ = xs[9]
	}()
}

func Chan_demo() {
	ch := make(chan int64, 1)
	ch <- 42
	close(ch)
	x, ok := <-ch
	println(x, ok)
	x2, ok2 := <-ch
	println(x2, ok2)
}

func Select_demo() {
	ch1 := make(chan int64, 1)
	ch2 := make(chan int64, 1)
	ch1 <- 42
	select {
	case x := <-ch1:
		println(x)
	case y := <-ch2:
		println(y)
	}
}

func Select_default_demo() {
	ch := make(chan int64, 1)
	select {
	case x := <-ch:
		println(x)
	default:
		println(99)
	}
}

func Goroutine_demo() {
	ch := make(chan int64)
	go func() {
		ch <- 42
	}()
	x := <-ch
	println(x)
}

func Session_demo() {
	_sess_ch := make(chan any)
	go func() {
		n := (<-_sess_ch).(int64)
		_sess_ch <- n + n
	}()
	_sess_ch <- int64(21)
	result := (<-_sess_ch).(int64)
	println(result)
}

func Adder_demo() {
	_sess_ch := make(chan any)
	go func() {
		a := (<-_sess_ch).(int64)
		b := (<-_sess_ch).(int64)
		_sess_ch <- a + b
	}()
	_sess_ch <- int64(20)
	_sess_ch <- int64(22)
	sum := (<-_sess_ch).(int64)
	println(sum)
}

func Sign_demo(n int64) {
	if n < 10 {
		println(n, true)
	} else {
		println(n, false)
	}
}

func Pick_demo(b bool) {
	if b {
		x := 1
		println(x)
	} else {
		x := 2
		println(x)
	}
}

func Neg_demo() {
	println(2 - 5)
}

func Control_flow_demo() {
	Sign_demo(5)
	Sign_demo(20)
	Pick_demo(true)
	Neg_demo()
}

func Bool_op_demo(a bool, b bool, c bool) {
	println(a && b)
	println(a || b)
	println(!b)
	println((a || b) && c)
}

func And_cond(a int64, b int64) {
	if a < 10 && b < 10 {
		println(1)
	} else {
		println(0)
	}
}

func Or_cond(a int64, b int64) {
	if a < 10 || b < 10 {
		println(1)
	} else {
		println(0)
	}
}

func Not_cond(a int64) {
	if !(a < 10) {
		println(1)
	} else {
		println(0)
	}
}

func Cond_op_demo() {
	And_cond(3, 4)
	Or_cond(30, 4)
	Not_cond(30)
}

func Inline_if_demo() {
	if 3 < 10 {
		println(1)
	} else {
		println(0)
	}
	if 30 < 10 {
		println(1)
	} else {
		println(0)
	}
	if 5 < 10 {
		println(1)
	} else {
		println(0)
	}
}

func Lookup_demo() {
	m := make(map[int64]int64)
	m[7] = 700
	if v, _ok := m[7]; _ok {
		println(v, true)
	} else {
		println(false)
	}
	if v, _ok := m[9]; _ok {
		println(v, true)
	} else {
		println(false)
	}
}

func List_demo() {
	xs := []int64{10, 20, 30}
	if len(xs) == 0 {
		println(false)
	} else {
		x := xs[0]
		rest := xs[1:]
		println(x, len(rest))
	}
}

func Slice_safe_demo() {
	xs := []int64{10, 20, 30}
	var v int64
	ok := 1 >= 0 && 1 < int64(len(xs))
	if ok {
		v = xs[1]
	}
	println(v, ok)
	var v2 int64
	ok2 := 9 >= 0 && 9 < int64(len(xs))
	if ok2 {
		v2 = xs[9]
	}
	println(v2, ok2)
	var v3 int64
	ok3 := Sub(0, 1) >= 0 && Sub(0, 1) < int64(len(xs))
	if ok3 {
		v3 = xs[Sub(0, 1)]
	}
	println(v3, ok3)
}

func Arr_demo() {
	a := [3]int64{10, 20, 30}
	var v int64
	ok := 1 >= 0 && 1 < int64(len(a))
	if ok {
		v = a[1]
	}
	println(v, ok)
	var v2 int64
	ok2 := Sub(10, 5) >= 0 && Sub(10, 5) < int64(len(a))
	if ok2 {
		v2 = a[Sub(10, 5)]
	}
	println(v2, ok2)
}

func Arr_eq_demo() {
	a := [3]int64{1, 2, 3}
	b := [3]int64{1, 2, 3}
	c := [3]int64{1, 2, 9}
	println(a == b, a == c)
}

func Arr_copy_demo() {
	a := [3]int64{10, 20, 30}
	b := func(_a [3]int64) [3]int64 { _a[0] = int64(99); return _a }(a)
	println(a == [3]int64{10, 20, 30}, b == [3]int64{99, 20, 30})
}

func Assert_safe_demo(n int64) {
	defer func() {
		if r := recover(); r != nil {
			v, ok := r.(int64)
			println(v, ok)
			b, ok2 := r.(bool)
			println(b, ok2)
		}
	}()
	panic(n)
}

func String_demo() {
	s := "Go"
	println(int64(len(s)))
	var b int64
	ok := 0 >= 0 && 0 < int64(len(s))
	if ok {
		b = int64(s[0])
	}
	println(b, ok)
	var b2 int64
	ok2 := 5 >= 0 && 5 < int64(len(s))
	if ok2 {
		b2 = int64(s[5])
	}
	println(b2, ok2)
	println(s + "!")
}

func Str_cmp_demo() {
	println("Go" == "Go", "Go" == "No", "abc" < "abd", "b" < "a")
}

func Tsw_demo(a any) {
	switch _tsv := a.(type) {
	case bool:
		b := _tsv
		println(b, 1)
	case string:
		s := _tsv
		println(s, 2)
	default:
		println(9)
	}
}

func Tsw3_demo(a any) {
	switch _tsv := a.(type) {
	case bool:
		b := _tsv
		println(b, 1)
	case string:
		s := _tsv
		println(s, 2)
	case int64:
		n := _tsv
		println(n, 3)
	default:
		println(9)
	}
}

func Tsw_or_demo(a any) {
	switch a.(type) {
	case bool, string:
		println(1)
	default:
		println(0)
	}
}

func Tsw_or3_demo(a any) {
	switch a.(type) {
	case bool, string, int64:
		println(1)
	default:
		println(0)
	}
}

func Int_sw_demo(x int64) {
	switch x {
	case 1:
		println(10)
	case 2:
		println(20)
	default:
		println(99)
	}
}

func Int_sw3_demo(x int64) {
	switch x {
	case 1:
		println(10)
	case 2:
		println(20)
	case 3:
		println(30)
	default:
		println(99)
	}
}

func Complex_demo() {
	c := complex(1.5, 2.5)
	println(real(c), imag(c))
}

func Complex_arith_demo() {
	a := complex(1.0, 2.0)
	b := complex(3.0, 4.0)
	s := a + b
	d := a - b
	println(real(s), imag(s), real(d), imag(d))
}

func Complex_neg_demo() {
	c := complex(3.0, 4.0)
	n := -c
	println(real(n), imag(n))
}

func Complex_mul_demo() {
	a := complex(1.0, 2.0)
	b := complex(3.0, 4.0)
	p := a * b
	println(real(p), imag(p))
}

func Complex_div_demo() {
	a := complex(1.0, 2.0)
	b := complex(3.0, 4.0)
	q := a / b
	println(real(q), imag(q))
}

func Complex_cmp_demo() {
	a := complex(1.0, 2.0)
	b := complex(1.0, 2.0)
	c := complex(1.0, 3.0)
	println(a == b, a == c, a != c)
}

func Str_sw_demo(x string) {
	switch x {
	case "a":
		println(1)
	case "b":
		println(2)
	default:
		println(9)
	}
}

func Bytes_demo() {
	b := []byte("Hi")
	println(string(b))
}

func Defer_loop_demo() {
	i := int64(0)
	var iv int64
	for {
		iv = i
		if iv < 3 {
			defer func(iv int64) {
				println(iv)
			}(iv)
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Defer_demo() {
	defer func() {
		println(1)
	}()
	defer func() {
		println(2)
	}()
	println(3)
}

func Mut_demo() {
	r := int64(10)
	a := r
	r = Add(a, 5)
	b := r
	println(b)
}

func Ptr_demo() {
	p := func(_v int64) *int64 { return &_v }(int64(10))
	a := *p
	println(a)
	*p = int64(99)
	b := *p
	println(b)
}

func New_demo() {
	p := new(int64)
	v := *p
	println(v)
}

func Ptr_safe_demo() {
	p := func(_v int64) *int64 { return &_v }(int64(42))
	var v int64
	ok := p != nil
	if ok {
		v = *p
	}
	println(v, ok)
	var v2 int64
	ok2 := ((*int64)(nil)) != nil
	if ok2 {
		v2 = *((*int64)(nil))
	}
	println(v2, ok2)
}

func Slice_alias_demo() {
	s := make([]int64, 3)
	s[0] = int64(10)
	s[1] = int64(20)
	(s[1:3])[0] = int64(99)
	v := s[1]
	println(v)
}

func Slice_append_demo() {
	s := make([]int64, 2)
	s[0] = int64(5)
	s2 := append(s, int64(9))
	v := s2[2]
	println(v)
}

func Slice_makecap_demo() {
	s := make([]int64, 1, 3)
	s[0] = int64(5)
	s2 := append(s, int64(8))
	s2[0] = int64(77)
	v := s[0]
	println(v)
}

func Slice_clear_demo() {
	s := make([]int64, 2)
	s[0] = int64(5)
	clear(s)
	v := s[0]
	println(v)
}

func Slice_copy_demo() {
	dst := make([]int64, 2)
	src := make([]int64, 2)
	src[0] = int64(7)
	copy(dst, src)
	v := dst[0]
	println(v)
}

func Count_demo() {
	i := int64(0)
	var iv int64
	for {
		iv = i
		if iv < 3 {
			println(iv)
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Cond_goto_demo(early bool) {
	println(1)
	if !early {
		println(2)
	}
	println(3)
	return
}

func Diamond_demo(b bool) {
	println(1)
	if b {
		println(10)
	} else {
		println(20)
	}
	println(99)
	return
}

func Loopif_demo() {
	i := int64(0)
	var iv int64
	for {
		iv = i
		if iv < 3 {
			iv = i
			if iv < 1 {
				println(100)
			}
			iv = i
			println(iv)
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Nested_loop_demo() {
	i := int64(0)
	j := int64(0)
	var jv int64
	var iv int64
	for {
		iv = i
		if iv < 2 {
			j = int64(0)
			for {
				jv = j
				if jv < 2 {
					jv = j
					println(jv)
					j = Add(jv, 1)
				} else {
					break
				}
			}
			iv = i
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Early_return_demo() {
	i := int64(0)
	var iv int64
	for {
		iv = i
		if iv < 9 {
			iv = i
			if iv < 2 {
				iv = i
				println(iv)
				i = Add(iv, 1)
			} else {
				return
			}
		} else {
			break
		}
	}
	println(999)
	return
}

func Labeled_break_demo() {
	i := int64(0)
	j := int64(0)
	var jv int64
	var iv int64
L0:
	for {
		iv = i
		if iv < 3 {
			j = int64(0)
			for {
				jv = j
				if jv < 3 {
					jv = j
					println(jv)
					if jv < 2 {
						jv = j
						j = Add(jv, 1)
					} else {
						break L0
					}
				} else {
					break
				}
			}
			iv = i
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Labeled_continue_demo() {
	i := int64(0)
	j := int64(0)
	var iv int64
	var jv int64
L0:
	for {
		iv = i
		i = Add(iv, 1)
		if iv < 2 {
			j = int64(0)
			for {
				jv = j
				if jv < 3 {
					jv = j
					println(jv)
					j = Add(jv, 1)
					if !(jv < 1) {
						continue L0
					}
				} else {
					break
				}
			}
		} else {
			break
		}
	}
	return
}

func Irreducible_demo(enter_high bool) {
	n := int64(0)
	var nv int64
	if enter_high {
		goto block2
	} else {
		goto block1
	}
block1:
	nv = n
	println(1)
	n = Add(nv, 1)
	goto block2
block2:
	nv = n
	println(2)
	n = Add(nv, 1)
	if nv < 3 {
		goto block1
	} else {
		goto block3
	}
block3:
	return
}

func Foreach_demo() {
	xs := []int64{10, 20, 30}
	for _, x := range xs {
		println(x)
	}
}

func Sum_demo() {
	xs := []int64{1, 2, 3, 4}
	total := int64(0)
	for _, x := range xs {
		total = total + x
	}
	println(total)
}

type Point struct {
	Px int64
	Py int64
}

func Point_demo() {
	p := Point{3, 4}
	println(p.Px)
	println(p.Py)
	println(p.Px + p.Py)
}

type Labeled struct {
	Flag bool
	Qty  int64
}

func Labeled_demo() {
	r := Labeled{true, 5}
	println(r.Flag)
	println(r.Qty)
}

func (p Point) Sum_coords() int64 {
	return p.Px + p.Py
}

func (p Point) Shifted(dx int64) Point {
	return Point{p.Px + dx, p.Py + dx}
}

func Method_demo() {
	p := Point{3, 4}
	q := p.Shifted(10)
	println(p.Sum_coords())
	println(q.Px)
	println(q.Py)
	println(q.Sum_coords())
}

func Call_shift10(f func(int64) Point) Point {
	return f(10)
}

func Method_value_demo() {
	p := Point{1, 2}
	q := Call_shift10(p.Shifted)
	println(q.Px, q.Py)
}

func Apply_pt(f func(Point) int64, p Point) int64 {
	return f(p)
}

func Method_expr_demo() {
	p := Point{5, 6}
	println(Apply_pt(Point.Sum_coords, p))
}

func Swap2(a int64, b int64) (int64, int64) {
	return b, a
}

func Multiret_demo() {
	x, y := Swap2(3, 4)
	println(x, y)
}

func (p Point) Describe() {
	println(p.Px)
	println(p.Py)
}

func Io_method_demo() {
	p := Point{8, 9}
	p.Describe()
}

func (a Point) Point_eqb(b Point) bool {
	return a.Px == b.Px && a.Py == b.Py
}

func Struct_eq_demo() {
	p := Point{3, 4}
	q := Point{3, 4}
	r := Point{3, 5}
	println(p.Point_eqb(q), p.Point_eqb(r))
}

func Struct_eq_native_demo() {
	p := Point{3, 4}
	q := Point{3, 4}
	r := Point{3, 5}
	println(p == q, p == r)
}

type Inner struct {
	Iv    int64
	Ikind int64
}

type Wrap struct {
	W_inner Inner
	Wz      int64
}

func Nested_struct_demo() {
	o := Wrap{Inner{5, 1}, 9}
	println((o.W_inner).Iv, o.Wz)
}

type Cell struct {
	Cx int64
	Cy int64
}

func Sptr_demo() {
	p := &Cell{3, 4}
	p.Cx = int64(7)
	a := p.Cx
	b := p.Cy
	println(a, b)
}

func (p *Cell) Cell_incx() {
	a := p.Cx
	p.Cx = a + 1
}

func Ptr_method_demo() {
	p := &Cell{10, 20}
	p.Cell_incx()
	a := p.Cx
	println(a)
}

type Shape struct {
	Area  func(int64) int64
	Perim func(int64) int64
}

func Mk_rect(w int64, h int64) Shape {
	return Shape{func(s int64) int64 {
		return w + h + (w + h) + s
	}, func(s int64) int64 {
		return w + h + s
	}}
}

func Mk_square(side int64) Shape {
	return Shape{func(s int64) int64 {
		return side + side + (side + side) + s
	}, func(s int64) int64 {
		return side + side + s
	}}
}

func (sh Shape) Show_shape() {
	println(sh.Area(0))
	println(sh.Perim(1000))
}

func Iface_demo() {
	(Mk_rect(3, 4)).Show_shape()
	(Mk_square(5)).Show_shape()
}

type Greeter struct {
	Greet   func(int64) int64
	Gr_self any
}

func Mk_adder(base int64) Greeter {
	return Greeter{func(x int64) int64 {
		return base + x
	}, base}
}

func Single_iface_demo() {
	println((Mk_adder(5)).Greet(10))
}

type Light struct {
	Ticks  int64
	Serial int64
}

var Fresh_light Light = Light{0, 7}

func (l Light) Go_green() Light {
	return Light{l.Ticks + 1, l.Serial}
}

func (l Light) Go_red() Light {
	return Light{l.Ticks, l.Serial}
}

func Typestate_demo() {
	l0 := Fresh_light
	l1 := l0.Go_green()
	l2 := l1.Go_red()
	println(l2.Ticks)
	println(l2.Serial)
}

type Sorted2 struct {
	S_a int64
	S_b int64
}

func (p Sorted2) Min_of() int64 {
	return p.S_a
}

func (p Sorted2) Max_of() int64 {
	return p.S_b
}

var Demo_pair Sorted2 = Sorted2{3, 7}

func Repinv_demo() {
	println(Demo_pair.Min_of())
	println(Demo_pair.Max_of())
}

func main() {
	println(1 + 2)
	Panic_and_recover(40 + 2)
	Div_demo()
	Overflow_safe_demo()
	I64_abs_demo()
	Neg_op_demo()
	Conv64_demo()
	Minmax64_demo()
	Cmp_ops_demo()
	Float_demo()
	Float_cmp_demo()
	Float_nan_demo(0.0)
	Float_opp_demo()
	Float_opp_sign_demo(0.0)
	Fminmax_demo()
	Fcmp_demo()
	U8_demo()
	Fw_cmp_demo()
	I8_demo()
	U16_demo()
	Bitwise_demo()
	Shift_demo()
	Convert_demo()
	Divmod_demo()
	U32_demo()
	I64_demo()
	I64_ops_demo()
	U64_demo()
	I64_pipeline_demo()
	U64_pipeline_demo()
	Const_demo()
	Recv_unused_ok_demo()
	Builtins_demo()
	Prec_demo()
	Neglit_demo()
	Map_demo()
	Slice_demo()
	Chan_demo()
	Select_demo()
	Select_default_demo()
	Goroutine_demo()
	Session_demo()
	Adder_demo()
	Control_flow_demo()
	Bool_op_demo(true, false, true)
	Cond_op_demo()
	Inline_if_demo()
	Lookup_demo()
	List_demo()
	Slice_safe_demo()
	Arr_demo()
	Arr_eq_demo()
	Arr_copy_demo()
	Assert_safe_demo(7)
	String_demo()
	Str_cmp_demo()
	Bytes_demo()
	Tsw_demo(true)
	Tsw_demo("go")
	Tsw_demo(5)
	Tsw3_demo(true)
	Tsw3_demo("hi")
	Tsw3_demo(I64_abs(5))
	Tsw_or_demo(true)
	Tsw_or_demo("x")
	Tsw_or_demo(5)
	Tsw_or3_demo(true)
	Tsw_or3_demo("z")
	Tsw_or3_demo(5)
	Int_sw_demo(1)
	Int_sw_demo(2)
	Int_sw_demo(5)
	Int_sw3_demo(3)
	Int_sw3_demo(8)
	Str_sw_demo("a")
	Str_sw_demo("b")
	Str_sw_demo("z")
	Complex_demo()
	Complex_arith_demo()
	Complex_mul_demo()
	Complex_div_demo()
	Complex_neg_demo()
	Complex_cmp_demo()
	Scmp_demo()
	Foreach_demo()
	Sum_demo()
	Cond_goto_demo(true)
	Cond_goto_demo(false)
	Diamond_demo(true)
	Diamond_demo(false)
	Loopif_demo()
	Nested_loop_demo()
	Early_return_demo()
	Labeled_break_demo()
	Labeled_continue_demo()
	Irreducible_demo(false)
	Irreducible_demo(true)
	Mut_demo()
	Ptr_demo()
	New_demo()
	Ptr_safe_demo()
	Slice_alias_demo()
	Slice_append_demo()
	Slice_makecap_demo()
	Slice_clear_demo()
	Slice_copy_demo()
	Count_demo()
	Defer_demo()
	Defer_loop_demo()
	Point_demo()
	Labeled_demo()
	Method_demo()
	Method_value_demo()
	Method_expr_demo()
	Multiret_demo()
	Io_method_demo()
	Struct_eq_demo()
	Struct_eq_native_demo()
	Nested_struct_demo()
	Sptr_demo()
	Ptr_method_demo()
	Iface_demo()
	Single_iface_demo()
	Typestate_demo()
	Repinv_demo()
}
