// Code generated by rocq-go-extraction; DO NOT EDIT.

package main

func Andb(b1 bool, b2 bool) bool {
	if b1 {
		return b2
	} else {
		return false
	}
}

func Orb(b1 bool, b2 bool) bool {
	if b1 {
		return true
	} else {
		return b2
	}
}

func Xorb(b1 bool, b2 bool) bool {
	if b1 {
		if b2 {
			return false
		} else {
			return true
		}
	} else {
		return b2
	}
}

func Negb(b bool) bool {
	if b {
		return false
	} else {
		return true
	}
}

type Comparison int

const (
	Eq Comparison = iota
	Lt
	Gt
)

type ListNode struct {
	Ln_val  int64
	Ln_next *ListNode
}

type ChanBox struct {
	Cb_id   int64
	Cb_chan chan ChanBox
}

func I64_abs(a int64) int64 {
	if a < 0 {
		return 0 - a
	} else {
		return a
	}
}

func U64_of_i64(a int64) uint64 {
	return uint64(a)
}

func I64_of_u64(a uint64) int64 {
	return int64(a)
}

func Ceqb[T1 comparable](a T1, b T1) bool {
	return a == b
}

func Add(n int, m int) int {
	return n + m
}

func Sub(n int, m int) int {
	return n - m
}

func I64_add_nz(a int64, b int64) int64 {
	return a + b
}

func I64_mul_nz(a int64, b int64) int64 {
	return a * b
}

func Overflow_safe_demo() {
	println(I64_add_nz(1000000000000, 2000000000000), I64_mul_nz(1000, 1000))
}

func I64_abs_demo() {
	println(I64_abs(-7), I64_abs(7), I64_abs(-9223372036854775808))
}

func Neg_op_demo() {
	println(func(x int64) int64 { return -x }(5), func(x int64) int64 { return -x }(func(x int64, y int64) int64 { return x - y }(0, 7)))
}

func Conv64_demo() {
	println(U64_of_i64(-1), I64_of_u64(18446744073709551615), U64_of_i64(255))
}

func Cmp_ops_demo() {
	println(5 > 3, 5 >= 5, 5 != 3, 18446744073709551615 > 1)
}

func Div_nz(n int, d int) int {
	return n / d
}

func Mod_nz(n int, d int) int {
	return n % d
}

func Div_demo() {
	println(Div_nz(17, 5), Mod_nz(17, 5))
}

func Float_demo() {
	println(func(x float64, y float64) float64 { return x + y }(1.5, 2.25), func(x float64, y float64) float64 { return x / y }(1.0, 4.0))
}

func Float_cmp_demo() {
	println(1.5 < 2.5)
	println(2.5 <= 2.5)
	println(1.5 == 1.5)
	println(3.0 < 2.0)
}

func Float_nan_demo(z float64) {
	println(z/z == z/z)
	println(z/z < 1.0)
}

func Float_opp_demo() {
	println(func(x float64) float64 { return -x }(1.5))
	println(func(x float64) float64 { return -x }(func(x float64) float64 { return -x }(2.0)))
}

func Float_opp_sign_demo(z float64) {
	println(func(x float64, y float64) float64 { return x / y }(1.0, -z) < 0.0)
}

func Fminmax_demo() {
	println(func(x float64, y float64) float64 { return min(x, y) }(3.0, 5.0), func(x float64, y float64) float64 { return max(x, y) }(3.0, 5.0))
}

func Fcmp_demo() {
	println(5.0 > 3.0, 3.0 >= 3.0, 5.0 != 3.0)
}

func F32_combine(a float32, b float32, c float32) float32 {
	return (a + b) * c
}

func F32_demo() {
	println(F32_combine(func(x float64) float32 { return float32(x) }(1.5), func(x float64) float32 { return float32(x) }(2.25), func(x float64) float32 { return float32(x) }(2.0)))
}

func I64_of_narrow_demo() {
	println((200 & 0xff), (((-5 & 0xff) ^ 0x80) - 0x80), (60000 & 0xffff))
}

func I64_to_narrow_demo() {
	println(uint8(((4660) & 0xff)), int8(((((200) & 0xff) ^ 0x80) - 0x80)), uint16(((70000) & 0xffff)), int32(((((5000000000) & 0xffffffff) ^ 0x80000000) - 0x80000000)))
}

func Narrow_let_assert_demo() {
	xu8 := ((200) & 0xff)
	v8, ok1 := any(uint8(xu8)).(uint8)
	println(v8, ok1)
}

func Lowbyte(x int64) uint8 {
	return uint8((x & 0xff))
}

func Lowbyte_i8(x int64) int8 {
	return int8((((x & 0xff) ^ 0x80) - 0x80))
}

func Narrow_ret_demo() {
	println(Lowbyte(4660), Lowbyte_i8(200))
}

func Narrow_u64_demo() {
	println(U64_of_i64((200 & 0xff)), U64_of_i64((((-1 & 0xff) ^ 0x80) - 0x80)), uint8(((I64_of_u64(511)) & 0xff)), int8(((((I64_of_u64(255)) & 0xff) ^ 0x80) - 0x80)))
}

func Narrow32(x float64) float32 {
	return float32(x)
}

func Widen64(x float32) float64 {
	return float64(x)
}

func F32_extra_demo() {
	println(func(x float32) float32 { return -x }(func(x float64) float32 { return float32(x) }(1.5)), func(x float32, y float32) float32 { return min(x, y) }(func(x float64) float32 { return float32(x) }(3.0), func(x float64) float32 { return float32(x) }(5.0)), func(x float32, y float32) float32 { return max(x, y) }(func(x float64) float32 { return float32(x) }(3.0), func(x float64) float32 { return float32(x) }(5.0)))
}

func F32_conv_demo() {
	println(func(x float64) float32 { return float32(x) }(float64(16777217)), func(x float64) float32 { return float32(x) }(float64(30.0/100.0)))
}

func Narrow_f32_demo() {
	println(int64(float64(float32((200 & 0xff)))))
}

func F32_const_runtime_demo() {
	println(func(x float32, y float32) float32 { return x / y }(func(x float64) float32 { return float32(x) }(1.0), func(x float64) float32 { return float32(x) }(0.0)), func(x float32, y float32) float32 { return x / y }(func(x float64) float32 { return float32(x) }(1.0), func(x float32) float32 { return -x }(func(x float64) float32 { return float32(x) }(0.0))), func(x float64) float32 { return float32(x) }(1e+40), func(x float64, y float64) float64 { return x / y }(1.0, 0.0))
}

func F32_of_int_demo() {
	println(float32(2305843146652647425) == func(x float64) float32 { return float32(x) }(float64(2305843146652647425)))
}

func F32_fconst_demo() {
	println(float32(30.0 / 100.0))
}

func F64_fconst_big_demo() {
	println(float64(9007199254740993.0 / 10.0))
}

func Floatconv_demo() {
	println(Narrow32(16777217.0))
	println(Widen64(Narrow32(7.5)))
}

func Fconst_demo() {
	println(float64(30.0/100.0), float64(3.0/8.0), float64(1.0/4.0))
}

func F32_cmp_demo() {
	println(F32_combine(func(x float64) float32 { return float32(x) }(1.5), func(x float64) float32 { return float32(x) }(0.0), func(x float64) float32 { return float32(x) }(2.0)) < F32_combine(func(x float64) float32 { return float32(x) }(5.0), func(x float64) float32 { return float32(x) }(0.0), func(x float64) float32 { return float32(x) }(2.0)), F32_combine(func(x float64) float32 { return float32(x) }(5.0), func(x float64) float32 { return float32(x) }(0.0), func(x float64) float32 { return float32(x) }(2.0)) >= F32_combine(func(x float64) float32 { return float32(x) }(1.5), func(x float64) float32 { return float32(x) }(0.0), func(x float64) float32 { return float32(x) }(2.0)), F32_combine(func(x float64) float32 { return float32(x) }(1.5), func(x float64) float32 { return float32(x) }(0.0), func(x float64) float32 { return float32(x) }(2.0)) != F32_combine(func(x float64) float32 { return float32(x) }(5.0), func(x float64) float32 { return float32(x) }(0.0), func(x float64) float32 { return float32(x) }(2.0)))
}

func Trunc64(x float64) int64 {
	return int64(x)
}

func I64_of_f64_demo() {
	println(Trunc64(3.7000000000000002), Trunc64(func(x float64) float64 { return -x }(2.8999999999999999)))
}

func U64_trunc(x float64) uint64 {
	return uint64(x)
}

func U64_to_f64(x uint64) float64 {
	return float64(x)
}

func U64conv_demo() {
	println(U64_to_f64(18446744073709551615), U64_trunc(U64_to_f64(13835058055282163712)))
}

func F64_of_int_demo() {
	println(float64(5), float64(-3))
}

func F64_of_i64_demo() {
	println(float64(7), float64(-3))
}

func U8_demo() {
	println(uint8((((200 & 0xff) + (100 & 0xff)) & 0xff)))
	println(uint8((((255 & 0xff) * (255 & 0xff)) & 0xff)))
	println(uint8((((0 & 0xff) - (1 & 0xff)) & 0xff)))
	println((10 & 0xff) < (20 & 0xff))
}

func I8_demo() {
	println(int8((((((((100 & 0xff) ^ 0x80) - 0x80) + (((50 & 0xff) ^ 0x80) - 0x80)) & 0xff) ^ 0x80) - 0x80)))
	println(int8((((((((-128 & 0xff) ^ 0x80) - 0x80) - (((1 & 0xff) ^ 0x80) - 0x80)) & 0xff) ^ 0x80) - 0x80)))
	println(int8((((-100 & 0xff) ^ 0x80) - 0x80)))
	println((((-5 & 0xff) ^ 0x80) - 0x80) < (((3 & 0xff) ^ 0x80) - 0x80))
}

func Fw_cmp_demo() {
	println((200&0xff) > (100&0xff), (((5&0xff)^0x80)-0x80) >= (((5&0xff)^0x80)-0x80), (((5&0xff)^0x80)-0x80) != (((-5&0xff)^0x80)-0x80), (4000000000&0xffffffff) > (1&0xffffffff))
}

func U16_demo() {
	println(uint16((((60000 & 0xffff) + (10000 & 0xffff)) & 0xffff)))
	println(uint16((((1000 & 0xffff) * (1000 & 0xffff)) & 0xffff)))
	println(int16((((((((30000 & 0xffff) ^ 0x8000) - 0x8000) + (((10000 & 0xffff) ^ 0x8000) - 0x8000)) & 0xffff) ^ 0x8000) - 0x8000)))
}

func Bitwise_demo() {
	println(uint8((240&0xff)&(60&0xff)), uint8((240&0xff)|(60&0xff)), uint8((240&0xff)^(60&0xff)))
	println(uint8((240&0xff)&^(60&0xff)), uint8((^(240 & 0xff) & 0xff)))
	println(int8((((^(((5 & 0xff) ^ 0x80) - 0x80) & 0xff) ^ 0x80) - 0x80)), int8((((-1&0xff)^0x80)-0x80)&^(((5&0xff)^0x80)-0x80)))
}

func Shift_demo() {
	println(uint8((((1 & 0xff) << 3) & 0xff)), uint8((((1 & 0xff) << 8) & 0xff)), uint8(((255 & 0xff) >> 4)))
	println(int8((((((((64 & 0xff) ^ 0x80) - 0x80) << 1) & 0xff) ^ 0x80) - 0x80)), int8(((((-3 & 0xff) ^ 0x80) - 0x80) >> 1)))
}

func Convert_demo() {
	a := (200 & 0xff)
	b := (((1000 & 0xffff) ^ 0x8000) - 0x8000)
	println(a, uint8(((b) & 0xff)))
	println(int16(((((b + ((((a) & 0xffff) ^ 0x8000) - 0x8000)) & 0xffff) ^ 0x8000) - 0x8000)))
}

func Divmod_demo() {
	println(uint8(((200 & 0xff) / (7 & 0xff))), uint8(((200 & 0xff) % (7 & 0xff))), int8((((((((-128 & 0xff) ^ 0x80) - 0x80) / (((-1 & 0xff) ^ 0x80) - 0x80)) & 0xff) ^ 0x80) - 0x80)))
}

func U32_demo() {
	println(uint32((((4000000000 & 0xffffffff) + (1000000000 & 0xffffffff)) & 0xffffffff)), int32((((((((2000000000 & 0xffffffff) ^ 0x80000000) - 0x80000000) + (((2000000000 & 0xffffffff) ^ 0x80000000) - 0x80000000)) & 0xffffffff) ^ 0x80000000) - 0x80000000)))
	println(uint32((((1 & 0xffffffff) << 31) & 0xffffffff)))
	println(uint32((((100000 & 0xffffffff) * (100000 & 0xffffffff)) & 0xffffffff)), int32((((((((46341 & 0xffffffff) ^ 0x80000000) - 0x80000000) * (((46341 & 0xffffffff) ^ 0x80000000) - 0x80000000)) & 0xffffffff) ^ 0x80000000) - 0x80000000)))
}

func I64_demo() {
	println(func(x int64, y int64) int64 { return x + y }(9000000000000000000, 200000000000000000), func(x int64, y int64) int64 { return x * y }(3000000000, 3000000000))
}

func I64_ops_demo() {
	println(func(x int64, y int64) int64 { return x / y }(9000000000000000000, 7), func(x int64, y int64) int64 { return x << y }(1, 40))
	println(func(x int64, y int64) int64 { return x & y }(-1, 4294967295), func(x int64) int64 { return ^x }(5))
}

var Uc_bignum int64 = 1099511627781

var Uc_mask int64 = 1048575

var Uc_product int64 = 1000000000000

var Uc_100_i64 int64 = 100

var Uc_100_u8 uint8 = (100 & 0xff)

var Uc_u64_hi uint64 = 9223372036854775808

var Uc_u64_msk uint64 = 4294967295

func Uconst_demo() {
	println(Uc_bignum, Uc_mask, Uc_product, Uc_100_i64, Uc_100_u8, Uc_u64_hi, Uc_u64_msk)
}

func U64_demo() {
	println(func(x uint64, y uint64) uint64 { return x + y }(5000000000000000000, 3000000000000000000), func(x uint64, y uint64) uint64 { return x * y }(3000000000, 3000000000))
}

func Recv_unused_ok_demo() {
	ch := make(chan int64, 1)
	ch <- 77
	x, _ := <-ch
	println(x)
}

func I64_pipeline_demo() {
	ch := make(chan int64, 1)
	ch <- 9000000000000000001
	x := <-ch
	m := make(map[int64]int64)
	m[42] = x
	hit := int64(0)
	if _v, _ok := m[42]; _ok {
		hit = _v
	}
	println(hit)
}

func U64_pipeline_demo() {
	ch := make(chan uint64, 1)
	ch <- 18000000000000000000
	x := <-ch
	m := make(map[uint64]uint64)
	m[7] = x
	hit := uint64(0)
	if _v, _ok := m[7]; _ok {
		hit = _v
	}
	println(hit)
}

func Const_demo() {
	println(1000000000000, 4611686018427387904)
}

func Minmax64_demo() {
	println(min(-2, 1), max(-2, 1), max(U64_of_i64(-1), 1))
}

func Builtins_demo() {
	println(min(3, 5), max(3, 5))
	println(len(make([]int64, 3)))
	m := make(map[int64]int64)
	m[1] = 10
	clear(m)
	n := len(m)
	println(n)
}

func Str_slice_demo() {
	println("Hello, world"[7:12])
}

func Scmp_demo() {
	println("b" > "a", "a" >= "a", "a" != "b")
}

func Prec_demo() {
	a := 2
	b := 3
	c := 4
	println(a*b+c, (a+b)*c)
}

func Neglit_demo() {
	println(-7, -1, -2147483648)
}

func Panic_and_recover(n int64) {
	defer func() {
		if v := recover(); v != nil {
			recovered := v.(int64)
			println(recovered, recovered+1)
		}
	}()
	panic(n)
}

func Map_demo() {
	m := make(map[int64]int64)
	m[1] = 100
	m[2] = 200
	m[3] = 300
	m[2] = 999
	sz := len(m)
	hit := int64(0)
	if _v, _ok := m[2]; _ok {
		hit = _v
	}
	mis := int64(0)
	if _v, _ok := m[9]; _ok {
		mis = _v
	}
	println(sz, hit, mis)
}

func Map_put(m map[int64]int64) {
	m[7] = 77
}

func Map_alias_demo() {
	m := make(map[int64]int64)
	Map_put(m)
	v := int64(0)
	if _v, _ok := m[7]; _ok {
		v = _v
	}
	println(v)
}

func Slice_demo() {
	xs := []int64{1, 2, 3, 4, 5}
	n := len(xs)
	v := xs[2]
	println(n, v)
	func() {
		defer func() {
			if x := recover(); x != nil {
				println(false)
			}
		}()
		_ = xs[9]
	}()
}

func Chan_demo() {
	ch := make(chan int64, 1)
	ch <- 42
	close(ch)
	x, ok := <-ch
	println(x, ok)
	x2, ok2 := <-ch
	println(x2, ok2)
}

func Select_demo() {
	ch1 := make(chan int64, 1)
	ch2 := make(chan int64, 1)
	ch1 <- 42
	select {
	case x := <-ch1:
		println(x)
	case y := <-ch2:
		println(y)
	}
}

func Select_default_demo() {
	ch := make(chan int64, 1)
	select {
	case x := <-ch:
		println(x)
	default:
		println(99)
	}
}

func Goroutine_demo() {
	ch := make(chan int64)
	go func() {
		ch <- 42
	}()
	x := <-ch
	println(x)
}

func Session_demo() {
	_sess_ch := make(chan any)
	go func() {
		n := (<-_sess_ch).(int64)
		_sess_ch <- n + n
	}()
	_sess_ch <- int64(21)
	result := (<-_sess_ch).(int64)
	println(result)
}

func Adder_demo() {
	_sess_ch := make(chan any)
	go func() {
		a := (<-_sess_ch).(int64)
		b := (<-_sess_ch).(int64)
		_sess_ch <- a + b
	}()
	_sess_ch <- int64(20)
	_sess_ch <- int64(22)
	sum := (<-_sess_ch).(int64)
	println(sum)
}

func Sign_demo(n int64) {
	if n < 10 {
		println(n, true)
	} else {
		println(n, false)
	}
}

func Pick_demo(b bool) {
	if b {
		x := 1
		println(x)
	} else {
		x := 2
		println(x)
	}
}

func Neg_demo() {
	println(func(x int64, y int64) int64 { return x - y }(2, 5))
}

func Control_flow_demo() {
	Sign_demo(5)
	Sign_demo(20)
	Pick_demo(true)
	Neg_demo()
}

func Bool_op_demo(a bool, b bool, c bool) {
	println(Andb(a, b))
	println(Orb(a, b))
	println(Negb(b))
	println(Andb(Orb(a, b), c))
}

func And_cond(a int64, b int64) {
	if Andb(a < 10, b < 10) {
		println(1)
	} else {
		println(0)
	}
}

func Or_cond(a int64, b int64) {
	if Orb(a < 10, b < 10) {
		println(1)
	} else {
		println(0)
	}
}

func Not_cond(a int64) {
	if Negb(a < 10) {
		println(1)
	} else {
		println(0)
	}
}

func Cond_op_demo() {
	And_cond(3, 4)
	Or_cond(30, 4)
	Not_cond(30)
}

func Inline_if_demo() {
	if 3 < 10 {
		println(1)
	} else {
		println(0)
	}
	if 30 < 10 {
		println(1)
	} else {
		println(0)
	}
	if 5 < 10 {
		println(1)
	} else {
		println(0)
	}
}

func Lookup_demo() {
	m := make(map[int64]int64)
	m[7] = 700
	if v, _ok := m[7]; _ok {
		println(v, true)
	} else {
		println(false)
	}
	if v, _ok := m[9]; _ok {
		println(v, true)
	} else {
		println(false)
	}
}

func List_demo() {
	xs := []int64{10, 20, 30}
	if len(xs) == 0 {
		println(false)
	} else {
		x := xs[0]
		rest := xs[1:]
		println(x, len(rest))
	}
}

func Slice_safe_demo() {
	xs := []int64{10, 20, 30}
	var v int64
	ok := 1 >= 0 && 1 < len(xs)
	if ok {
		v = xs[1]
	}
	println(v, ok)
	var v2 int64
	ok2 := 9 >= 0 && 9 < len(xs)
	if ok2 {
		v2 = xs[9]
	}
	println(v2, ok2)
	var v3 int64
	ok3 := Sub(0, 1) >= 0 && Sub(0, 1) < len(xs)
	if ok3 {
		v3 = xs[Sub(0, 1)]
	}
	println(v3, ok3)
}

func Arr_demo() {
	a := [3]int64{10, 20, 30}
	var v int64
	ok := 1 >= 0 && 1 < len(a)
	if ok {
		v = a[1]
	}
	println(v, ok)
	var v2 int64
	ok2 := Sub(10, 5) >= 0 && Sub(10, 5) < len(a)
	if ok2 {
		v2 = a[Sub(10, 5)]
	}
	println(v2, ok2)
}

var VecN_a [3]int64 = [3]int64{10, 20, 30}

var VecN_b [3]int64 = [3]int64{10, 20, 99}

func Vec3_eqb(a [3]int64, b [3]int64) bool {
	return a == b
}

var PairN [2]int64 = [2]int64{7, 8}

func Vec2_eqb(a [2]int64, b [2]int64) bool {
	return a == b
}

func ArrN_demo() {
	println(Vec3_eqb(VecN_a, VecN_a), Vec3_eqb(VecN_a, VecN_b), Vec2_eqb(PairN, PairN))
}

func Vec3_id(a [3]int64) [3]int64 {
	return a
}

type Triple struct {
	T_vec   [3]int64
	T_label int64
}

func Arr_field_ret_demo() {
	tr := Triple{T_vec: [3]int64{4, 5, 6}, T_label: 77}
	println(Vec3_eqb(Vec3_id(tr.T_vec), tr.T_vec))
	println(tr.T_label)
}

func Arr_eq_demo() {
	a := [3]int64{1, 2, 3}
	b := [3]int64{1, 2, 3}
	c := [3]int64{1, 2, 9}
	println(a == b, a == c)
}

func Arr_copy_demo() {
	a := [3]int64{10, 20, 30}
	b := func(_a [3]int64) [3]int64 { _a[0] = int64(99); return _a }(a)
	println(a == [3]int64{10, 20, 30}, b == [3]int64{99, 20, 30})
}

func Assert_safe_demo(n int64) {
	defer func() {
		if r := recover(); r != nil {
			v, ok := r.(int64)
			println(v, ok)
			b, ok2 := r.(bool)
			println(b, ok2)
		}
	}()
	panic(n)
}

func String_demo() {
	s := "Go"
	println(len(s))
	var b int64
	ok := 0 >= 0 && 0 < len(s)
	if ok {
		b = int64(s[0])
	}
	println(b, ok)
	var b2 int64
	ok2 := 5 >= 0 && 5 < len(s)
	if ok2 {
		b2 = int64(s[5])
	}
	println(b2, ok2)
	println(s + "!")
}

func Str_cmp_demo() {
	println("Go" == "Go", "Go" == "No", "abc" < "abd", "b" < "a")
}

func Tsw_demo(a any) {
	switch _tsv := a.(type) {
	case bool:
		b := _tsv
		println(b, 1)
	case string:
		s := _tsv
		println(s, 2)
	default:
		println(9)
	}
}

func Tsw3_demo(a any) {
	switch _tsv := a.(type) {
	case bool:
		b := _tsv
		println(b, 1)
	case string:
		s := _tsv
		println(s, 2)
	case int64:
		n := _tsv
		println(n, 3)
	default:
		println(9)
	}
}

func Tsw_or_demo(a any) {
	switch a.(type) {
	case bool, string:
		println(1)
	default:
		println(0)
	}
}

func Tsw_or3_demo(a any) {
	switch a.(type) {
	case bool, string, int64:
		println(1)
	default:
		println(0)
	}
}

func Int_sw_demo(x int64) {
	switch x {
	case 1:
		println(10)
	case 2:
		println(20)
	default:
		println(99)
	}
}

func Int_sw3_demo(x int64) {
	switch x {
	case 1:
		println(10)
	case 2:
		println(20)
	case 3:
		println(30)
	default:
		println(99)
	}
}

func Complex_demo() {
	c := complex(1.5, 2.5)
	println(real(c), imag(c))
}

func Complex_arith_demo() {
	a := complex(1.0, 2.0)
	b := complex(3.0, 4.0)
	s := a + b
	d := a - b
	println(real(s), imag(s), real(d), imag(d))
}

func Complex_neg_demo() {
	c := complex(3.0, 4.0)
	n := -c
	println(real(n), imag(n))
}

func Complex_const_runtime_demo() {
	println(func(x float64, y float64) float64 { return x / y }(1.0, real(func(x complex128) complex128 { return -x }(complex(0.0, 0.0)))))
}

func Complex_mul_demo() {
	a := complex(1.0, 2.0)
	b := complex(3.0, 4.0)
	p := a * b
	println(real(p), imag(p))
}

func Complex_div_demo() {
	a := complex(1.0, 2.0)
	b := complex(3.0, 4.0)
	q := a / b
	println(real(q), imag(q))
}

func Complex_cmp_demo() {
	a := complex(1.0, 2.0)
	b := complex(1.0, 2.0)
	c := complex(1.0, 3.0)
	println(a == b, a == c, a != c)
}

func Str_sw_demo(x string) {
	switch x {
	case "a":
		println(1)
	case "b":
		println(2)
	default:
		println(9)
	}
}

func Str_sw3_demo(x string) {
	switch x {
	case "a":
		println(1)
	case "b":
		println(2)
	case "c":
		println(3)
	default:
		println(9)
	}
}

func Bytes_demo() {
	b := []byte("Hi")
	println(string(b))
}

func Rune_demo() {
	rs := []rune("Go")
	println(string(rs))
}

func Rune_to_str_demo() {
	println(string(rune(65)))
}

func Str_range_demo() {
	for i, r := range string(rune(72)) + (string(rune(8364)) + string(rune(33))) {
		println(i, r)
	}
}

func Defer_loop_demo() {
	i := int(0)
	var iv int
	for {
		iv = i
		if iv < 3 {
			defer func(iv int) {
				println(iv)
			}(iv)
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Defer_demo() {
	defer func() {
		println(1)
	}()
	defer func() {
		println(2)
	}()
	println(3)
}

func Mut_demo() {
	r := int(10)
	a := r
	r = Add(a, 5)
	b := r
	println(b)
}

func Ptr_demo() {
	p := func(_v int64) *int64 { return &_v }(int64(10))
	a := *p
	println(a)
	*p = int64(99)
	b := *p
	println(b)
}

func New_demo() {
	p := new(int64)
	v := *p
	println(v)
}

func Ptr_safe_demo() {
	p := func(_v int64) *int64 { return &_v }(int64(42))
	var v int64
	ok := p != nil
	if ok {
		v = *p
	}
	println(v, ok)
	var v2 int64
	ok2 := ((*int64)(nil)) != nil
	if ok2 {
		v2 = *((*int64)(nil))
	}
	println(v2, ok2)
}

func Ptr_chan_demo() {
	p := func(_v int64) *int64 { return &_v }(int64(7))
	ch := make(chan *int64, 1)
	ch <- p
	q := <-ch
	v := *q
	println(v)
}

type Inbox struct {
	Ib_ch   chan int64
	Ib_name string
}

func Inbox_demo() {
	ch := make(chan int64, 1)
	box := Inbox{Ib_ch: ch, Ib_name: "fido"}
	box.Ib_ch <- 42
	v, _ := <-box.Ib_ch
	println(box.Ib_name, v)
}

type Hub struct {
	Hub_chans []chan int64
	Hub_id    int64
}

func Hub_demo() {
	ch0 := make(chan int64, 1)
	ch1 := make(chan int64, 1)
	hub := Hub{Hub_chans: []chan int64{ch0, ch1}, Hub_id: 7}
	c := hub.Hub_chans[1]
	c <- 99
	v, _ := <-c
	println(hub.Hub_id, v)
}

func Hub_worker_demo() {
	ch := make(chan int64)
	box := Inbox{Ib_ch: ch, Ib_name: "worker"}
	go func() {
		box.Ib_ch <- 123
	}()
	v := <-box.Ib_ch
	println(box.Ib_name, v)
}

func Chan_of_chan_demo() {
	reqs := make(chan chan int64, 1)
	reply := make(chan int64, 1)
	go func() {
		r := <-reqs
		r <- 77
	}()
	reqs <- reply
	v, _ := <-reply
	println(v)
}

type Pool struct {
	Pool_chans []chan int64
	Pool_base  int64
}

func Pool_demo() {
	c0 := make(chan int64, 1)
	c1 := make(chan int64, 1)
	go func() {
		c0 <- 5
	}()
	go func() {
		c1 <- 7
	}()
	pool := Pool{Pool_chans: []chan int64{c0, c1}, Pool_base: 10}
	ch0 := pool.Pool_chans[0]
	ch1 := pool.Pool_chans[1]
	v0 := <-ch0
	v1 := <-ch1
	println(func(x int64, y int64) int64 { return x + y }(pool.Pool_base, v0+v1))
}

func Linked_list_demo() {
	p3 := func(_v ListNode) *ListNode { return &_v }(ListNode{Ln_val: 3, Ln_next: nil})
	p2 := func(_v ListNode) *ListNode { return &_v }(ListNode{Ln_val: 2, Ln_next: p3})
	p1 := func(_v ListNode) *ListNode { return &_v }(ListNode{Ln_val: 1, Ln_next: p2})
	n1 := *p1
	n2 := *(n1.Ln_next)
	n3 := *(n2.Ln_next)
	println(n1.Ln_val, n2.Ln_val, n3.Ln_val)
}

func Chanbox_demo() {
	c := make(chan ChanBox)
	go func() {
		c <- ChanBox{Cb_id: 42, Cb_chan: c}
	}()
	v := <-c
	println(v.Cb_id)
}

type Cursed struct {
	Cu_chans []chan ChanBox
	Cu_list  *ListNode
}

func Cursed_demo() {
	c0 := make(chan ChanBox)
	c1 := make(chan ChanBox)
	t3 := func(_v ListNode) *ListNode { return &_v }(ListNode{Ln_val: 3, Ln_next: nil})
	t2 := func(_v ListNode) *ListNode { return &_v }(ListNode{Ln_val: 2, Ln_next: t3})
	t1 := func(_v ListNode) *ListNode { return &_v }(ListNode{Ln_val: 1, Ln_next: t2})
	cu := Cursed{Cu_chans: []chan ChanBox{c0, c1}, Cu_list: t1}
	ch0 := cu.Cu_chans[0]
	ch1 := cu.Cu_chans[1]
	go func() {
		ch0 <- ChanBox{Cb_id: 90, Cb_chan: ch0}
	}()
	go func() {
		ch1 <- ChanBox{Cb_id: 9, Cb_chan: ch1}
	}()
	v0 := <-ch0
	v1 := <-ch1
	n1 := *(cu.Cu_list)
	n2 := *(n1.Ln_next)
	n3 := *(n2.Ln_next)
	println(func(x int64, y int64) int64 { return x + y }(v0.Cb_id, v1.Cb_id), n1.Ln_val, n2.Ln_val, n3.Ln_val)
}

func Slice_alias_demo() {
	s := make([]int64, 3)
	s[0] = int64(10)
	s[1] = int64(20)
	(s[1:3])[0] = int64(99)
	v := s[1]
	println(v)
}

func Slice_append_demo() {
	s := make([]int64, 2)
	s[0] = int64(5)
	s2 := append(s, int64(9))
	v := s2[2]
	println(v)
}

func Slice_makecap_demo() {
	s := make([]int64, 1, 3)
	s[0] = int64(5)
	s2 := append(s, int64(8))
	s2[0] = int64(77)
	v := s[0]
	println(v)
}

func Slice_clear_demo() {
	s := make([]int64, 2)
	s[0] = int64(5)
	clear(s)
	v := s[0]
	println(v)
}

func Slice_copy_demo() {
	dst := make([]int64, 2)
	src := make([]int64, 2)
	src[0] = int64(7)
	copy(dst, src)
	v := dst[0]
	println(v)
}

func Count_demo() {
	i := int(0)
	var iv int
	for {
		iv = i
		if iv < 3 {
			println(iv)
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Cond_goto_demo(early bool) {
	println(1)
	if !early {
		println(2)
	}
	println(3)
	return
}

func Diamond_demo(b bool) {
	println(1)
	if b {
		println(10)
	} else {
		println(20)
	}
	println(99)
	return
}

func Loopif_demo() {
	i := int(0)
	var iv int
	for {
		iv = i
		if iv < 3 {
			iv = i
			if iv < 1 {
				println(100)
			}
			iv = i
			println(iv)
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Nested_loop_demo() {
	i := int(0)
	j := int(0)
	var jv int
	var iv int
	for {
		iv = i
		if iv < 2 {
			j = int(0)
			for {
				jv = j
				if jv < 2 {
					jv = j
					println(jv)
					j = Add(jv, 1)
				} else {
					break
				}
			}
			iv = i
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Early_return_demo() {
	i := int(0)
	var iv int
	for {
		iv = i
		if iv < 9 {
			iv = i
			if iv < 2 {
				iv = i
				println(iv)
				i = Add(iv, 1)
			} else {
				return
			}
		} else {
			break
		}
	}
	println(999)
	return
}

func Labeled_break_demo() {
	i := int(0)
	j := int(0)
	var jv int
	var iv int
L0:
	for {
		iv = i
		if iv < 3 {
			j = int(0)
			for {
				jv = j
				if jv < 3 {
					jv = j
					println(jv)
					if jv < 2 {
						jv = j
						j = Add(jv, 1)
					} else {
						break L0
					}
				} else {
					break
				}
			}
			iv = i
			i = Add(iv, 1)
		} else {
			break
		}
	}
	return
}

func Labeled_continue_demo() {
	i := int(0)
	j := int(0)
	var iv int
	var jv int
L0:
	for {
		iv = i
		i = Add(iv, 1)
		if iv < 2 {
			j = int(0)
			for {
				jv = j
				if jv < 3 {
					jv = j
					println(jv)
					j = Add(jv, 1)
					if !(jv < 1) {
						continue L0
					}
				} else {
					break
				}
			}
		} else {
			break
		}
	}
	return
}

func Irreducible_demo(enter_high bool) {
	n := int(0)
	var nv int
	if enter_high {
		goto block2
	} else {
		goto block1
	}
block1:
	nv = n
	println(1)
	n = Add(nv, 1)
	goto block2
block2:
	nv = n
	println(2)
	n = Add(nv, 1)
	if nv < 3 {
		goto block1
	} else {
		goto block3
	}
block3:
	return
}

func Foreach_demo() {
	xs := []int{10, 20, 30}
	for _, x := range xs {
		println(x)
	}
}

func Sum_print(xs ...int64) {
	for _, x := range xs {
		println(x)
	}
}

func Variadic_demo() {
	xs := []int64{7, 8, 9}
	Sum_print(xs...)
}

func Log_prefixed(prefix string, xs ...int64) {
	for _, x := range xs {
		println(prefix, x)
	}
}

func Variadic_mixed_demo() {
	xs := []int64{4, 5}
	Log_prefixed("n=", xs...)
}

func Variadic_lit_demo() {
	Sum_print(1, 2, 3)
}

func Foreach_idx_demo() {
	xs := []int64{10, 20, 30}
	for i, x := range xs {
		println(i, x)
	}
}

func Int_range_demo() {
	for i := range 4 {
		println(i)
	}
}

func Sum_demo() {
	xs := []int64{1, 2, 3, 4}
	total := int64(0)
	for _, x := range xs {
		total = total + x
	}
	println(total)
}

type Point struct {
	Px int64
	Py int64
}

func Point_demo() {
	p := Point{Px: 3, Py: 4}
	println(p.Px)
	println(p.Py)
	println(func(x int64, y int64) int64 { return x + y }(p.Px, p.Py))
}

type Labeled struct {
	Flag bool
	Qty  int64
}

func Labeled_demo() {
	r := Labeled{Flag: true, Qty: 5}
	println(r.Flag)
	println(r.Qty)
}

func (p Point) Sum_coords() int64 {
	return func(x int64, y int64) int64 { return x + y }(p.Px, p.Py)
}

func (p Point) Shifted(dx int64) Point {
	return Point{Px: p.Px + dx, Py: p.Py + dx}
}

func Method_demo() {
	p := Point{Px: 3, Py: 4}
	q := p.Shifted(10)
	println(p.Sum_coords())
	println(q.Px)
	println(q.Py)
	println(q.Sum_coords())
}

func Call_shift10(f func(int64) Point) Point {
	return f(10)
}

func Method_value_demo() {
	p := Point{Px: 1, Py: 2}
	q := Call_shift10(p.Shifted)
	println(q.Px, q.Py)
}

func Apply_pt(f func(Point) int64, p Point) int64 {
	return f(p)
}

func Method_expr_demo() {
	p := Point{Px: 5, Py: 6}
	println(Apply_pt(Point.Sum_coords, p))
}

func Swap2(a int64, b int64) (int64, int64) {
	return b, a
}

func Multiret_demo() {
	x, y := Swap2(3, 4)
	println(x, y)
}

func (p Point) Describe() {
	println(p.Px)
	println(p.Py)
}

func Io_method_demo() {
	p := Point{Px: 8, Py: 9}
	p.Describe()
}

func (p Point) Px_then_sum() int64 {
	println(p.Px)
	return func(x int64, y int64) int64 { return x + y }(p.Px, p.Py)
}

func Io_val_method_demo() {
	p := Point{Px: 8, Py: 9}
	s := p.Px_then_sum()
	println(s)
}

func (a Point) Point_eqb(b Point) bool {
	return Andb(a.Px == b.Px, a.Py == b.Py)
}

func Struct_eq_demo() {
	p := Point{Px: 3, Py: 4}
	q := Point{Px: 3, Py: 4}
	r := Point{Px: 3, Py: 5}
	println(p.Point_eqb(q), p.Point_eqb(r))
}

func Struct_eq_native_demo() {
	p := Point{Px: 3, Py: 4}
	q := Point{Px: 3, Py: 4}
	r := Point{Px: 3, Py: 5}
	println(p == q, p == r)
}

type Inner struct {
	Iv    int64
	Ikind int64
}

type Wrap struct {
	W_inner Inner
	Wz      int64
}

func Nested_struct_demo() {
	o := Wrap{W_inner: Inner{Iv: 5, Ikind: 1}, Wz: 9}
	println((o.W_inner).Iv, o.Wz)
}

type Cell struct {
	Cx int64
	Cy int64
}

func Sptr_demo() {
	p := &Cell{Cx: 3, Cy: 4}
	p.Cx = int64(7)
	a := p.Cx
	b := p.Cy
	println(a, b)
}

func (p *Cell) Cell_incx() {
	a := p.Cx
	p.Cx = a + 1
}

func Ptr_method_demo() {
	p := &Cell{Cx: 10, Cy: 20}
	p.Cell_incx()
	a := p.Cx
	println(a)
}

func Apply_cell(f func(*Cell), p *Cell) {
	f(p)
}

func Ptr_method_expr_demo() {
	p := &Cell{Cx: 5, Cy: 6}
	Apply_cell((*Cell).Cell_incx, p)
	a := p.Cx
	println(a)
}

type Node struct {
	*Cell
	Ntag int64
}

func Node_embed_demo() {
	p := &Cell{Cx: 10, Cy: 20}
	nd := Node{Cell: p, Ntag: 99}
	nd.Cell_incx()
	a := (nd.Cell).Cx
	println(a, nd.Ntag)
}

type Cell3 struct {
	C3x int64
	C3y int64
	C3z int64
}

func (p *Cell3) Cell3_inc_z() {
	z := p.C3z
	p.C3z = z + 1
}

func Nfield_ptr_demo() {
	p := &Cell3{C3x: 10, C3y: 20, C3z: 30}
	p.Cell3_inc_z()
	z := p.C3z
	println(z)
}

type Pair struct {
	P_n int64
	P_b bool
}

func (p *Pair) Pair_bump() {
	n := p.P_n
	p.P_n = n + 1
}

func Het_ptr_demo() {
	p := &Pair{P_n: 10, P_b: true}
	p.Pair_bump()
	n := p.P_n
	b := p.P_b
	println(n, b)
}

type Shape struct {
	Area  func(int64) int64
	Perim func(int64) int64
}

func Mk_rect(w int64, h int64) Shape {
	return Shape{Area: func(s int64) int64 {
		return func(x int64, y int64) int64 { return x + y }(w+h, w+h) + s
	}, Perim: func(s int64) int64 {
		return w + h + s
	}}
}

func Mk_square(side int64) Shape {
	return Shape{Area: func(s int64) int64 {
		return func(x int64, y int64) int64 { return x + y }(side+side, side+side) + s
	}, Perim: func(s int64) int64 {
		return side + side + s
	}}
}

func (sh Shape) Show_shape() {
	println(sh.Area(0))
	println(sh.Perim(1000))
}

func Iface_demo() {
	(Mk_rect(3, 4)).Show_shape()
	(Mk_square(5)).Show_shape()
}

type Greeter struct {
	Greet   func(int64) int64
	Gr_self any
}

func Mk_adder(base int64) Greeter {
	return Greeter{Greet: func(x int64) int64 {
		return base + x
	}, Gr_self: base}
}

func Single_iface_demo() {
	println((Mk_adder(5)).Greet(10))
}

type Stringer struct {
	Sg_str  func() string
	Sg_self any
}

func Mk_namer(nm string) Stringer {
	return Stringer{Sg_str: func() string {
		return nm
	}, Sg_self: nm}
}

func Nullary_iface_demo() {
	println((Mk_namer("fido")).Sg_str())
}

type Reader struct {
	Rd_read func(int64) int64
	Rd_self any
}

type Writer struct {
	Wr_write func(int64) int64
	Wr_self  any
}

type ReadWriter struct {
	Rw_read  func(int64) int64
	Rw_write func(int64) int64
	Rw_self  any
}

func Mk_file(base int64) ReadWriter {
	return ReadWriter{Rw_read: func(x int64) int64 {
		return x + base
	}, Rw_write: func(x int64) int64 {
		return x - base
	}, Rw_self: base}
}

func (rw ReadWriter) Rw_as_reader() Reader {
	return Reader{Rd_read: rw.Rw_read, Rd_self: rw.Rw_self}
}

func (rw ReadWriter) Rw_as_writer() Writer {
	return Writer{Wr_write: rw.Rw_write, Wr_self: rw.Rw_self}
}

func Embed_iface_demo() {
	f := Mk_file(10)
	println(f.Rw_read(3))
	println((f.Rw_as_reader()).Rd_read(5))
	println((f.Rw_as_writer()).Wr_write(40))
}

type LoggedGreeter struct {
	Greeter
	Lg_calls int64
}

func Mk_logged(base int64, calls int64) LoggedGreeter {
	return LoggedGreeter{Greeter: Mk_adder(base), Lg_calls: calls}
}

func Embed_iface_in_struct_demo() {
	lg := Mk_logged(100, 7)
	println(lg.Greet(5))
	println(lg.Lg_calls)
}

type Light struct {
	Ticks  int64
	Serial int64
}

var Fresh_light Light = Light{Ticks: 0, Serial: 7}

func (l Light) Go_green() Light {
	return Light{Ticks: func(x int64, y int64) int64 { return x + y }(l.Ticks, 1), Serial: l.Serial}
}

func (l Light) Go_red() Light {
	return Light{Ticks: l.Ticks, Serial: l.Serial}
}

func Typestate_demo() {
	l0 := Fresh_light
	l1 := l0.Go_green()
	l2 := l1.Go_red()
	println(l2.Ticks)
	println(l2.Serial)
}

type Sorted2 struct {
	S_a int64
	S_b int64
}

func (p Sorted2) Min_of() int64 {
	return p.S_a
}

func (p Sorted2) Max_of() int64 {
	return p.S_b
}

var Demo_pair Sorted2 = Sorted2{S_a: 3, S_b: 7}

func Repinv_demo() {
	println(Demo_pair.Min_of())
	println(Demo_pair.Max_of())
}

type MyI64 int64

func Mk_myi64(v int64) MyI64 {
	return MyI64(v)
}

func (m MyI64) Myi64_double() MyI64 {
	return Mk_myi64(func(x int64, y int64) int64 { return x + y }(int64(m), int64(m)))
}

func Deftype_demo() {
	println(int64((Mk_myi64(21)).Myi64_double()))
}

type Greeting string

func Mk_greeting(s string) Greeting {
	return Greeting(s)
}

func (g Greeting) Greeting_with(who string) string {
	return string(g) + who
}

func Deftype_str_demo() {
	println((Mk_greeting("Hi, ")).Greeting_with("fido"))
}

type Celsius int64

func Mk_celsius(v int64) Celsius {
	return Celsius(v)
}

func (c Celsius) Reading() int64 {
	return func(x int64, y int64) int64 { return x + y }(int64(c), 100)
}

type Measurable struct {
	Measure   func() int64
	Meas_self any
}

func (c Celsius) Celsius_measurable() Measurable {
	return Measurable{Measure: func() int64 {
		return c.Reading()
	}, Meas_self: int64(c)}
}

func Deftype_iface_demo() {
	println(((Mk_celsius(20)).Celsius_measurable()).Measure())
}

type Handler func(int64) int64

func Mk_handler(f func(int64) int64) Handler {
	return Handler(f)
}

func (h Handler) Handler_run(x int64) int64 {
	return (func(int64) int64)(h)(x)
}

func Hinc(n int64) int64 {
	return n + 1
}

func Named_func_demo() {
	println((Mk_handler(Hinc)).Handler_run(41))
}

type IntList []int64

func Mk_intlist(s []int64) IntList {
	return IntList(s)
}

func (l IntList) Il_len() int {
	return len([]int64(l))
}

func Deftype_slice_demo() {
	println((Mk_intlist(make([]int64, 3))).Il_len())
}

type Animal struct {
	Species string
	Legs    int64
}

func (a Animal) Speak() string {
	return a.Species
}

type Dog struct {
	Animal
	Breed string
}

func Mk_dog(sp string, br string) Dog {
	return Dog{Animal: Animal{Species: sp, Legs: 4}, Breed: br}
}

func Embed_demo() {
	println((Mk_dog("canine", "lab")).Species)
	println((Mk_dog("canine", "lab")).Speak())
}

func Gid[T1 any](x T1) T1 {
	return x
}

func Glen[T1 any](xs []T1) int {
	return len(xs)
}

func Gfirst[T1 any, T2 any](x T1, y T2) T1 {
	return x
}

func Generics_demo() {
	println(Gid("go"))
	println(Glen(make([]int64, 3)))
	println(Glen(make([]string, 2)))
	println(Gfirst("first", true))
}

func Ceq_i64(a int64, b int64) bool {
	return Ceqb(a, b)
}

func Ceq_u64(a uint64, b uint64) bool {
	return Ceqb(a, b)
}

func Ceq_str(a string, b string) bool {
	return Ceqb(a, b)
}

func (a Point) Ceq_point(b Point) bool {
	return Ceqb(a, b)
}

func (a Celsius) Ceq_celsius(b Celsius) bool {
	return Ceqb(a, b)
}

func Comparable_demo() {
	println(Ceq_i64(5, 5), Ceq_u64(9, 9), Ceq_str("go", "hi"), Point{Px: 1, Py: 2}.Ceq_point(Point{Px: 1, Py: 2}), (Mk_celsius(20)).Ceq_celsius(Mk_celsius(20)))
}

type Box[T1 any] struct {
	Bval T1
	Btag int64
}

func Make_box[T1 any](v T1) Box[T1] {
	return Box[T1]{Bval: v, Btag: 1}
}

func (b Box[T1]) Box_get() T1 {
	return b.Bval
}

func (b Box[T1]) Box_tag() int64 {
	return b.Btag
}

func Gstruct_demo() {
	println((Make_box("hi")).Box_get())
	println((Make_box(true)).Box_get())
	println((Make_box("x")).Box_tag())
}

type Counts map[string]int64

func Mk_counts(m map[string]int64) Counts {
	return Counts(m)
}

func (c Counts) Co_size() int {
	return len(map[string]int64(c))
}

func (c Counts) Co_sum() int64 {
	a := int64(0)
	if _v, _ok := map[string]int64(c)["a"]; _ok {
		a = _v
	}
	b := int64(0)
	if _v, _ok := map[string]int64(c)["b"]; _ok {
		b = _v
	}
	return a + b
}

func Gmap_deftype_demo() {
	m := make(map[string]int64)
	m["a"] = 1
	m["b"] = 2
	n := (Mk_counts(m)).Co_size()
	println(n)
	s := (Mk_counts(m)).Co_sum()
	println(s)
}

func Countdown(n uint, v int64) {
	if n == 0 {
	} else {
		k := n - 1
		println(v)
		Countdown(k, v-1)
	}
}
func Recursion_demo() {
	Countdown(3, 3)
}

func Pow2(n uint) int64 {
	if n == 0 {
		return 1
	} else {
		k := n - 1
		return func(x int64, y int64) int64 { return x * y }(2, Pow2(k))
	}
}
func Pure_rec_demo() {
	println(Pow2(4))
}

func Is_even(n uint) bool {
	if n == 0 {
		return true
	} else {
		k := n - 1
		return Is_odd(k)
	}
}
func Is_odd(n uint) bool {
	if n == 0 {
		return false
	} else {
		k := n - 1
		return Is_even(k)
	}
}
func Mutual_rec_demo() {
	println(Is_even(4))
	println(Is_odd(4))
}

type Direction int

const (
	North Direction = iota
	South
	East
	West
)

func Dir_io(d Direction) {
	switch d {
	case North:
		println(0)
	case South:
		println(1)
	case East:
		println(2)
	case West:
		println(3)
	}
}

func Enum_demo() {
	Dir_io(East)
}

func Dir_name(d Direction) string {
	switch d {
	case North:
		return "N"
	case South:
		return "S"
	case East:
		return "E"
	default:
		return "W"
	}
}

func Enum_value_demo() {
	println(Dir_name(West))
}

func Dir_sign(d Direction) {
	switch d {
	case North:
		println(1)
	case South:
		println(0)
	case East:
		println(0)
	case West:
		println(0)
	}
}

func Enum_default_demo() {
	Dir_sign(North)
	Dir_sign(South)
}

func main() {
	println(func(x int64, y int64) int64 { return x + y }(1, 2))
	Panic_and_recover(func(x int64, y int64) int64 { return x + y }(40, 2))
	Div_demo()
	Overflow_safe_demo()
	I64_abs_demo()
	Neg_op_demo()
	Conv64_demo()
	Minmax64_demo()
	Cmp_ops_demo()
	Float_demo()
	Float_cmp_demo()
	Float_nan_demo(0.0)
	Float_opp_demo()
	Float_opp_sign_demo(0.0)
	Fminmax_demo()
	F64_of_int_demo()
	F64_of_i64_demo()
	Fcmp_demo()
	U8_demo()
	Fw_cmp_demo()
	I8_demo()
	U16_demo()
	Bitwise_demo()
	Shift_demo()
	Convert_demo()
	Divmod_demo()
	U32_demo()
	I64_demo()
	I64_ops_demo()
	Uconst_demo()
	U64_demo()
	I64_pipeline_demo()
	U64_pipeline_demo()
	Const_demo()
	Recv_unused_ok_demo()
	Builtins_demo()
	Prec_demo()
	Neglit_demo()
	Map_demo()
	Map_alias_demo()
	Slice_demo()
	Chan_demo()
	Select_demo()
	Select_default_demo()
	Goroutine_demo()
	Session_demo()
	Adder_demo()
	Control_flow_demo()
	Bool_op_demo(true, false, true)
	Cond_op_demo()
	Inline_if_demo()
	Lookup_demo()
	List_demo()
	Slice_safe_demo()
	Arr_demo()
	ArrN_demo()
	Arr_field_ret_demo()
	Arr_eq_demo()
	Arr_copy_demo()
	Assert_safe_demo(7)
	String_demo()
	Str_cmp_demo()
	Str_slice_demo()
	Bytes_demo()
	Rune_demo()
	Rune_to_str_demo()
	Str_range_demo()
	Tsw_demo(true)
	Tsw_demo("go")
	Tsw_demo(5)
	Tsw3_demo(true)
	Tsw3_demo("hi")
	Tsw3_demo(I64_abs(5))
	Tsw_or_demo(true)
	Tsw_or_demo("x")
	Tsw_or_demo(5)
	Tsw_or3_demo(true)
	Tsw_or3_demo("z")
	Tsw_or3_demo(5)
	Int_sw_demo(1)
	Int_sw_demo(2)
	Int_sw_demo(5)
	Int_sw3_demo(3)
	Int_sw3_demo(8)
	Str_sw_demo("a")
	Str_sw_demo("b")
	Str_sw_demo("z")
	Str_sw3_demo("c")
	Str_sw3_demo("z")
	Complex_demo()
	Complex_arith_demo()
	Complex_mul_demo()
	Complex_div_demo()
	Complex_neg_demo()
	Complex_const_runtime_demo()
	Complex_cmp_demo()
	Scmp_demo()
	Foreach_demo()
	Variadic_demo()
	Variadic_mixed_demo()
	Variadic_lit_demo()
	Foreach_idx_demo()
	Int_range_demo()
	Sum_demo()
	Cond_goto_demo(true)
	Cond_goto_demo(false)
	Diamond_demo(true)
	Diamond_demo(false)
	Loopif_demo()
	Nested_loop_demo()
	Early_return_demo()
	Labeled_break_demo()
	Labeled_continue_demo()
	Irreducible_demo(false)
	Irreducible_demo(true)
	Mut_demo()
	Ptr_demo()
	New_demo()
	Ptr_safe_demo()
	Ptr_chan_demo()
	Inbox_demo()
	Hub_demo()
	Hub_worker_demo()
	Chan_of_chan_demo()
	Pool_demo()
	Linked_list_demo()
	Chanbox_demo()
	Cursed_demo()
	Slice_alias_demo()
	Slice_append_demo()
	Slice_makecap_demo()
	Slice_clear_demo()
	Slice_copy_demo()
	Count_demo()
	Defer_demo()
	Defer_loop_demo()
	Point_demo()
	Labeled_demo()
	Method_demo()
	Method_value_demo()
	Method_expr_demo()
	Multiret_demo()
	Io_method_demo()
	Io_val_method_demo()
	Struct_eq_demo()
	Struct_eq_native_demo()
	Nested_struct_demo()
	Sptr_demo()
	Ptr_method_demo()
	Ptr_method_expr_demo()
	Node_embed_demo()
	Nfield_ptr_demo()
	Het_ptr_demo()
	Iface_demo()
	Single_iface_demo()
	Nullary_iface_demo()
	Embed_iface_demo()
	Embed_iface_in_struct_demo()
	Typestate_demo()
	Repinv_demo()
	Deftype_demo()
	Deftype_str_demo()
	Deftype_iface_demo()
	Named_func_demo()
	Deftype_slice_demo()
	Embed_demo()
	Generics_demo()
	Comparable_demo()
	Gstruct_demo()
	Gmap_deftype_demo()
	Recursion_demo()
	Pure_rec_demo()
	Mutual_rec_demo()
	F32_demo()
	I64_of_narrow_demo()
	I64_to_narrow_demo()
	Narrow_let_assert_demo()
	Narrow_ret_demo()
	Narrow_u64_demo()
	Floatconv_demo()
	Fconst_demo()
	F32_cmp_demo()
	F32_extra_demo()
	F32_conv_demo()
	Narrow_f32_demo()
	F32_const_runtime_demo()
	F32_of_int_demo()
	F32_fconst_demo()
	F64_fconst_big_demo()
	I64_of_f64_demo()
	U64conv_demo()
	Enum_demo()
	Enum_value_demo()
	Enum_default_demo()
}
