(** Rocq → Go extraction backend.
    MiniML printer for extracted Go packages.

    Type map:
      nat  → uint
      bool → bool

    Nat and bool operations are inlined as Go operators/literals.
    All other globals become exported Go identifiers. *)

open Pp
open Names
open Miniml
open Mlutil
open Modutil
open Table
open Common

(*s Keywords that may not be used as Go identifiers. *)

let keywords =
  let kws = [
    "break"; "case"; "chan"; "const"; "continue"; "default"; "defer";
    "else"; "fallthrough"; "for"; "func"; "go"; "goto"; "if"; "import";
    "interface"; "map"; "package"; "range"; "return"; "select"; "struct";
    "switch"; "type"; "var";
    (* predeclared identifiers *)
    "any"; "bool"; "byte"; "comparable"; "complex64"; "complex128";
    "error"; "float32"; "float64"; "int"; "int8"; "int16"; "int32";
    "int64"; "rune"; "string"; "uint"; "uint8"; "uint16"; "uint32";
    "uint64"; "uintptr"; "true"; "false"; "iota"; "nil";
    "append"; "cap"; "clear"; "close"; "complex"; "copy"; "delete";
    "imag"; "len"; "make"; "max"; "min"; "new"; "panic"; "print";
    "println"; "real"; "recover";
  ] in
  List.fold_left (fun s w -> Id.Set.add (Id.of_string w) s) Id.Set.empty kws

(*s File naming. *)

let file_naming state mp =
  file_of_modfile (State.get_table state) mp

(*s Preamble emitted at the top of every extracted .go file. *)

let preamble_for_pkg pkg _state _name _comment _used_modules _safe =
  str "// Code generated by rocq-go-extraction; DO NOT EDIT." ++ fnl () ++
  fnl () ++
  str ("package " ^ pkg) ++ fnl () ++ fnl ()

let preamble = preamble_for_pkg "fido"

let sig_preamble _state _name _comment _used_modules _safe = mt ()

let pp_sig _state _sig = mt ()

(*s Identifier utilities. *)

(** Sanitise a Rocq id for Go: replace prime ['] with underscore. *)
let go_safe s = String.map (function '\'' -> '_' | c -> c) s

let pp_goid id = str (go_safe (Id.to_string id))

(** Capitalise the first character (export in Go). *)
let go_export s =
  if String.length s = 0 then s
  else
    let b = Bytes.of_string s in
    Bytes.set b 0 (Char.uppercase_ascii (Bytes.get b 0));
    Bytes.to_string b

(*s Global-reference helpers. *)

let global_path r =
  try
    DirPath.to_string (Nametab.dirpath_of_global r.glob) ^ "." ^
    Id.to_string (Nametab.basename_of_global r.glob)
  with Not_found -> ""

let global_basename r =
  try Id.to_string (Nametab.basename_of_global r.glob)
  with Not_found -> ""

(* A Fido builtin/combinator is matched by its (unqualified) basename — safe
   because those names are reserved by builtins.v and user theories should not
   shadow them.  Stdlib refs are package-qualified and use [ref_has_suffix]. *)
let named n r = String.equal (global_basename r) n

let ref_has_suffix r suffix =
  let p = global_path r in
  let n = String.length p and m = String.length suffix in
  n >= m && String.equal suffix (String.sub p (n - m) m)

(*s Standard-library type and constructor recognition. *)

let is_unit_type   r = ref_has_suffix r ".Init.Datatypes.unit"
let is_nat_type    r = ref_has_suffix r ".Init.Datatypes.nat"
let is_uint63_type r =
  ref_has_suffix r ".PrimInt63.int" ||
  ref_has_suffix r ".Cyclic.Int63.PrimInt63.int"
let is_nat_zero r  = ref_has_suffix r ".Init.Datatypes.O"
let is_nat_succ r  = ref_has_suffix r ".Init.Datatypes.S"
let is_bool_type r = ref_has_suffix r ".Init.Datatypes.bool"
let is_bool_true r = ref_has_suffix r ".Init.Datatypes.true"
let is_bool_false r = ref_has_suffix r ".Init.Datatypes.false"
let is_unit_tt r   = ref_has_suffix r ".Init.Datatypes.tt"
let is_list_type r =
  ref_has_suffix r ".Init.Datatypes.list"
let is_list_nil r  =
  ref_has_suffix r ".Init.Datatypes.nil" ||
  String.equal (global_basename r) "nil"
let is_list_cons r =
  ref_has_suffix r ".Init.Datatypes.cons" ||
  String.equal (global_basename r) "cons"

(*s println / GoAny model recognition. *)

(* Basename matching is safe here because Go builtin names are unqualified
   and no user theory should shadow them.  All other Go stdlib calls are
   package-qualified (e.g. fmt.Println) and will never match these. *)
let is_print_ref r   = String.equal (global_basename r) "print"
(* Table of axiom type names → Go type keywords.
   Basename matching is safe: these names are reserved by builtins.v and
   no user theory should shadow them. *)
let go_prim_type_table = [
  "GoInt",     "int";
  "GoInt8",    "int8";
  "GoInt16",   "int16";
  "GoInt32",   "int32";
  "GoUint",    "uint";
  "GoUint8",   "uint8";
  "GoUint16",  "uint16";
  "GoUint32",  "uint32";
  "GoUint64",  "uint64";
  "GoFloat32", "float32";
]

let is_float64_type r =
  ref_has_suffix r ".PrimFloat.float" ||
  String.equal (global_basename r) "float"

let classify_go_prim_type r =
  List.assoc_opt (global_basename r) go_prim_type_table

let is_go_prim_type r = Option.has_some (classify_go_prim_type r)

let is_println_ref = named "println"
let is_len_ref    r  = String.equal (global_basename r) "len"
let is_cap_ref    r  = String.equal (global_basename r) "cap"
let is_append_ref r  = String.equal (global_basename r) "append"
let is_go_map_type = named "GoMap"
let is_slice_of_list_ref = named "slice_of_list"
let is_slice_get_ref = named "slice_get"
let is_slice_at_ok_ref = named "slice_at_ok"
let is_for_each_ref = named "for_each"
let is_slice_fold_ref = named "slice_fold"
let is_ref_type = named "Ref"
let is_ref_new_ref = named "ref_new"
let is_ref_get_ref = named "ref_get"
let is_ref_set_ref = named "ref_set"
let is_run_blocks_ref = named "run_blocks"
let is_jump_ctor = named "Jump"
let is_done_ctor = named "Done"
let is_map_make_ref = named "map_make"
let is_map_make_typed_ref = named "map_make_typed"
let is_map_set_ref = named "map_set"
let is_map_del_ref = named "map_delete"
let is_map_len_ref = named "map_len"
let is_map_get_or_ref = named "map_get_or"
let is_map_get_opt_ref = named "map_get_opt"
(* option Some/None — used to lower [match map_get_opt … with Some v | None]. *)
let is_some_ctor r =
  ref_has_suffix r ".Init.Datatypes.Some" || String.equal (global_basename r) "Some"
let is_none_ctor r =
  ref_has_suffix r ".Init.Datatypes.None" || String.equal (global_basename r) "None"
let is_panic_ref = named "panic"
let is_type_assert_ref = named "type_assert"
let is_type_assert_safe_ref = named "type_assert_safe"
let is_go_chan_type = named "GoChan"
let is_make_chan_ref = named "make_chan"
let is_make_chan_buf_ref = named "make_chan_buf"
let is_send_ref = named "send"
let is_recv_ref = named "recv"
let is_close_chan_ref = named "close_chan"
let is_recv_ok_ref = named "recv_ok"
let is_go_spawn_ref = named "go_spawn"
let is_defer_call_ref = named "defer_call"
let is_proto_type r =
  String.equal (global_basename r) "Proto"
let is_proto_ctor r =
  String.equal (global_basename r) "PSend" ||
  String.equal (global_basename r) "PRecv" ||
  String.equal (global_basename r) "PEnd"
let is_dual_ref = named "dual"
let is_sess_endpoint_ref = named "SessEndpoint"
let is_make_sess_ref = named "make_sess"
let is_sess_send_ref = named "sess_send"
let is_sess_recv_ref = named "sess_recv"
let is_sess_close_ref = named "sess_close"

(* GoTypeTag constructors → Go type names *)
let go_type_tag_map = [
  "TBool",    "bool";
  "TInt64",   "int64";
  "TFloat64", "float64";
  "TString",  "string";
  "TAny",     "any";
  "TInt",     "int";
  "TInt8",    "int8";
  "TInt16",   "int16";
  "TInt32",   "int32";
  "TUint",    "uint";
  "TUint8",   "uint8";
  "TUint16",  "uint16";
  "TUint32",  "uint32";
  "TUint64",  "uint64";
  "TFloat32", "float32";
]

(** Primitive tag lookup — basename only, no recursion. *)
let classify_go_type_tag r =
  List.assoc_opt (global_basename r) go_type_tag_map

(** Recursive tag → Go type string.  Handles composite tags (TChan, TSlice, TMap)
    by recursing into their argument tags. *)
let rec go_type_of_tag = function
  | MLcons (_, r, []) ->
      (match List.assoc_opt (global_basename r) go_type_tag_map with
       | Some t -> t
       | None   -> "any")
  | MLcons (_, r, [inner]) when String.equal (global_basename r) "TChan"  ->
      "chan " ^ go_type_of_tag inner
  | MLcons (_, r, [inner]) when String.equal (global_basename r) "TSlice" ->
      "[]" ^ go_type_of_tag inner
  | MLcons (_, r, [kt; vt]) when String.equal (global_basename r) "TMap"  ->
      "map[" ^ go_type_of_tag kt ^ "]" ^ go_type_of_tag vt
  | _ -> "any"

(** Zero value for a Go type given its tag. *)
let zero_of_tag tag =
  match tag with
  | MLcons (_, r, []) when String.equal (global_basename r) "TBool"   -> "false"
  | MLcons (_, r, []) when String.equal (global_basename r) "TString" -> "\"\""
  | MLcons (_, r, []) when String.equal (global_basename r) "TAny"    -> "nil"
  | MLcons (_, r, [_])    when String.equal (global_basename r) "TChan"  -> "nil"
  | MLcons (_, r, [_])    when String.equal (global_basename r) "TSlice" -> "nil"
  | MLcons (_, r, [_; _]) when String.equal (global_basename r) "TMap"   -> "nil"
  | t -> go_type_of_tag t ^ "(0)"

let is_zero_val_ref = named "zero_val"

let is_go_type_tag_ctor r =
  Option.has_some (classify_go_type_tag r) ||
  String.equal (global_basename r) "TChan"  ||
  String.equal (global_basename r) "TSlice" ||
  String.equal (global_basename r) "TMap"

(* IO monad — basename matching is acceptable here because these names
   live in builtins.v and user theories should not shadow them. *)
let is_IO_type  r = String.equal (global_basename r) "IO"
let is_ret_ref = named "ret"
let is_bind_ref = named "bind"

(* existT is the constructor of sigT — used by the [any] notation. *)
let is_existT_ref r =
  ref_has_suffix r ".Init.Specif.existT" ||
  String.equal (global_basename r) "existT"

(* sigT / GoAny — map to Go's [any] type. *)
let is_sigT_ref r =
  ref_has_suffix r ".Init.Specif.sigT" ||
  String.equal (global_basename r) "sigT"

(*s Nat arithmetic operation recognition. *)

type nat_op = NatAdd | NatSub | NatMul | NatDiv | NatMod
            | NatEqb | NatLtb | NatLeb

let nat_op_names = [
  "add",     NatAdd;
  "sub",     NatSub;
  "mul",     NatMul;
  (* Integer div / mod are deliberately omitted: Go panics on division by zero,
     but Rocq's Uint63 / nat division is total (x / 0 = 0, x mod 0 = x), so
     emitting a raw `/` or `%` would be silently unsound.  Forbidden until a
     guarded form (proof d <> 0, or a checked form) exists.  Any use now
     extracts to an undefined identifier rather than wrong Go.  (Float `/` is
     handled separately and kept — IEEE, no panic.) *)
  "eqb",     NatEqb;
  "ltb",     NatLtb;
  "leb",     NatLeb;
]

let is_nat_op_ref r name =
  ref_has_suffix r (".Init.Nat." ^ name) ||
  ref_has_suffix r (".Arith.PeanoNat.Nat." ^ name)

let is_int63_op_ref r name =
  ref_has_suffix r (".PrimInt63." ^ name) ||
  ref_has_suffix r (".Cyclic.Int63.PrimInt63." ^ name)

let float_op_table = [
  "add", " + "; "sub", " - "; "mul", " * "; "div", " / ";
]

let is_float_op_ref r name =
  ref_has_suffix r (".PrimFloat." ^ name)

let classify_float_op r =
  List.find_map
    (fun (name, op) -> if is_float_op_ref r name then Some op else None)
    float_op_table

let classify_nat_op r =
  List.find_map
    (fun (name, op) -> if is_nat_op_ref r name then Some op else None)
    nat_op_names

let classify_int63_op r =
  List.find_map
    (fun (name, op) -> if is_int63_op_ref r name then Some op else None)
    nat_op_names  (* same infix table works for int63 *)

(* Signed comparison.  [int] is modelled with signed semantics to match Go's
   [int64]; comparison/division are where signed and unsigned differ (the raw
   +/-/* ops are shared).  The signed primitives [ltsb]/[lesb] live in
   [PrimInt63] (same module as add/sub/mul); Go's [<]/[<=] are type-directed
   (signed on int64), so emitting them is faithful. *)
let sint63_cmp_names = [ "ltsb", NatLtb; "lesb", NatLeb ]
let classify_sint63_op r =
  List.find_map
    (fun (name, op) -> if is_int63_op_ref r name then Some op else None)
    sint63_cmp_names

let go_infix = function
  | NatAdd -> " + " | NatSub -> " - " | NatMul -> " * "
  | NatDiv -> " / " | NatMod -> " % "
  | NatEqb -> " == " | NatLtb -> " < " | NatLeb -> " <= "

(*s Type printer. *)

let rec pp_type state = function
  | Tarr (t1, t2) ->
      str "func(" ++ pp_type state t1 ++ str ") " ++ pp_type state t2
  | Tglob (r, _)  when is_sigT_ref r -> str "any"
  (* IO A erases to A — the world token has no runtime representation *)
  | Tglob (r, [arg]) when is_IO_type r -> pp_type state arg
  (* SessEndpoint P → chan any (both endpoints share one chan any; proto is proof-only) *)
  | Tglob (r, _) when is_sess_endpoint_ref r -> str "chan any"
  (* Ref A → T (a mutable local cell is just a Go variable of type T) *)
  | Tglob (r, [arg]) when is_ref_type r -> pp_type state arg
  (* GoChan A → chan T *)
  | Tglob (r, [arg]) when is_go_chan_type r ->
      str "chan " ++ pp_type state arg
  (* GoMap K V → map[KT]VT *)
  | Tglob (r, [kt; vt]) when is_go_map_type r ->
      str "map[" ++ pp_type state kt ++ str "]" ++ pp_type state vt
  (* list GoRune = GoString — must come before the general slice case *)
  | Tglob (r, [Tglob (elem, [])]) when is_list_type r
    && String.equal (global_basename elem) "GoInt32" -> str "string"
  (* list A = GoSlice A → []T *)
  | Tglob (r, [arg]) when is_list_type r ->
      str "[]" ++ pp_type state arg
  | Tglob (r, []) when is_float64_type r  -> str "float64"
  | Tglob (r, []) when is_go_prim_type r -> str (Option.get (classify_go_prim_type r))
  | Tglob (r, []) when is_unit_type r   -> str "struct{}"
  | Tglob (r, []) when is_uint63_type r -> str "int64"
  | Tglob (r, []) when is_nat_type r    -> str "uint"
  | Tglob (r, []) when is_bool_type r   -> str "bool"
  | Tglob (r, args) ->
      str (go_export (global_basename r)) ++
      (if args = [] then mt ()
       else
         str "[" ++
         prlist_with_sep (fun () -> str ", ") (pp_type state) args ++
         str "]")
  | Tvar i | Tvar' i -> str ("T" ^ string_of_int i)
  | Tdummy _ | Tunknown | Taxiom | Tmeta _ -> str "any"

let rec collect_tarrs = function
  | Tarr (t, rest) -> let ts, ret = collect_tarrs rest in t :: ts, ret
  | t              -> [], t

let is_erased = function MLdummy _ -> true | _ -> false

(*s De Bruijn environment.

    [env] is the list of bound [ml_ident]s, innermost binder first.
    [MLrel 1] is the innermost (most-recently-bound) variable.

    In Rocq 9.x, [ml_ident] is a variant: [Dummy | Id of variable | Tmp of variable]. *)

let is_dummy = function Dummy -> true | _ -> false

let pp_mlident = function
  | Dummy   -> str "_"
  | Id v    -> str (go_safe (Id.to_string v))
  | Tmp v   -> str (go_safe (Id.to_string v))

let pp_rel env i =
  try pp_mlident (List.nth env (i - 1))
  with Not_found -> str ("_db" ^ string_of_int i)

(*s Collect nested lambdas into a flat parameter list. *)

let collect_lam body =
  let rec go acc = function
    | MLlam (id, body) -> go (id :: acc) body
    | body             -> List.rev acc, body
  in
  go [] body

(*s Flatten nested applications. *)

let collect_app head args =
  let rec go acc = function
    | MLapp (h, more) -> go (more @ acc) h
    | h               -> h, acc
  in
  go args head

(*s Peel [MLmagic] coercions (inserted by extraction around casts) to reach
    the underlying node — needed to recognise [MLcase] under a coercion. *)
let rec strip_magic = function
  | MLmagic e -> strip_magic e
  | e         -> e

(*s Unfold a Rocq list literal (MLcons-based) to an OCaml list, or None. *)

let rec unfold_list acc = function
  | MLcons (_, r, [x; rest]) when is_list_cons r -> unfold_list (x :: acc) rest
  | MLcons (_, r, [])        when is_list_nil r  -> Some (List.rev acc)
  | _ -> None


(*s Fold a Peano nat literal to an integer, or return None. *)

let rec nat_value = function
  | MLcons (_, r, [])  when is_nat_zero r -> Some 0
  | MLcons (_, r, [n]) when is_nat_succ r ->
      (match nat_value n with Some v -> Some (v + 1) | None -> None)
  | _ -> None

(*s Expression printer. *)

(*s Check whether MLrel 1 appears free in an expression.
    Used to detect unused bind parameters (the result is discarded). *)

let rec db1_free = function
  | MLrel 1             -> false
  | MLrel _ | MLglob _ | MLuint _ | MLfloat _ | MLdummy _ | MLaxiom _ | MLexn _ -> true
  | MLapp (h, args)     -> db1_free h && List.for_all db1_free args
  | MLlam (_, b)        -> db1_free b   (* conservative: may over-suppress inside nested lam *)
  | MLcons (_, _, args) -> List.for_all db1_free args
  | MLletin (_, e1, e2) -> db1_free e1 && db1_free e2
  | MLmagic e           -> db1_free e
  | _                   -> true

(*s CFG block terminators ([Next] values).  A block emitter delegates its
    terminator to one of these, so the same emitter prints raw labels+goto or
    structured continue/break depending on context. *)

let raw_term tab next =
  match next with
  | MLcons (_, c, [n]) when is_jump_ctor c ->
      let lbl = match nat_value n with Some v -> v | None -> 0 in
      str tab ++ str (Printf.sprintf "goto block%d" lbl) ++ fnl ()
  | MLcons (_, c, []) when is_done_ctor c -> str tab ++ str "return" ++ fnl ()
  | _ -> str tab ++ str "return" ++ fnl ()

(* Inside a structured [for] for loop-header [header] with exit block [exit]:
   a jump back to the header is the implicit loop-around (emit nothing); a jump
   to the exit is [break]; anything else falls back to a raw [goto]. *)
let loop_term header exit tab next =
  match next with
  | MLcons (_, c, [n]) when is_jump_ctor c ->
      (match nat_value n with
       | Some l when l = header -> mt ()
       | Some l when l = exit   -> str tab ++ str "break" ++ fnl ()
       | _ -> raw_term tab next)
  | _ -> raw_term tab next

let rec pp_expr state env = function
  | MLrel i ->
      pp_rel env i

  | MLapp (head, args) ->
      let head, all_args = collect_app head args in
      let vis = List.filter (fun a -> not (is_erased a)) all_args in
      (match head, vis with
       (* ret x → x (identity: IO wrapper erases) *)
       | MLglob r, [x] when is_ret_ref r -> pp_expr state env x

       (* type_assert tag v → v.(T) where T is read from the tag constructor *)
       | MLglob r, [tag; v] when is_type_assert_ref r ->
           let go_type = go_type_of_tag tag in
           let inner =
             match v with
             | MLcons (_, r2, [x])    when is_existT_ref r2 -> pp_expr state env x
             | MLcons (_, r2, [_; x]) when is_existT_ref r2 -> pp_expr state env x
             | _ -> pp_expr state env v
           in
           inner ++ str ".(" ++ str go_type ++ str ")"

       (* panic(val) *)
       | MLglob r, [x] when is_panic_ref r ->
           let pp_pa e =
             match e with
             | MLcons (_, r2, [v])    when is_existT_ref r2 -> pp_expr state env v
             | MLcons (_, r2, [_; v]) when is_existT_ref r2 -> pp_expr state env v
             | _ -> pp_expr state env e
           in
           str "panic(" ++ pp_pa x ++ str ")"

       (* slice_of_list tag list → []T{v1, v2, ...} *)
       | MLglob r, [tag; lst] when is_slice_of_list_ref r ->
           let go_elem = go_type_of_tag tag in
           (match unfold_list [] lst with
            | Some elems ->
                str ("[]" ^ go_elem ^ "{") ++
                prlist_with_sep (fun () -> str ", ") (pp_expr state env) elems ++
                str "}"
            | None -> str ("[]" ^ go_elem ^ "(nil)"))

       (* slice_get tag xs i → xs[i] — panics if out of bounds *)
       | MLglob r, [_tag; xs; i] when is_slice_get_ref r ->
           pp_expr state env xs ++ str "[" ++ pp_expr state env i ++ str "]"

       (* mutable cells: ref_new v → init value (bound as the Go var by the
          enclosing bind); ref_get r → read the var; ref_set r v → r = v.
          int/float literals are typed so the inferred Go var is int64/float64. *)
       | MLglob r, [v] when is_ref_new_ref r -> pp_typed_lit state env v
       | MLglob r, [_tag; rf] when is_ref_get_ref r -> pp_expr state env rf
       | MLglob r, [rf; v] when is_ref_set_ref r ->
           pp_expr state env rf ++ str " = " ++ pp_typed_lit state env v

       (* make_chan tag → make(chan T) *)
       | MLglob r, [tag] when is_make_chan_ref r ->
           str ("make(chan " ^ go_type_of_tag tag ^ ")")

       (* make_chan_buf tag n → make(chan T, n) *)
       | MLglob r, [tag; n] when is_make_chan_buf_ref r ->
           str ("make(chan " ^ go_type_of_tag tag ^ ", ") ++ pp_expr state env n ++ str ")"

       (* send ch v → ch <- v *)
       | MLglob r, [ch; v] when is_send_ref r ->
           pp_expr state env ch ++ str " <- " ++ pp_expr state env v

       (* recv tag ch → <-ch *)
       | MLglob r, [_tag; ch] when is_recv_ref r ->
           str "<-" ++ pp_expr state env ch

       (* close_chan ch → close(ch) *)
       | MLglob r, [ch] when is_close_chan_ref r ->
           str "close(" ++ pp_expr state env ch ++ str ")"

       (* recv_ok in expression context — handled properly by pp_stmts;
          this fallback covers the rare case of expression-position use. *)
       | MLglob r, [_tag; ch; _kont] when is_recv_ok_ref r ->
           str "<-" ++ pp_expr state env ch

       (* zero_val tag → false / "" / nil / T(0) *)
       | MLglob r, [tag] when is_zero_val_ref r ->
           str (zero_of_tag tag)

       (* map_make_typed kt vt → make(map[K]V) with concrete types from tags *)
       | MLglob r, [kt; vt] when is_map_make_typed_ref r ->
           str ("make(map[" ^ go_type_of_tag kt ^ "]" ^ go_type_of_tag vt ^ ")")

       (* map_get_or: handled in pp_stmts/MLletin for clean two-statement emission *)

       (* map operations *)
       | MLglob r, [k; v; m] when is_map_set_ref r ->
           pp_expr state env m ++ str "[" ++ pp_expr state env k ++ str "] = " ++
           pp_expr state env v
       | MLglob r, [k; m]    when is_map_del_ref r ->
           str "delete(" ++ pp_expr state env m ++ str ", " ++ pp_expr state env k ++ str ")"
       | MLglob r, [m]       when is_map_len_ref r ->
           str "len(" ++ pp_expr state env m ++ str ")"
       | MLglob r, []        when is_map_make_ref r ->
           str "make(map[any]any)" (* type params erased; real type comes from context *)

       (* len(slice) / cap(slice) *)
       | MLglob r, [s] when is_len_ref r ->
           str "len(" ++ pp_expr state env s ++ str ")"
       | MLglob r, [s] when is_cap_ref r ->
           str "cap(" ++ pp_expr state env s ++ str ")"
       (* append(xs, ys) *)
       | MLglob r, [xs; ys] when is_append_ref r ->
           str "append(" ++ pp_expr state env xs ++ str ", " ++
           pp_expr state env ys ++ str "...)"

       (* print/println(list GoAny) — unfold list, strip existT wrappers *)
       | MLglob r, [lst] when is_print_ref r || is_println_ref r ->
           let fname = global_basename r in
           let pp_pa e =
             match e with
             | MLcons (_, r, [v])    when is_existT_ref r -> pp_expr state env v
             | MLcons (_, r, [_; v]) when is_existT_ref r -> pp_expr state env v
             | _ -> pp_expr state env e
           in
           (match unfold_list [] lst with
            | Some pargs ->
                str (fname ^ "(") ++
                prlist_with_sep (fun () -> str ", ") pp_pa pargs ++
                str ")"
            | None ->
                str (fname ^ "(/* dynamic list */)"))
       (* Inlined float64 binary operation *)
       | MLglob r, [a; b] when Option.has_some (classify_float_op r) ->
           let op = Option.get (classify_float_op r) in
           pp_atom state env a ++ str op ++ pp_atom state env b
       (* Inlined nat / int63 binary operation *)
       | MLglob r, [a; b] when Option.has_some (classify_nat_op r) ->
           let op = go_infix (Option.get (classify_nat_op r)) in
           pp_atom state env a ++ str op ++ pp_atom state env b
       | MLglob r, [a; b] when Option.has_some (classify_int63_op r) ->
           let op = go_infix (Option.get (classify_int63_op r)) in
           pp_atom state env a ++ str op ++ pp_atom state env b
       (* Signed int63 comparison (Sint63) — faithful to Go's int64 < / <= *)
       | MLglob r, [a; b] when Option.has_some (classify_sint63_op r) ->
           let op = go_infix (Option.get (classify_sint63_op r)) in
           pp_atom state env a ++ str op ++ pp_atom state env b
       | _ ->
           pp_atom state env head ++ str "(" ++
           prlist_with_sep (fun () -> str ", ")
             (pp_expr state env) vis ++
           str ")")

  | MLlam _ as e ->
      let ids, body = collect_lam e in
      let vis = List.filter (fun id -> not (is_dummy id)) ids in
      let new_env = List.rev ids @ env in
      str "func(" ++
      prlist_with_sep (fun () -> str ", ")
        (fun id -> pp_mlident id ++ str " any") vis ++
      str ") any {" ++ fnl () ++
      str "\treturn " ++ pp_expr state new_env body ++ fnl () ++
      str "}"

  | MLglob r ->
      if is_bool_true r     then str "true"
      else if is_bool_false r then str "false"
      else if is_map_make_ref r || is_map_make_typed_ref r then str "make(map[any]any)"
      else str (go_export (global_basename r))

  | MLfix (i, names, _) ->
      str (go_export (go_safe (Id.to_string names.(i))))

  | MLletin (id, e1, e2) ->
      let new_env = id :: env in
      str "(func() any {" ++ fnl () ++
      str "\t" ++ pp_mlident id ++ str " := " ++ pp_expr state env e1 ++ fnl () ++
      str "\treturn " ++ pp_expr state new_env e2 ++ fnl () ++
      str "})()"

  | MLcons _ as e ->
      (match nat_value e with
       | Some n -> str (string_of_int n)
       | None   ->
           match e with
           | MLcons (_, r, []) when is_unit_tt r    -> mt ()
           | MLcons (_, r, []) when is_bool_true r  -> str "true"
           | MLcons (_, r, []) when is_bool_false r -> str "false"
           | MLcons (_, r, []) when is_list_nil r   -> str "nil"
           | MLcons _ as lst ->
               (* Non-empty list literal: emit as append(nil, v1, v2, ...).
                  Go infers the slice element type from the values. *)
               (match unfold_list [] lst with
                | Some elems ->
                    str "append(nil, " ++
                    prlist_with_sep (fun () -> str ", ")
                      (pp_expr state env) elems ++
                    str ")"
                | None -> str "nil /* dynamic list */")
           | _ -> str "nil /* unhandled constructor */")

  | MLmagic e -> pp_expr state env e
  | MLdummy _ -> str "_"
  | MLfloat f ->
      let s = Float64.to_string f in
      (* Ensure Go sees a float literal: add .0 if no decimal or exponent. *)
      let s = if String.contains s '.' || String.contains s 'e'
                 || String.contains s 'E' || String.contains s 'n'
              then s else s ^ ".0" in
      str s
  | MLexn s   -> str ("panic(" ^ Printf.sprintf "%S" s ^ ")")
  | MLaxiom s -> str ("panic(\"axiom: " ^ String.escaped s ^ "\")")
  | MLuint n  -> str (Uint63.to_string n)
  | _         -> str "nil /* TODO */"

and pp_atom state env e =
  match e with
  | MLrel _ | MLglob _ | MLcons _ | MLuint _ | MLfloat _ | MLmagic _ ->
      pp_expr state env e
  | _ ->
      str "(" ++ pp_expr state env e ++ str ")"

(* An integer/float literal carries no Go type, so where the target type must be
   fixed (a value boxed into [any], a typed cell/accumulator, …) wrap a bare
   literal as [int64(..)] / [float64(..)].  Non-literals already have a type. *)
and pp_typed_lit state env e =
  match e with
  | MLuint _  -> str "int64("   ++ pp_expr state env e ++ str ")"
  | MLfloat _ -> str "float64(" ++ pp_expr state env e ++ str ")"
  | _         -> pp_expr state env e

(*s CFG blocks (the goto model).  A block is an [IO Next]: it does its effects
    then transfers control via [ret (Jump n)] (goto block n) or [ret Done]
    (return).  [block_targets] collects the Jump targets (so only used labels
    are emitted — Go rejects unused ones); [emit_block] prints one block. *)

and block_targets b acc =
  let h, args = collect_app b [] in
  let vis = List.filter (fun a -> not (is_erased a)) args in
  match h, vis with
  | MLglob r, [_action; k] when is_bind_ref r ->
      let _ids, kbody = collect_lam k in block_targets kbody acc
  | MLglob r, [next] when is_ret_ref r ->
      (match next with
       | MLcons (_, c, [n]) when is_jump_ctor c ->
           (match nat_value n with Some v -> v :: acc | None -> acc)
       | _ -> acc)
  | _ ->
      (match b with
       | MLcase (_, _, branches) ->
           Array.fold_left (fun a (_, _, body) -> block_targets body a) acc branches
       | _ -> acc)

(* Does any tail of this block [ret Done] (return)?  A block can both return on
   one branch and jump on another, so this is independent of [block_targets].
   Used to give every returning block an edge to the virtual exit node when
   computing post-dominators for the structurer. *)
and block_has_done b =
  let h, args = collect_app b [] in
  let vis = List.filter (fun a -> not (is_erased a)) args in
  match h, vis with
  | MLglob r, [_action; k] when is_bind_ref r ->
      let _ids, kbody = collect_lam k in block_has_done kbody
  | MLglob r, [next] when is_ret_ref r ->
      (match next with MLcons (_, c, []) when is_done_ctor c -> true | _ -> false)
  | _ ->
      (match b with
       | MLcase (_, _, branches) ->
           Array.exists (fun (_, _, body) -> block_has_done body) branches
       | _ -> false)

(* Loop-block-local variables (bound by a [bind] inside a block) are hoisted to
   [var x T] before the blocks so their declaration dominates all uses and is
   never re-run on a backward jump.  Only tagged reads ([ref_get tag r]) are
   hoistable here, since that is where the Go type is known. *)
and block_hoists b acc =
  let h, args = collect_app b [] in
  let vis = List.filter (fun a -> not (is_erased a)) args in
  match h, vis with
  | MLglob r, [action; k] when is_bind_ref r ->
      let ids, kbody = collect_lam k in
      let acc' =
        (match List.filter (fun id -> not (is_dummy id)) ids with
         | [x] ->
             let ah, aargs = collect_app action [] in
             let avis = List.filter (fun a -> not (is_erased a)) aargs in
             (match ah, avis with
              | MLglob rr, [tag; _rf] when is_ref_get_ref rr ->
                  (x, go_type_of_tag tag) :: acc
              | _ -> acc)
         | _ -> acc) in
      block_hoists kbody acc'
  | _ ->
      (match b with
       | MLcase (_, _, branches) ->
           Array.fold_left (fun a (_, _, body) -> block_hoists body a) acc branches
       | _ -> acc)

(* Emit one [bind] action (the non-control part of a block) as a Go statement.
   [ids] are the continuation's binders (for the [x =] lhs of a value read).
   - a [defer]/[go] closure captures the hoisted loop-temps BY VALUE
     ([kw func(iv T){ body }(iv)]) so each iteration's value is fixed here;
     capturing the shared hoisted cell by reference would give every closure the
     last value (the goto form of Go's loop-variable capture; the structured
     [for] lowering gets this free on Go 1.22+).  A closure body is not part of
     the CFG, so it terminates with [raw_term] (return).
   - a value read ([ref_get]) goes to its hoisted var with [=]; a void action
     (println / ref_set, whose [fun _] may extract as a named var) is just the
     statement. *)
and emit_action state hoists tab env ids action =
  let emit_closure kw body =
    let sep = prlist_with_sep (fun () -> str ", ") (fun x -> x) in
    let params = List.map (fun (x, t) -> pp_mlident x ++ str " " ++ str t) hoists in
    let args   = List.map (fun (x, _) -> pp_mlident x) hoists in
    str tab ++ str kw ++ str " func(" ++ sep params ++ str ") {" ++ fnl () ++
    emit_block state hoists raw_term (tab ^ "\t") env body ++
    str tab ++ str "}(" ++ sep args ++ str ")" ++ fnl ()
  in
  let ah, aargs = collect_app action [] in
  let avis = List.filter (fun a -> not (is_erased a)) aargs in
  match ah, avis with
  | MLglob rr, [dbody] when is_defer_call_ref rr -> emit_closure "defer" dbody
  | MLglob rr, [gbody] when is_go_spawn_ref rr -> emit_closure "go" gbody
  | _ ->
      let action_is_value =
        (match ah with MLglob rr -> is_ref_get_ref rr | _ -> false) in
      let lhs = match List.filter (fun id -> not (is_dummy id)) ids with
        | [x] when action_is_value -> pp_mlident x ++ str " = "
        | _   -> mt () in
      str tab ++ lhs ++ pp_expr state env action ++ fnl ()

(* [term] handles the block's terminator (a [Next] value) — see [raw_term] /
   [loop_term].  This is what lets one emitter print raw goto or structured
   continue/break. *)
and emit_block state hoists term tab env b =
  let h, args = collect_app b [] in
  let vis = List.filter (fun a -> not (is_erased a)) args in
  match h, vis with
  | MLglob r, [action; k] when is_bind_ref r ->
      let ids, kbody = collect_lam k in
      let new_env = List.rev ids @ env in
      emit_action state hoists tab env ids action
      ++ emit_block state hoists term tab new_env kbody
  | MLglob r, [next] when is_ret_ref r -> term tab next
  | _ ->
      (match b with
       | MLcase (_, scrut, branches) ->
           (match Array.to_list branches with
            | [ (_, p1, body1); (_, p2, body2) ] ->
                let cref p = (match p with Pusual r | Pcons (r, _) -> Some r | _ -> None) in
                (match cref p1, cref p2 with
                 | Some c1, Some c2
                   when (is_bool_true c1 && is_bool_false c2)
                     || (is_bool_false c1 && is_bool_true c2) ->
                     let tb, eb = if is_bool_true c1 then body1, body2 else body2, body1 in
                     str tab ++ str "if " ++ pp_expr state env scrut ++ str " {" ++ fnl () ++
                     emit_block state hoists term (tab ^ "\t") env tb ++
                     str tab ++ str "} else {" ++ fnl () ++
                     emit_block state hoists term (tab ^ "\t") env eb ++
                     str tab ++ str "}" ++ fnl ()
                 | _ -> str tab ++ str "return" ++ fnl ())
            | _ -> str tab ++ str "return" ++ fnl ())
       | _ -> str tab ++ pp_expr state env b ++ fnl ())

(*s Structuring: recognise a goto-CFG that is a [while] loop and lift it back to
    an idiomatic Go [for].  Shape: two blocks, entry at 0; block 0 (the header)
    jumps only to itself (loop around) or to block 1 (exit); block 1 is terminal
    (no jumps).  This lowers to [for { <block0, loop_term 0 1> } <block1>], where
    [loop_term] turns the jump-to-header into fall-through and the jump-to-exit
    into [break] — no labels, no goto.  Anything else stays raw goto. *)

let as_while_loop start_v bs =
  match bs with
  | [b0; b1] when start_v = 0 ->
      let t0 = block_targets b0 [] in
      let t1 = block_targets b1 [] in
      if List.for_all (fun n -> n = 0 || n = 1) t0
         && List.mem 0 t0 && List.mem 1 t0 && t1 = []
      then Some (b0, b1) else None
  | _ -> None

(*s IO body emitter — shared by pp_function (for IO-returning fns) and pp_main_body. *)

let pp_io_body state tab env body =
  let is_void_call e =
    match collect_app e [] with
    | MLglob r, _ when is_print_ref r || is_println_ref r || is_panic_ref r -> true
    | MLglob r, _ when is_map_set_ref r || is_map_del_ref r -> true
    | MLglob r, _ when is_send_ref r -> true
    | MLglob r, _ when is_close_chan_ref r -> true
    | MLglob r, _ when is_ref_set_ref r -> true
    | _ -> false
  in
  let is_terminating e =
    match collect_app e [] with
    | MLglob r, _ when is_panic_ref r -> true
    | _ -> false
  in
  let rec pp_stmts tab env = function
    | MLapp _ as e ->
        let head, all_args = collect_app e [] in
        let vis = List.filter (fun a -> not (is_erased a)) all_args in
        (match head, vis with
         | MLglob r, [m; f] when is_bind_ref r ->
             (match strip_magic m with
              (* IO-valued branch: bind distributes over case, so push the
                 continuation f into every arm.  This turns the match into a
                 statement (if/switch) rather than a value. *)
              | MLcase (typ, scrut, branches) ->
                  (* Lift the continuation past each arm's pattern binders so its
                     de Bruijn indices stay correct inside the branch scope. *)
                  emit_case tab env typ scrut branches
                    (fun nb b -> MLapp (head, [b; ast_lift nb f]))
              | _ ->
             let ids, body = collect_lam f in
             let new_env = List.rev ids @ env in
             (* go_spawn: bind (go_spawn goroutine_body) f → go func(){body}(); f *)
             let h_m, all_m = collect_app m [] in
             let vis_m = List.filter (fun a -> not (is_erased a)) all_m in
             (match h_m, vis_m with
              | MLglob r2, [goroutine_body] when is_go_spawn_ref r2 ->
                  str tab ++ str "go func() {" ++ fnl () ++
                  pp_stmts (tab ^ "\t") env goroutine_body ++
                  str tab ++ str "}()" ++ fnl () ++
                  pp_stmts tab new_env body
              | MLglob r2, [defer_body] when is_defer_call_ref r2 ->
                  str tab ++ str "defer func() {" ++ fnl () ++
                  pp_stmts (tab ^ "\t") env defer_body ++
                  str tab ++ str "}()" ++ fnl () ++
                  pp_stmts tab new_env body
              | MLglob r2, [sess_ep] when is_sess_close_ref r2 ->
                  (* Use the endpoint var so Go doesn't complain "declared but not used" *)
                  str tab ++ str "_ = " ++ pp_expr state env sess_ep ++ fnl () ++
                  pp_stmts tab new_env body
              | MLglob r2, [xs; bodyfn] when is_for_each_ref r2 ->
                  emit_for_each tab env xs bodyfn ++
                  pp_stmts tab new_env body
              | _ ->
             let vis_ids = List.filter (fun id -> not (is_dummy id)) ids in
             let lhs = match vis_ids with
               | _ when is_void_call m   -> mt ()
               | _ when db1_free body    ->
                   (* If the head is a known value-returning builtin (slice_get,
                      type_assert, etc.), discard with _ =.
                      User-defined functions have unknown return — assume void. *)
                   let head_m, _ = collect_app m [] in
                   (match head_m with
                    | MLglob r when is_slice_get_ref r || is_type_assert_ref r
                                 || is_map_len_ref r || is_map_get_or_ref r
                                 || is_len_ref r || is_cap_ref r
                                 || is_recv_ref r || is_make_chan_ref r || is_make_chan_buf_ref r
                                 || Option.has_some (classify_nat_op r)
                                 || Option.has_some (classify_int63_op r)
                                 || Option.has_some (classify_float_op r) -> str "_ = "
                    | _                              -> mt ())
               | [id]                    -> pp_mlident id ++ str " := "
               | _                       -> mt ()
             in
             (* Bare MLglob in statement position is a zero-arg IO function
                call — needs () in Go.  Builtins handle their own emission. *)
             let emit_m =
               match m with
               | MLglob r when not (is_bool_true r || is_bool_false r
                                    || is_unit_tt r || is_map_make_ref r) ->
                   pp_expr state env m ++ str "()"
               | _ -> pp_expr state env m
             in
             str tab ++ lhs ++ emit_m ++ fnl () ++
             (if is_terminating m then mt ()
              else pp_stmts tab new_env body)))
         | MLglob r, [_] when is_ret_ref r -> mt ()
         (* for_each in tail position (not inside a bind) *)
         | MLglob r, [xs; bodyfn] when is_for_each_ref r ->
             emit_for_each tab env xs bodyfn
         (* run_blocks start [b0; b1; …] → Go labels + goto.  Only Jump-target
            labels are emitted (Go rejects unused labels); the label sits one
            indent left of its block, as gofmt wants. *)
         | MLglob r, [start; blocks] when is_run_blocks_ref r ->
             (match unfold_list [] blocks with
              | Some bs ->
                  let hoists =
                    List.fold_left (fun a b -> block_hoists b a) [] bs in
                  let start_v = match nat_value start with Some v -> v | None -> 0 in
                  (* hoisted declarations: var x T, dominating every block *)
                  let hoist_doc =
                    prlist
                      (fun (x, t) ->
                         str tab ++ str "var " ++ pp_mlident x ++ str " "
                         ++ str t ++ fnl ())
                      (List.rev hoists) in
                  let blocks = Array.of_list bs in
                  let nblk = Array.length blocks in
                  let exit_node = nblk in
                  (* acyclic ⟺ every jump goes strictly forward (a back/self edge
                     is a loop, handled by [as_while_loop] or the raw fallback). *)
                  let acyclic =
                    let ok = ref true in
                    Array.iteri
                      (fun i b ->
                         List.iter (fun t -> if t <= i then ok := false)
                           (block_targets b []))
                      blocks;
                    !ok in
                  (* raw labels + goto: the always-correct fallback.  Only Jump-
                     target labels are emitted (Go rejects unused ones); a label
                     sits one indent left of its block, as gofmt wants. *)
                  let emit_raw () =
                    let targets =
                      List.fold_left (fun a b -> block_targets b a) [] bs in
                    let is_target i = List.mem i targets in
                    let lbl_indent =
                      if String.length tab >= 1
                      then String.sub tab 0 (String.length tab - 1) else "" in
                    let initial =
                      if start_v = 0 then mt ()
                      else str tab ++ str (Printf.sprintf "goto block%d" start_v) ++ fnl () in
                    let rec emit_all i = function
                      | [] -> mt ()
                      | bi :: rest ->
                          (if is_target i
                           then str lbl_indent ++ str (Printf.sprintf "block%d:" i) ++ fnl ()
                           else mt ()) ++
                          emit_block state hoists raw_term tab env bi ++
                          emit_all (i + 1) rest
                    in
                    hoist_doc ++ initial ++ emit_all 0 bs in
                  (match as_while_loop start_v bs with
                   | Some (b0, b1) ->
                       (* structured: for { <header> } <exit> — no labels/goto *)
                       hoist_doc
                       ++ str tab ++ str "for {" ++ fnl ()
                       ++ emit_block state hoists (loop_term 0 1) (tab ^ "\t") env b0
                       ++ str tab ++ str "}" ++ fnl ()
                       ++ emit_block state hoists raw_term tab env b1
                   | None when acyclic && start_v = 0 ->
                       (* General acyclic structurer: lift a forward (loop-free)
                          CFG to nested if/else.  A conditional's branches are
                          emitted up to their merge — the immediate post-dominator
                          — then the merge region is emitted once after the if, so
                          no block is duplicated.  succ adds an edge to the virtual
                          exit for every returning block. *)
                       let succ i =
                         let ts = List.sort_uniq compare (block_targets blocks.(i) []) in
                         if block_has_done blocks.(i) then exit_node :: ts else ts in
                       let inter a b = List.filter (fun x -> List.mem x b) a in
                       let pdom = Array.make (nblk + 1) [] in
                       pdom.(exit_node) <- [exit_node];
                       for i = nblk - 1 downto 0 do
                         let common = match succ i with
                           | [] -> [exit_node]
                           | s0 :: rest ->
                               List.fold_left (fun acc x -> inter acc pdom.(x))
                                 pdom.(s0) rest in
                         pdom.(i) <- i :: common
                       done;
                       (* merge of a conditional = least-index block post-
                          dominating both branches' leaf successors *)
                       let merge_of tb eb =
                         let leaves bb =
                           let ts = List.sort_uniq compare (block_targets bb []) in
                           if block_has_done bb then exit_node :: ts else ts in
                         match List.sort_uniq compare (leaves tb @ leaves eb) with
                         | [] -> exit_node
                         | s0 :: rest ->
                             let common =
                               List.fold_left (fun acc x -> inter acc pdom.(x))
                                 pdom.(s0) rest in
                             (match List.sort compare common with
                              | m :: _ -> m | [] -> exit_node) in
                       (* a branch that is a bare unconditional jump to j (no
                          statements): if its target is the merge, the branch is
                          empty and the [if] is inverted/one-armed. *)
                       let bare_jump bb =
                         match collect_app bb [] with
                         | MLglob r, args when is_ret_ref r ->
                             (match List.filter (fun a -> not (is_erased a)) args with
                              | [MLcons (_, c, [nn])] when is_jump_ctor c -> nat_value nn
                              | _ -> None)
                         | _ -> None in
                       let rec emit_dag entry stop tab env =
                         if entry = stop || entry = exit_node then mt ()
                         else walk stop tab env blocks.(entry)
                       and walk stop tab env b =
                         let h, args = collect_app b [] in
                         let vis = List.filter (fun a -> not (is_erased a)) args in
                         match h, vis with
                         | MLglob r, [action; k] when is_bind_ref r ->
                             let ids, kbody = collect_lam k in
                             emit_action state hoists tab env ids action
                             ++ walk stop tab (List.rev ids @ env) kbody
                         | MLglob r, [next] when is_ret_ref r ->
                             (match next with
                              | MLcons (_, c, [nn]) when is_jump_ctor c ->
                                  (match nat_value nn with
                                   | Some j -> emit_dag j stop tab env
                                   | None -> str tab ++ str "return" ++ fnl ())
                              | _ -> str tab ++ str "return" ++ fnl ())
                         | _ ->
                             (match b with
                              | MLcase (_, scrut, branches) ->
                                  (match Array.to_list branches with
                                   | [ (_, p1, body1); (_, p2, body2) ] ->
                                       let cref p =
                                         (match p with Pusual r | Pcons (r, _) -> Some r | _ -> None) in
                                       (match cref p1, cref p2 with
                                        | Some c1, Some c2
                                          when (is_bool_true c1 && is_bool_false c2)
                                            || (is_bool_false c1 && is_bool_true c2) ->
                                            let tb, eb =
                                              if is_bool_true c1 then body1, body2 else body2, body1 in
                                            let m = merge_of tb eb in
                                            let then_empty = (bare_jump tb = Some m) in
                                            let else_empty = (bare_jump eb = Some m) in
                                            let cond = pp_expr state env scrut in
                                            let arms =
                                              if then_empty && not else_empty then
                                                str tab ++ str "if !" ++ pp_atom state env scrut ++ str " {" ++ fnl ()
                                                ++ walk m (tab ^ "\t") env eb
                                                ++ str tab ++ str "}" ++ fnl ()
                                              else if else_empty && not then_empty then
                                                str tab ++ str "if " ++ cond ++ str " {" ++ fnl ()
                                                ++ walk m (tab ^ "\t") env tb
                                                ++ str tab ++ str "}" ++ fnl ()
                                              else
                                                str tab ++ str "if " ++ cond ++ str " {" ++ fnl ()
                                                ++ walk m (tab ^ "\t") env tb
                                                ++ str tab ++ str "} else {" ++ fnl ()
                                                ++ walk m (tab ^ "\t") env eb
                                                ++ str tab ++ str "}" ++ fnl () in
                                            arms ++ emit_dag m stop tab env
                                        | _ -> str tab ++ str "return" ++ fnl ())
                                   | _ -> str tab ++ str "return" ++ fnl ())
                              | _ -> str tab ++ pp_expr state env b ++ fnl ())
                       in
                       hoist_doc ++ emit_dag start_v exit_node tab env
                   | None -> emit_raw ())
              | None ->
                  str tab ++ str "/* run_blocks: non-literal block list */" ++ fnl ())
         | MLglob r, [m; h] when String.equal (global_basename r) "catch" ->
             let ids, h_body = collect_lam h in
             let new_env = List.rev ids @ env in
             let p_id = match List.filter (fun id -> not (is_dummy id)) ids with
               | [id] -> pp_mlident id
               | _    -> str "_p"
             in
             let t = str tab in
             t ++ str "func() {" ++ fnl () ++
             t ++ str "\tdefer func() {" ++ fnl () ++
             t ++ str "\t\tif " ++ p_id ++ str " := recover(); " ++ p_id ++ str " != nil {" ++ fnl () ++
             pp_stmts (tab ^ "\t\t\t") new_env h_body ++
             t ++ str "\t\t}" ++ fnl () ++
             t ++ str "\t}()" ++ fnl () ++
             pp_stmts (tab ^ "\t") env m ++
             t ++ str "}()" ++ fnl ()
         (* go_spawn body (not inside bind — uncommon but valid) *)
         | MLglob r, [goroutine_body] when is_go_spawn_ref r ->
             str tab ++ str "go func() {" ++ fnl () ++
             pp_stmts (tab ^ "\t") env goroutine_body ++
             str tab ++ str "}()" ++ fnl ()
         (* defer_call f → defer func(){ f }() (function-scoped, like Go's defer) *)
         | MLglob r, [defer_body] when is_defer_call_ref r ->
             str tab ++ str "defer func() {" ++ fnl () ++
             pp_stmts (tab ^ "\t") env defer_body ++
             str tab ++ str "}()" ++ fnl ()
         (* recv_ok tag ch (fun x ok => body) → x, ok := <-ch; body *)
         | MLglob r, [_tag; ch; kont] when is_recv_ok_ref r ->
             let ids, k_body = collect_lam kont in
             let new_env = List.rev ids @ env in
             let vis_ids = List.filter (fun id -> not (is_dummy id)) ids in
             (match vis_ids with
              | [x_id; ok_id] ->
                  str tab ++ pp_mlident x_id ++ str ", " ++ pp_mlident ok_id ++
                  str " := <-" ++ pp_expr state env ch ++ fnl () ++
                  pp_stmts tab new_env k_body
              | _ ->
                  str tab ++ str "_, _ = <-" ++ pp_expr state env ch ++ fnl ())
         (* slice_at_ok tag xs i (fun v ok => body) → bounds-checked index:
              var v T
              ok := i < int64(len(xs))   (* i is uint63 >= 0; only upper bound *)
              if ok { v = xs[i] }
              body
            Each binder is emitted only when used; v defaults to its zero value
            when out of bounds, so no panic is possible. *)
         | MLglob r, [tag; xs; i; kont] when is_slice_at_ok_ref r ->
             let ids, k_body = collect_lam kont in
             let new_env = List.rev ids @ env in
             (match ids with
              | [v_id; ok_id] ->
                  let go_t = go_type_of_tag tag in
                  let xs_d = pp_expr state env xs in
                  let i_d  = pp_expr state env i in
                  let cond = i_d ++ str " < int64(len(" ++ xs_d ++ str "))" in
                  let v_decl =
                    if is_dummy v_id then mt ()
                    else str tab ++ str "var " ++ pp_mlident v_id ++ str " "
                         ++ str go_t ++ fnl () in
                  let ok_bind =
                    if is_dummy ok_id then mt ()
                    else str tab ++ pp_mlident ok_id ++ str " := " ++ cond ++ fnl () in
                  let guard = if is_dummy ok_id then cond else pp_mlident ok_id in
                  let if_block =
                    if is_dummy v_id then mt ()
                    else
                      str tab ++ str "if " ++ guard ++ str " {" ++ fnl () ++
                      str (tab ^ "\t") ++ pp_mlident v_id ++ str " = "
                        ++ xs_d ++ str "[" ++ i_d ++ str "]" ++ fnl () ++
                      str tab ++ str "}" ++ fnl () in
                  v_decl ++ ok_bind ++ if_block ++ pp_stmts tab new_env k_body
              | _ ->
                  pp_stmts tab new_env k_body)
         (* type_assert_safe tag x (fun v ok => body) → v, ok := x.(T); body
            Go's native two-value assertion: ok=false (no panic) on mismatch. *)
         | MLglob r, [tag; x; kont] when is_type_assert_safe_ref r ->
             let go_t = go_type_of_tag tag in
             let inner = match x with
               | MLcons (_, r2, [a])    when is_existT_ref r2 -> pp_expr state env a
               | MLcons (_, r2, [_; a]) when is_existT_ref r2 -> pp_expr state env a
               | _ -> pp_expr state env x in
             let ids, k_body = collect_lam kont in
             let new_env = List.rev ids @ env in
             (match ids with
              | [v_id; ok_id] when not (is_dummy v_id && is_dummy ok_id) ->
                  str tab ++ pp_mlident v_id ++ str ", " ++ pp_mlident ok_id ++
                  str " := " ++ inner ++ str ".(" ++ str go_t ++ str ")" ++ fnl () ++
                  pp_stmts tab new_env k_body
              | _ ->
                  pp_stmts tab new_env k_body)
         (* make_sess (fun ep1 ep2 => body) → ch := make(chan any); ep1 := ch; ep2 := ch
            Both endpoints share one chan any; the continuation is always emitted,
            and each non-dummy endpoint is aliased to the channel. *)
         | MLglob r, vis when is_make_sess_ref r ->
             let f = List.nth vis (List.length vis - 1) in
             let ids, k_body = collect_lam f in
             let new_env = List.rev ids @ env in
             let assigns =
               List.filter_map
                 (fun id ->
                    if is_dummy id then None
                    else Some (str tab ++ pp_mlident id ++ str " := _sess_ch" ++ fnl ()))
                 ids
             in
             str tab ++ str "_sess_ch := make(chan any)" ++ fnl () ++
             (if assigns = [] then str tab ++ str "_ = _sess_ch" ++ fnl ()
              else prlist (fun x -> x) assigns) ++
             pp_stmts tab new_env k_body
         (* sess_send ep v (fun ep' => body) → ep <- v; ep' := ep; body
            Proto index P may precede ep in the arg list (not erased if Proto:Type);
            take the last 3 visible args as ep, v, kont. *)
         | MLglob r, vis when is_sess_send_ref r && List.length vis >= 3 ->
             let n = List.length vis in
             let ep   = List.nth vis (n - 3) in
             let v    = List.nth vis (n - 2) in
             let kont = List.nth vis (n - 1) in
             (* chan any requires explicit Go types for literals — untyped constants
                default to int/float64 which may not match the recv's type assertion. *)
             let pp_val = pp_typed_lit state env in
             let ids, k_body = collect_lam kont in
             let new_env = List.rev ids @ env in
             (* Alias the advanced endpoint when the continuation binds it; the
                continuation body is always emitted (never dropped). *)
             let assign =
               match List.filter (fun id -> not (is_dummy id)) ids with
               | [ep'_id] ->
                   str tab ++ pp_mlident ep'_id ++ str " := " ++ pp_expr state env ep ++ fnl ()
               | _ -> mt ()
             in
             str tab ++ pp_expr state env ep ++ str " <- " ++ pp_val v ++ fnl () ++
             assign ++
             pp_stmts tab new_env k_body
         (* sess_recv tag ep (fun v ep' => body) → _r := <-ep; v := _r.(T); ep' := ep; body
            Proto index P may precede tag; take the last 3 visible args as tag, ep, kont. *)
         | MLglob r, vis when is_sess_recv_ref r && List.length vis >= 3 ->
             let n = List.length vis in
             let tag  = List.nth vis (n - 3) in
             let ep   = List.nth vis (n - 2) in
             let kont = List.nth vis (n - 1) in
             let go_t = go_type_of_tag tag in
             let ids, k_body = collect_lam kont in
             let new_env = List.rev ids @ env in
             (* Continuation binds [v] then [ep']; either may be dummy.  We always
                emit the receive and the continuation body. *)
             let v_id, ep_id = match ids with
               | [a; b] -> a, b
               | [a]    -> a, Dummy
               | _      -> Dummy, Dummy
             in
             let recv_line =
               if is_dummy v_id then
                 (* value discarded — receive and drop, no type assertion needed *)
                 str tab ++ str "<-" ++ pp_expr state env ep ++ fnl ()
               else
                 let nm = match v_id with
                   | Id v | Tmp v -> go_safe (Id.to_string v)
                   | Dummy        -> "v"
                 in
                 let tmp = "_sr_" ^ nm in
                 str tab ++ str (tmp ^ " := <-") ++ pp_expr state env ep ++ fnl () ++
                 str tab ++ pp_mlident v_id ++ str (" := " ^ tmp ^ ".(" ^ go_t ^ ")") ++ fnl ()
             in
             let ep_line =
               if is_dummy ep_id then mt ()
               else str tab ++ pp_mlident ep_id ++ str " := " ++ pp_expr state env ep ++ fnl ()
             in
             recv_line ++ ep_line ++ pp_stmts tab new_env k_body
         (* sess_close ep → _ = ep; marks endpoint var as used, session is done *)
         | MLglob r, [sess_ep] when is_sess_close_ref r ->
             str tab ++ str "_ = " ++ pp_expr state env sess_ep ++ fnl ()
         | _ ->
             str tab ++ pp_expr state env e ++ fnl ())
    | MLletin (id, e1, e2) ->
        let new_env = id :: env in
        (* map_get_or k default m → two-statement pattern: no IIFE *)
        let head1, all_args1 = collect_app e1 [] in
        let vis1 = List.filter (fun a -> not (is_erased a)) all_args1 in
        (match head1, vis1 with
         | MLglob r, [k; def; m] when is_map_get_or_ref r && not (is_dummy id) ->
             let lhs = pp_mlident id in
             str tab ++ str "var " ++ lhs ++ str " any = "
               ++ pp_typed_lit state env def ++ fnl () ++
             str tab ++ str "if _v, _ok := " ++ pp_expr state env m ++
             str "[" ++ pp_expr state env k ++ str "]; _ok {" ++ fnl () ++
             str tab ++ str "\t" ++ lhs ++ str " = _v" ++ fnl () ++
             str tab ++ str "}" ++ fnl () ++
             pp_stmts tab new_env e2
         (* let acc := slice_fold xs init step in body →
              acc := init
              for _, x := range xs { acc = step acc x }
              body
            The accumulator reuses the let-bound Go variable [id]; [step]'s two
            binders map to (acc=id, x=loop var). *)
         | MLglob r, [xs; init; step] when is_slice_fold_ref r && not (is_dummy id) ->
             let step_ids, step_body = collect_lam step in
             (match step_ids with
              | [_acc; x_id] ->
                  let acc = pp_mlident id in
                  (* step_body env: MLrel 1 = x, MLrel 2 = acc (= id); any captured
                     outer vars sit past both binders in [env]. *)
                  let loop_env = x_id :: id :: env in
                  str tab ++ acc ++ str " := " ++ pp_typed_lit state env init ++ fnl () ++
                  str tab ++ str "for _, " ++ pp_mlident x_id ++ str " := range "
                    ++ pp_expr state env xs ++ str " {" ++ fnl () ++
                  str (tab ^ "\t") ++ acc ++ str " = "
                    ++ pp_expr state loop_env step_body ++ fnl () ++
                  str tab ++ str "}" ++ fnl () ++
                  pp_stmts tab new_env e2
              | _ ->
                  str tab ++ pp_mlident id ++ str " := " ++ pp_expr state env e1
                    ++ fnl () ++ pp_stmts tab new_env e2)
         | _ ->
             let lhs = if is_dummy id || is_void_call e1 then mt ()
                       else pp_mlident id ++ str " := " in
             str tab ++ lhs ++ pp_expr state env e1 ++ fnl () ++
             pp_stmts tab new_env e2)
    (* Case analysis in statement position (tail of an IO body). *)
    | MLcase (typ, scrut, branches) ->
        emit_case tab env typ scrut branches (fun _nb b -> b)
    | MLcons (_, r, []) when is_unit_tt r -> mt ()
    (* Bare nullary IO function in tail position — needs () to be a call,
       not a function value. *)
    | MLglob r as e
      when not (is_bool_true r || is_bool_false r
                || is_unit_tt r || is_map_make_ref r) ->
        str tab ++ pp_expr state env e ++ str "()" ++ fnl ()
    | e ->
        str tab ++ pp_expr state env e ++ fnl ()

  (* Emit an [MLcase] as Go statements.  [mk_body] transforms each arm's body
     before it is printed: the identity in tail position, or "wrap in [bind …
     k]" when a continuation must be threaded into every arm.  Only [bool]
     matches (i.e. [if]/[else]) are lowered for now; richer inductives and
     type switches follow. *)
  and emit_case tab env typ scrut branches mk_body =
    (* Branch binders are stored in constructor order [arg0; …; argN]; the body
       env is [List.rev ids @ env] (innermost binder = last arg = MLrel 1),
       matching the lambda convention used elsewhere. *)
    let ctor_of (ids, pat, body) =
      match pat with
      | Pusual r | Pcons (r, _)   -> (Some r, ids, body)
      | Pwild | Prel _ | Ptuple _ -> (None, ids, body)
    in
    let unhandled () =
      str tab ++ str "panic(\"unhandled match\") // TODO: unsupported MLcase"
      ++ fnl ()
    in
    (* Emit a two-arm if/else; [pre] (e.g. an "x, ok :=" init clause) precedes
       the condition, and [tenv]/[fenv] are the branch environments. *)
    let if_else pre cond (tbody, tn, tenv) (fbody, fn, fenv) =
      str tab ++ str "if " ++ pre ++ cond ++ str " {" ++ fnl () ++
      pp_stmts (tab ^ "\t") tenv (mk_body tn tbody) ++
      str tab ++ str "} else {" ++ fnl () ++
      pp_stmts (tab ^ "\t") fenv (mk_body fn fbody) ++
      str tab ++ str "}" ++ fnl ()
    in
    (* [list GoRune] = string; the slice lowering (xs[0], xs[1:]) is byte-wise
       and wrong for runes, so a string match is excluded from the list case. *)
    let is_string_list =
      match typ with
      | Tglob (r, [Tglob (elem, [])]) ->
          is_list_type r && String.equal (global_basename elem) "GoInt32"
      | _ -> false
    in
    match Array.to_list branches with
    | [ b1; b2 ] ->
        let (r1, ids1, body1) = ctor_of b1 in
        let (r2, ids2, body2) = ctor_of b2 in
        (match r1, r2 with
         (* if/else: match on bool *)
         | Some c1, Some c2
           when (is_bool_true c1 && is_bool_false c2)
             || (is_bool_false c1 && is_bool_true c2) ->
             let then_b, else_b =
               if is_bool_true c1 then body1, body2 else body2, body1 in
             if_else (mt ()) (pp_expr state env scrut)
               (then_b, 0, env) (else_b, 0, env)
         (* option: match on [map_get_opt k m] → comma-ok lookup.  The Some arm
            binds the value; the None arm is the absent case.  Only the
            map-lookup producer is fused; a free [option] value is not yet
            representable. *)
         | Some c1, Some c2
           when (is_some_ctor c1 && is_none_ctor c2)
             || (is_none_ctor c1 && is_some_ctor c2) ->
             let some_ids, some_body, none_body =
               if is_some_ctor c1 then ids1, body1, body2
               else ids2, body2, body1 in
             let sh, sargs = collect_app (strip_magic scrut) [] in
             let svis = List.filter (fun a -> not (is_erased a)) sargs in
             (match sh, svis with
              | MLglob r, [k; m] when is_map_get_opt_ref r ->
                  let v_doc = match some_ids with
                    | [id] when not (is_dummy id) -> pp_mlident id
                    | _ -> str "_" in
                  let pre =
                    v_doc ++ str ", _ok := " ++ pp_expr state env m ++
                    str "[" ++ pp_expr state env k ++ str "]; " in
                  if_else pre (str "_ok")
                    (some_body, List.length some_ids, List.rev some_ids @ env)
                    (none_body, 0, env)
              | _ -> unhandled ())
         (* list / slice: [match xs with [] | x :: rest] → len / index / reslice.
            Slices only — string (list GoRune) matches are excluded above. *)
         | Some c1, Some c2
           when ((is_list_nil c1 && is_list_cons c2)
              || (is_list_cons c1 && is_list_nil c2))
             && not is_string_list ->
             let nil_body, cons_ids, cons_body =
               if is_list_nil c1 then body1, ids2, body2
               else body2, ids1, body1 in
             let head_id, tail_id = match cons_ids with
               | [h; t] -> h, t
               | _      -> Dummy, Dummy in
             let xs = pp_expr state env scrut in
             let prefix =
               (if is_dummy head_id then mt ()
                else str (tab ^ "\t") ++ pp_mlident head_id ++ str " := "
                     ++ xs ++ str "[0]" ++ fnl ()) ++
               (if is_dummy tail_id then mt ()
                else str (tab ^ "\t") ++ pp_mlident tail_id ++ str " := "
                     ++ xs ++ str "[1:]" ++ fnl ())
             in
             str tab ++ str "if len(" ++ xs ++ str ") == 0 {" ++ fnl () ++
             pp_stmts (tab ^ "\t") env (mk_body 0 nil_body) ++
             str tab ++ str "} else {" ++ fnl () ++
             prefix ++
             pp_stmts (tab ^ "\t") (List.rev cons_ids @ env)
               (mk_body (List.length cons_ids) cons_body) ++
             str tab ++ str "}" ++ fnl ()
         | _ -> unhandled ())
    | _ -> unhandled ()

  (* for_each xs (fun x => body) → for _, x := range xs { body } *)
  and emit_for_each tab env xs bodyfn =
    let ids, body = collect_lam bodyfn in
    let new_env = List.rev ids @ env in
    let hdr =
      match List.filter (fun id -> not (is_dummy id)) ids with
      | [x] -> str "for _, " ++ pp_mlident x ++ str " := range "
      | _   -> str "for range " in
    str tab ++ hdr ++ pp_expr state env xs ++ str " {" ++ fnl () ++
    pp_stmts (tab ^ "\t") new_env body ++
    str tab ++ str "}" ++ fnl ()
  in
  let rec peel_catches tab env b =
    let head, all_args = collect_app b [] in
    let vis = List.filter (fun a -> not (is_erased a)) all_args in
    match head, vis with
    | MLglob r, [m; h] when String.equal (global_basename r) "catch" ->
        let ids, h_body = collect_lam h in
        let new_env = List.rev ids @ env in
        let p_id = match List.filter (fun id -> not (is_dummy id)) ids with
          | [id] -> pp_mlident id
          | _    -> str "_p"
        in
        let t = str tab in
        t ++ str "defer func() {" ++ fnl () ++
        t ++ str "\tif " ++ p_id ++ str " := recover(); " ++ p_id ++ str " != nil {" ++ fnl () ++
        pp_stmts (tab ^ "\t\t") new_env h_body ++
        t ++ str "\t}" ++ fnl () ++
        t ++ str "}()" ++ fnl () ++
        peel_catches tab env m
    | _ -> pp_stmts tab env b
  in
  peel_catches tab env body

(*s Declaration printer. *)

(** Emit a top-level function, collecting leading lambdas for the signature
    and using [typ] for parameter/return type annotations. *)
let pp_function state name body typ =
  let ids, inner_body = collect_lam body in
  let param_types, ret_type = collect_tarrs typ in
  (* Pair visible ids with their corresponding types, skipping erased args. *)
  let rec zip_params ids types =
    match ids, types with
    | [], _              -> []
    | id :: rest, _ when is_dummy id ->
        let rest_types = (match types with _ :: t -> t | [] -> []) in
        zip_params rest rest_types
    | id :: rest, t :: rest_types -> (id, t) :: zip_params rest rest_types
    | id :: rest, []              -> (id, Tunknown) :: zip_params rest []
  in
  let param_pairs = zip_params ids param_types in
  (* env includes all ids (with dummies) for de Bruijn; innermost first. *)
  let full_env = List.rev ids in
  let fn_sig =
    str "func " ++ str (go_export name) ++ str "(" ++
    prlist_with_sep (fun () -> str ", ")
      (fun (id, t) -> pp_mlident id ++ str " " ++ pp_type state t)
      param_pairs
  in
  (* IO-returning functions use pp_io_body; pure functions use return+expr *)
  match ret_type with
  | Tglob (r, [inner]) when is_IO_type r ->
      let go_ret = match inner with
        | Tglob (r2, []) when is_unit_type r2 -> mt ()   (* IO unit → void *)
        | t -> str " " ++ pp_type state t
      in
      fn_sig ++ str ")" ++ go_ret ++ str " {" ++ fnl () ++
      pp_io_body state "\t" full_env inner_body ++
      str "}" ++ fnl ()
  | _ ->
      fn_sig ++ str ") " ++ pp_type state ret_type ++ str " {" ++ fnl () ++
      str "\treturn " ++ pp_expr state full_env inner_body ++ fnl () ++
      str "}" ++ fnl ()

(*s Stdlib terms that are inlined at call sites — skip as top-level decls. *)

let is_inlined_ref r =
  is_nat_zero r || is_nat_succ r ||
  is_bool_true r || is_bool_false r ||
  is_print_ref r || is_println_ref r ||
  is_len_ref r || is_cap_ref r || is_append_ref r || is_panic_ref r ||
  is_type_assert_ref r || is_type_assert_safe_ref r ||
  is_go_type_tag_ctor r || is_zero_val_ref r ||
  is_slice_of_list_ref r || is_slice_get_ref r || is_slice_at_ok_ref r ||
  is_for_each_ref r || is_slice_fold_ref r || is_run_blocks_ref r ||
  is_ref_type r || is_ref_new_ref r || is_ref_get_ref r || is_ref_set_ref r ||
  is_go_map_type r || is_map_make_ref r || is_map_make_typed_ref r ||
  is_map_set_ref r || is_map_del_ref r || is_map_len_ref r || is_map_get_or_ref r ||
  is_map_get_opt_ref r ||
  is_go_chan_type r || is_make_chan_ref r || is_make_chan_buf_ref r ||
  is_send_ref r || is_recv_ref r || is_close_chan_ref r || is_recv_ok_ref r ||
  is_go_spawn_ref r || is_defer_call_ref r ||
  is_sess_endpoint_ref r || is_make_sess_ref r ||
  is_sess_send_ref r || is_sess_recv_ref r || is_sess_close_ref r ||
  is_dual_ref r || is_proto_ctor r || is_proto_type r ||
  is_IO_type r || is_ret_ref r || is_bind_ref r ||
  String.equal (global_basename r) "catch" ||
  String.equal (global_basename r) "with_defer" ||
  is_unit_tt r ||
  is_go_prim_type r || is_float64_type r ||
  List.exists (fun (name, _) -> is_float_op_ref r name) float_op_table ||
  is_existT_ref r || is_sigT_ref r ||
  List.exists (fun (name, _) -> is_nat_op_ref r name) nat_op_names ||
  List.exists (fun (name, _) -> is_int63_op_ref r name) nat_op_names ||
  List.exists (fun (name, _) -> is_int63_op_ref r name) sint63_cmp_names

(*s Main-package wrapper. *)

(** Emit [func main() { _ = EntryFn() }] for the given entry-point name. *)
let pp_main_call fn_name =
  fnl () ++
  str "func main() {" ++ fnl () ++
  str ("\t" ^ go_export fn_name ^ "()") ++ fnl () ++
  str "}" ++ fnl ()

(** Emit [func main()] with the entry body inlined directly. *)
(** Emit [func main()] body as flat sequential statements.
    [MLletin] chains become [x := rhs] assignments rather than IIFEs. *)
(** Emit the body of any IO-returning function as flat sequential statements.
    Used by both [pp_main_body] and [pp_function] for IO-typed functions. *)
let pp_main_body state body =
  str "func main() {" ++ fnl () ++
  pp_io_body state "\t" [] body ++
  str "}" ++ fnl ()

(*s Declaration printer. *)

let pp_decl state decl =
  match decl with
  | Dterm (r, _, _) when is_inlined_ref r ->
      mt ()

  (* Suppress top-level definitions whose result type is Proto — protocol
     descriptors are proof-only witnesses with no runtime representation. *)
  | Dterm (_, _, Tglob (rt, _)) when is_proto_type rt ->
      mt ()

  | Dterm (r, body, typ) ->
      let name = global_basename r in
      (match body with
       | MLlam _ ->
           pp_function state name body typ ++ fnl ()
       | _ ->
           match typ with
           | Tglob (r, []) when is_unit_type r ->
               str "func " ++ str (go_export name) ++ str "() {" ++ fnl () ++
               str "\t" ++ pp_expr state [] body ++ fnl () ++
               str "}" ++ fnl () ++ fnl ()
           | Tglob (r, [inner]) when is_IO_type r ->
               let go_ret = match inner with
                 | Tglob (r2, []) when is_unit_type r2 -> mt ()
                 | t -> str " " ++ pp_type state t
               in
               str "func " ++ str (go_export name) ++ str "()" ++ go_ret ++ str " {" ++ fnl () ++
               pp_io_body state "\t" [] body ++
               str "}" ++ fnl () ++ fnl ()
           | _ ->
               str "var " ++ str (go_export name) ++ str " " ++
               pp_type state typ ++ str " = " ++
               pp_expr state [] body ++ fnl () ++ fnl ())

  | Dfix (refs, bodies, types) ->
      if Array.exists is_inlined_ref refs then mt ()
      else
        prvecti
          (fun i _ -> pp_function state (global_basename refs.(i)) bodies.(i) types.(i))
          refs

  | Dind _ ->
      (* nat and bool are treated as builtins; other inductives are TODO *)
      mt ()

  | Dtype (r, _, _) when is_uint63_type r || is_go_prim_type r || is_float64_type r
    || is_IO_type r || is_go_map_type r || is_go_chan_type r
    || is_sess_endpoint_ref r || is_ref_type r
    || String.equal (global_basename r) "GoString"
    || String.equal (global_basename r) "GoSlice" -> mt ()
  | Dtype (_, _, Tglob (r, _)) when is_sigT_ref r    -> mt ()

  | Dtype (r, _, typ) ->
      str "type " ++ str (go_export (global_basename r)) ++
      str " = " ++ pp_type state typ ++ fnl ()

(*s Structure printer. *)

let pp_struct state struc =
  let pp_mod (mp, sel) =
    State.with_visibility state mp [] (fun state ->
      prlist
        (fun (_, elem) ->
           match elem with
           | SEdecl d      -> pp_decl state d
           | SEmodule _
           | SEmodtype _   -> mt ())
        sel)
  in
  prlist pp_mod struc

(*s Language descriptor. *)

let go_descr : Common.State.t language_descr = {
  keywords;
  file_suffix  = ".go";
  file_naming;
  preamble;
  pp_struct;
  sig_suffix   = None;
  sig_preamble;
  pp_sig;
  pp_decl;
}
