(** Rocq → Go extraction backend.
    MiniML printer for extracted Go packages.

    Type map:
      nat  → uint
      bool → bool

    Nat and bool operations are inlined as Go operators/literals.
    All other globals become exported Go identifiers. *)

open Pp
open Names
open Miniml
open Mlutil
open Modutil
open Table
open Common

(*s Keywords that may not be used as Go identifiers. *)

let keywords =
  let kws = [
    "break"; "case"; "chan"; "const"; "continue"; "default"; "defer";
    "else"; "fallthrough"; "for"; "func"; "go"; "goto"; "if"; "import";
    "interface"; "map"; "package"; "range"; "return"; "select"; "struct";
    "switch"; "type"; "var";
    (* predeclared identifiers *)
    "any"; "bool"; "byte"; "comparable"; "complex64"; "complex128";
    "error"; "float32"; "float64"; "int"; "int8"; "int16"; "int32";
    "int64"; "rune"; "string"; "uint"; "uint8"; "uint16"; "uint32";
    "uint64"; "uintptr"; "true"; "false"; "iota"; "nil";
    "append"; "cap"; "clear"; "close"; "complex"; "copy"; "delete";
    "imag"; "len"; "make"; "max"; "min"; "new"; "panic"; "print";
    "println"; "real"; "recover";
  ] in
  List.fold_left (fun s w -> Id.Set.add (Id.of_string w) s) Id.Set.empty kws

(*s File naming. *)

let file_naming state mp =
  file_of_modfile (State.get_table state) mp

(*s Preamble emitted at the top of every extracted .go file. *)

let preamble_for_pkg pkg _state _name _comment _used_modules _safe =
  str "// Code generated by rocq-go-extraction; DO NOT EDIT." ++ fnl () ++
  fnl () ++
  str ("package " ^ pkg) ++ fnl () ++ fnl ()

let preamble = preamble_for_pkg "fido"

let sig_preamble _state _name _comment _used_modules _safe = mt ()

let pp_sig _state _sig = mt ()

(*s Identifier utilities. *)

(** Sanitise a Rocq id for Go: replace prime ['] with underscore. *)
let go_safe s = String.map (function '\'' -> '_' | c -> c) s

let pp_goid id = str (go_safe (Id.to_string id))

(** Capitalise the first character (export in Go). *)
let go_export s =
  if String.length s = 0 then s
  else
    let b = Bytes.of_string s in
    Bytes.set b 0 (Char.uppercase_ascii (Bytes.get b 0));
    Bytes.to_string b

(*s Global-reference helpers. *)

let global_path r =
  try
    DirPath.to_string (Nametab.dirpath_of_global r.glob) ^ "." ^
    Id.to_string (Nametab.basename_of_global r.glob)
  with Not_found -> ""

let global_basename r =
  try Id.to_string (Nametab.basename_of_global r.glob)
  with Not_found -> ""

let ref_has_suffix r suffix =
  let p = global_path r in
  let n = String.length p and m = String.length suffix in
  n >= m && String.equal suffix (String.sub p (n - m) m)

(*s Standard-library type and constructor recognition. *)

let is_unit_type   r = ref_has_suffix r ".Init.Datatypes.unit"
let is_nat_type    r = ref_has_suffix r ".Init.Datatypes.nat"
let is_uint63_type r =
  ref_has_suffix r ".PrimInt63.int" ||
  ref_has_suffix r ".Cyclic.Int63.PrimInt63.int"
let is_nat_zero r  = ref_has_suffix r ".Init.Datatypes.O"
let is_nat_succ r  = ref_has_suffix r ".Init.Datatypes.S"
let is_bool_type r = ref_has_suffix r ".Init.Datatypes.bool"
let is_bool_true r = ref_has_suffix r ".Init.Datatypes.true"
let is_bool_false r = ref_has_suffix r ".Init.Datatypes.false"
let is_unit_tt r   = ref_has_suffix r ".Init.Datatypes.tt"
let is_list_type r =
  ref_has_suffix r ".Init.Datatypes.list"
let is_list_nil r  =
  ref_has_suffix r ".Init.Datatypes.nil" ||
  String.equal (global_basename r) "nil"
let is_list_cons r =
  ref_has_suffix r ".Init.Datatypes.cons" ||
  String.equal (global_basename r) "cons"

(*s println / GoAny model recognition. *)

(* Basename matching is safe here because Go builtin names are unqualified
   and no user theory should shadow them.  All other Go stdlib calls are
   package-qualified (e.g. fmt.Println) and will never match these. *)
let is_print_ref r   = String.equal (global_basename r) "print"
(* Table of axiom type names → Go type keywords.
   Basename matching is safe: these names are reserved by builtins.v and
   no user theory should shadow them. *)
let go_prim_type_table = [
  "GoInt",     "int";
  "GoInt8",    "int8";
  "GoInt16",   "int16";
  "GoInt32",   "int32";
  "GoUint",    "uint";
  "GoUint8",   "uint8";
  "GoUint16",  "uint16";
  "GoUint32",  "uint32";
  "GoUint64",  "uint64";
  "GoFloat32", "float32";
]

let is_float64_type r =
  ref_has_suffix r ".PrimFloat.float" ||
  String.equal (global_basename r) "float"

let classify_go_prim_type r =
  List.assoc_opt (global_basename r) go_prim_type_table

let is_go_prim_type r = Option.has_some (classify_go_prim_type r)

let is_println_ref r = String.equal (global_basename r) "println"
let is_len_ref    r  = String.equal (global_basename r) "len"
let is_cap_ref    r  = String.equal (global_basename r) "cap"
let is_append_ref r  = String.equal (global_basename r) "append"
let is_go_map_type  r = String.equal (global_basename r) "GoMap"
let is_slice_of_list_ref r = String.equal (global_basename r) "slice_of_list"
let is_slice_get_ref     r = String.equal (global_basename r) "slice_get"
let is_map_make_ref       r = String.equal (global_basename r) "map_make"
let is_map_make_typed_ref r = String.equal (global_basename r) "map_make_typed"
let is_map_set_ref  r = String.equal (global_basename r) "map_set"
let is_map_del_ref  r = String.equal (global_basename r) "map_delete"
let is_map_len_ref    r = String.equal (global_basename r) "map_len"
let is_map_get_or_ref r = String.equal (global_basename r) "map_get_or"
let is_panic_ref       r = String.equal (global_basename r) "panic"
let is_type_assert_ref r = String.equal (global_basename r) "type_assert"

(* GoTypeTag constructors → Go type names *)
let go_type_tag_map = [
  "TBool",    "bool";
  "TInt64",   "int64";
  "TFloat64", "float64";
  "TString",  "string";
  "TAny",     "any";
  "TInt",     "int";
  "TInt32",   "int32";
  "TUint64",  "uint64";
]

let classify_go_type_tag r =
  List.assoc_opt (global_basename r) go_type_tag_map

(* IO monad — basename matching is acceptable here because these names
   live in builtins.v and user theories should not shadow them. *)
let is_IO_type  r = String.equal (global_basename r) "IO"
let is_ret_ref  r = String.equal (global_basename r) "ret"
let is_bind_ref r = String.equal (global_basename r) "bind"

(* existT is the constructor of sigT — used by the [any] notation. *)
let is_existT_ref r =
  ref_has_suffix r ".Init.Specif.existT" ||
  String.equal (global_basename r) "existT"

(* sigT / GoAny — map to Go's [any] type. *)
let is_sigT_ref r =
  ref_has_suffix r ".Init.Specif.sigT" ||
  String.equal (global_basename r) "sigT"

(*s Nat arithmetic operation recognition. *)

type nat_op = NatAdd | NatSub | NatMul | NatDiv | NatMod
            | NatEqb | NatLtb | NatLeb

let nat_op_names = [
  "add",     NatAdd;
  "sub",     NatSub;
  "mul",     NatMul;
  "div",     NatDiv;
  "modulo",  NatMod;
  "mod",     NatMod;
  "eqb",     NatEqb;
  "ltb",     NatLtb;
  "leb",     NatLeb;
]

let is_nat_op_ref r name =
  ref_has_suffix r (".Init.Nat." ^ name) ||
  ref_has_suffix r (".Arith.PeanoNat.Nat." ^ name)

let is_int63_op_ref r name =
  ref_has_suffix r (".PrimInt63." ^ name) ||
  ref_has_suffix r (".Cyclic.Int63.PrimInt63." ^ name)

let float_op_table = [
  "add", " + "; "sub", " - "; "mul", " * "; "div", " / ";
]

let is_float_op_ref r name =
  ref_has_suffix r (".PrimFloat." ^ name)

let classify_float_op r =
  List.find_map
    (fun (name, op) -> if is_float_op_ref r name then Some op else None)
    float_op_table

let classify_nat_op r =
  List.find_map
    (fun (name, op) -> if is_nat_op_ref r name then Some op else None)
    nat_op_names

let classify_int63_op r =
  List.find_map
    (fun (name, op) -> if is_int63_op_ref r name then Some op else None)
    nat_op_names  (* same infix table works for int63 *)

let go_infix = function
  | NatAdd -> " + " | NatSub -> " - " | NatMul -> " * "
  | NatDiv -> " / " | NatMod -> " % "
  | NatEqb -> " == " | NatLtb -> " < " | NatLeb -> " <= "

(*s Type printer. *)

let rec pp_type state = function
  | Tarr (t1, t2) ->
      str "func(" ++ pp_type state t1 ++ str ") " ++ pp_type state t2
  | Tglob (r, _)  when is_sigT_ref r -> str "any"
  (* IO A erases to A — the world token has no runtime representation *)
  | Tglob (r, [arg]) when is_IO_type r -> pp_type state arg
  (* GoMap K V → map[KT]VT *)
  | Tglob (r, [kt; vt]) when is_go_map_type r ->
      str "map[" ++ pp_type state kt ++ str "]" ++ pp_type state vt
  (* list GoRune = GoString — must come before the general slice case *)
  | Tglob (r, [Tglob (elem, [])]) when is_list_type r
    && String.equal (global_basename elem) "GoInt32" -> str "string"
  (* list A = GoSlice A → []T *)
  | Tglob (r, [arg]) when is_list_type r ->
      str "[]" ++ pp_type state arg
  | Tglob (r, []) when is_float64_type r  -> str "float64"
  | Tglob (r, []) when is_go_prim_type r -> str (Option.get (classify_go_prim_type r))
  | Tglob (r, []) when is_unit_type r   -> str "struct{}"
  | Tglob (r, []) when is_uint63_type r -> str "int64"
  | Tglob (r, []) when is_nat_type r    -> str "uint"
  | Tglob (r, []) when is_bool_type r   -> str "bool"
  | Tglob (r, args) ->
      str (go_export (global_basename r)) ++
      (if args = [] then mt ()
       else
         str "[" ++
         prlist_with_sep (fun () -> str ", ") (pp_type state) args ++
         str "]")
  | Tvar i | Tvar' i -> str ("T" ^ string_of_int i)
  | Tdummy _ | Tunknown | Taxiom | Tmeta _ -> str "any"

let rec collect_tarrs = function
  | Tarr (t, rest) -> let ts, ret = collect_tarrs rest in t :: ts, ret
  | t              -> [], t

let is_erased = function MLdummy _ -> true | _ -> false

(*s De Bruijn environment.

    [env] is the list of bound [ml_ident]s, innermost binder first.
    [MLrel 1] is the innermost (most-recently-bound) variable.

    In Rocq 9.x, [ml_ident] is a variant: [Dummy | Id of variable | Tmp of variable]. *)

let is_dummy = function Dummy -> true | _ -> false

let pp_mlident = function
  | Dummy   -> str "_"
  | Id v    -> str (go_safe (Id.to_string v))
  | Tmp v   -> str (go_safe (Id.to_string v))

let pp_rel env i =
  try pp_mlident (List.nth env (i - 1))
  with Not_found -> str ("_db" ^ string_of_int i)

(*s Collect nested lambdas into a flat parameter list. *)

let collect_lam body =
  let rec go acc = function
    | MLlam (id, body) -> go (id :: acc) body
    | body             -> List.rev acc, body
  in
  go [] body

(*s Flatten nested applications. *)

let collect_app head args =
  let rec go acc = function
    | MLapp (h, more) -> go (more @ acc) h
    | h               -> h, acc
  in
  go args head

(*s Unfold a Rocq list literal (MLcons-based) to an OCaml list, or None. *)

let rec unfold_list acc = function
  | MLcons (_, r, [x; rest]) when is_list_cons r -> unfold_list (x :: acc) rest
  | MLcons (_, r, [])        when is_list_nil r  -> Some (List.rev acc)
  | _ -> None


(*s Fold a Peano nat literal to an integer, or return None. *)

let rec nat_value = function
  | MLcons (_, r, [])  when is_nat_zero r -> Some 0
  | MLcons (_, r, [n]) when is_nat_succ r ->
      (match nat_value n with Some v -> Some (v + 1) | None -> None)
  | _ -> None

(*s Expression printer. *)

let rec pp_expr state env = function
  | MLrel i ->
      pp_rel env i

  | MLapp (head, args) ->
      let head, all_args = collect_app head args in
      let vis = List.filter (fun a -> not (is_erased a)) all_args in
      (match head, vis with
       (* ret x → x (identity: IO wrapper erases) *)
       | MLglob r, [x] when is_ret_ref r -> pp_expr state env x

       (* type_assert tag v → v.(T) where T is read from the tag constructor *)
       | MLglob r, [tag; v] when is_type_assert_ref r ->
           let go_type =
             match tag with
             | MLcons (_, r2, _) ->
                 (match classify_go_type_tag r2 with
                  | Some t -> t
                  | None   -> "any")
             | _ -> "any"
           in
           let inner =
             match v with
             | MLcons (_, r2, [x])    when is_existT_ref r2 -> pp_expr state env x
             | MLcons (_, r2, [_; x]) when is_existT_ref r2 -> pp_expr state env x
             | _ -> pp_expr state env v
           in
           inner ++ str ".(" ++ str go_type ++ str ")"

       (* panic(val) *)
       | MLglob r, [x] when is_panic_ref r ->
           let pp_pa e =
             match e with
             | MLcons (_, r2, [v])    when is_existT_ref r2 -> pp_expr state env v
             | MLcons (_, r2, [_; v]) when is_existT_ref r2 -> pp_expr state env v
             | _ -> pp_expr state env e
           in
           str "panic(" ++ pp_pa x ++ str ")"

       (* slice_of_list tag list → []T{v1, v2, ...} *)
       | MLglob r, [tag; lst] when is_slice_of_list_ref r ->
           let go_elem = match tag with
             | MLcons (_, r2, _) ->
                 (match classify_go_type_tag r2 with Some t -> t | None -> "any")
             | _ -> "any"
           in
           (match unfold_list [] lst with
            | Some elems ->
                str ("[]" ^ go_elem ^ "{") ++
                prlist_with_sep (fun () -> str ", ") (pp_expr state env) elems ++
                str "}"
            | None -> str ("[]" ^ go_elem ^ "(nil)"))

       (* slice_get tag xs i → xs[i] — panics if out of bounds *)
       | MLglob r, [_tag; xs; i] when is_slice_get_ref r ->
           pp_expr state env xs ++ str "[" ++ pp_expr state env i ++ str "]"

       (* map_make_typed kt vt → make(map[K]V) with concrete types from tags *)
       | MLglob r, [kt; vt] when is_map_make_typed_ref r ->
           let tag_to_go tag =
             match tag with
             | MLcons (_, r2, _) ->
                 (match classify_go_type_tag r2 with Some t -> t | None -> "any")
             | _ -> "any"
           in
           str ("make(map[" ^ tag_to_go kt ^ "]" ^ tag_to_go vt ^ ")")

       (* map_get_or: handled in pp_stmts/MLletin for clean two-statement emission *)

       (* map operations *)
       | MLglob r, [k; v; m] when is_map_set_ref r ->
           pp_expr state env m ++ str "[" ++ pp_expr state env k ++ str "] = " ++
           pp_expr state env v
       | MLglob r, [k; m]    when is_map_del_ref r ->
           str "delete(" ++ pp_expr state env m ++ str ", " ++ pp_expr state env k ++ str ")"
       | MLglob r, [m]       when is_map_len_ref r ->
           str "len(" ++ pp_expr state env m ++ str ")"
       | MLglob r, []        when is_map_make_ref r ->
           str "make(map[any]any)" (* type params erased; real type comes from context *)

       (* len(slice) / cap(slice) *)
       | MLglob r, [s] when is_len_ref r ->
           str "len(" ++ pp_expr state env s ++ str ")"
       | MLglob r, [s] when is_cap_ref r ->
           str "cap(" ++ pp_expr state env s ++ str ")"
       (* append(xs, ys) *)
       | MLglob r, [xs; ys] when is_append_ref r ->
           str "append(" ++ pp_expr state env xs ++ str ", " ++
           pp_expr state env ys ++ str "...)"

       (* print/println(list GoAny) — unfold list, strip existT wrappers *)
       | MLglob r, [lst] when is_print_ref r || is_println_ref r ->
           let fname = global_basename r in
           let pp_pa e =
             match e with
             | MLcons (_, r, [v])    when is_existT_ref r -> pp_expr state env v
             | MLcons (_, r, [_; v]) when is_existT_ref r -> pp_expr state env v
             | _ -> pp_expr state env e
           in
           (match unfold_list [] lst with
            | Some pargs ->
                str (fname ^ "(") ++
                prlist_with_sep (fun () -> str ", ") pp_pa pargs ++
                str ")"
            | None ->
                str (fname ^ "(/* dynamic list */)"))
       (* Inlined float64 binary operation *)
       | MLglob r, [a; b] when Option.has_some (classify_float_op r) ->
           let op = Option.get (classify_float_op r) in
           pp_atom state env a ++ str op ++ pp_atom state env b
       (* Inlined nat / int63 binary operation *)
       | MLglob r, [a; b] when Option.has_some (classify_nat_op r) ->
           let op = go_infix (Option.get (classify_nat_op r)) in
           pp_atom state env a ++ str op ++ pp_atom state env b
       | MLglob r, [a; b] when Option.has_some (classify_int63_op r) ->
           let op = go_infix (Option.get (classify_int63_op r)) in
           pp_atom state env a ++ str op ++ pp_atom state env b
       | _ ->
           pp_atom state env head ++ str "(" ++
           prlist_with_sep (fun () -> str ", ")
             (pp_expr state env) vis ++
           str ")")

  | MLlam _ as e ->
      let ids, body = collect_lam e in
      let vis = List.filter (fun id -> not (is_dummy id)) ids in
      let new_env = List.rev ids @ env in
      str "func(" ++
      prlist_with_sep (fun () -> str ", ")
        (fun id -> pp_mlident id ++ str " any") vis ++
      str ") any {" ++ fnl () ++
      str "\treturn " ++ pp_expr state new_env body ++ fnl () ++
      str "}"

  | MLglob r ->
      if is_bool_true r     then str "true"
      else if is_bool_false r then str "false"
      else if is_map_make_ref r || is_map_make_typed_ref r then str "make(map[any]any)"
      else str (go_export (global_basename r))

  | MLfix (i, names, _) ->
      str (go_export (go_safe (Id.to_string names.(i))))

  | MLletin (id, e1, e2) ->
      let new_env = id :: env in
      str "(func() any {" ++ fnl () ++
      str "\t" ++ pp_mlident id ++ str " := " ++ pp_expr state env e1 ++ fnl () ++
      str "\treturn " ++ pp_expr state new_env e2 ++ fnl () ++
      str "})()"

  | MLcons _ as e ->
      (match nat_value e with
       | Some n -> str (string_of_int n)
       | None   ->
           match e with
           | MLcons (_, r, []) when is_unit_tt r    -> mt ()
           | MLcons (_, r, []) when is_bool_true r  -> str "true"
           | MLcons (_, r, []) when is_bool_false r -> str "false"
           | MLcons (_, r, []) when is_list_nil r   -> str "nil"
           | MLcons _ as lst ->
               (* Non-empty list literal: emit as append(nil, v1, v2, ...).
                  Go infers the slice element type from the values. *)
               (match unfold_list [] lst with
                | Some elems ->
                    str "append(nil, " ++
                    prlist_with_sep (fun () -> str ", ")
                      (pp_expr state env) elems ++
                    str ")"
                | None -> str "nil /* dynamic list */")
           | _ -> str "nil /* unhandled constructor */")

  | MLmagic e -> pp_expr state env e
  | MLdummy _ -> str "_"
  | MLfloat f ->
      let s = Float64.to_string f in
      (* Ensure Go sees a float literal: add .0 if no decimal or exponent. *)
      let s = if String.contains s '.' || String.contains s 'e'
                 || String.contains s 'E' || String.contains s 'n'
              then s else s ^ ".0" in
      str s
  | MLexn s   -> str ("panic(" ^ Printf.sprintf "%S" s ^ ")")
  | MLaxiom s -> str ("panic(\"axiom: " ^ String.escaped s ^ "\")")
  | MLuint n  -> str (Uint63.to_string n)
  | _         -> str "nil /* TODO */"

and pp_atom state env e =
  match e with
  | MLrel _ | MLglob _ | MLcons _ | MLuint _ | MLfloat _ | MLmagic _ ->
      pp_expr state env e
  | _ ->
      str "(" ++ pp_expr state env e ++ str ")"

(*s Check whether MLrel 1 appears free in an expression.
    Used to detect unused bind parameters (the result is discarded). *)

let rec db1_free = function
  | MLrel 1             -> false
  | MLrel _ | MLglob _ | MLuint _ | MLfloat _ | MLdummy _ | MLaxiom _ | MLexn _ -> true
  | MLapp (h, args)     -> db1_free h && List.for_all db1_free args
  | MLlam (_, b)        -> db1_free b   (* conservative: may over-suppress inside nested lam *)
  | MLcons (_, _, args) -> List.for_all db1_free args
  | MLletin (_, e1, e2) -> db1_free e1 && db1_free e2
  | MLmagic e           -> db1_free e
  | _                   -> true

(*s IO body emitter — shared by pp_function (for IO-returning fns) and pp_main_body. *)

let pp_io_body state tab env body =
  let is_void_call e =
    match collect_app e [] with
    | MLglob r, _ when is_print_ref r || is_println_ref r || is_panic_ref r -> true
    | MLglob r, _ when is_map_set_ref r || is_map_del_ref r -> true
    | _ -> false
  in
  let is_terminating e =
    match collect_app e [] with
    | MLglob r, _ when is_panic_ref r -> true
    | _ -> false
  in
  let rec pp_stmts tab env = function
    | MLapp _ as e ->
        let head, all_args = collect_app e [] in
        let vis = List.filter (fun a -> not (is_erased a)) all_args in
        (match head, vis with
         | MLglob r, [m; f] when is_bind_ref r ->
             let ids, body = collect_lam f in
             let new_env = List.rev ids @ env in
             let vis_ids = List.filter (fun id -> not (is_dummy id)) ids in
             let lhs = match vis_ids with
               | _ when is_void_call m   -> mt ()
               | _ when db1_free body    ->
                   (* If the head is a known value-returning builtin (slice_get,
                      type_assert, etc.), discard with _ =.
                      User-defined functions have unknown return — assume void. *)
                   let head_m, _ = collect_app m [] in
                   (match head_m with
                    | MLglob r when is_slice_get_ref r || is_type_assert_ref r
                                 || is_map_len_ref r || is_map_get_or_ref r
                                 || is_len_ref r || is_cap_ref r
                                 || Option.has_some (classify_nat_op r)
                                 || Option.has_some (classify_int63_op r)
                                 || Option.has_some (classify_float_op r) -> str "_ = "
                    | _                              -> mt ())
               | [id]                    -> pp_mlident id ++ str " := "
               | _                       -> mt ()
             in
             (* Bare MLglob in statement position is a zero-arg IO function
                call — needs () in Go.  Builtins handle their own emission. *)
             let emit_m =
               match m with
               | MLglob r when not (is_bool_true r || is_bool_false r
                                    || is_unit_tt r || is_map_make_ref r) ->
                   pp_expr state env m ++ str "()"
               | _ -> pp_expr state env m
             in
             str tab ++ lhs ++ emit_m ++ fnl () ++
             (if is_terminating m then mt ()
              else pp_stmts tab new_env body)
         | MLglob r, [_] when is_ret_ref r -> mt ()
         | MLglob r, [m; h] when String.equal (global_basename r) "catch" ->
             let ids, h_body = collect_lam h in
             let new_env = List.rev ids @ env in
             let p_id = match List.filter (fun id -> not (is_dummy id)) ids with
               | [id] -> pp_mlident id
               | _    -> str "_p"
             in
             let t = str tab in
             t ++ str "func() {" ++ fnl () ++
             t ++ str "\tdefer func() {" ++ fnl () ++
             t ++ str "\t\tif " ++ p_id ++ str " := recover(); " ++ p_id ++ str " != nil {" ++ fnl () ++
             pp_stmts (tab ^ "\t\t\t") new_env h_body ++
             t ++ str "\t\t}" ++ fnl () ++
             t ++ str "\t}()" ++ fnl () ++
             pp_stmts (tab ^ "\t") env m ++
             t ++ str "}()" ++ fnl ()
         | _ ->
             str tab ++ pp_expr state env e ++ fnl ())
    | MLletin (id, e1, e2) ->
        let new_env = id :: env in
        (* map_get_or k default m → two-statement pattern: no IIFE *)
        let head1, all_args1 = collect_app e1 [] in
        let vis1 = List.filter (fun a -> not (is_erased a)) all_args1 in
        (match head1, vis1 with
         | MLglob r, [k; def; m] when is_map_get_or_ref r && not (is_dummy id) ->
             let lhs = pp_mlident id in
             let pp_def d = match d with
               | MLuint _ -> str "int64(" ++ pp_expr state env d ++ str ")"
               | MLfloat _ -> str "float64(" ++ pp_expr state env d ++ str ")"
               | _ -> pp_expr state env d
             in
             str tab ++ str "var " ++ lhs ++ str " any = " ++ pp_def def ++ fnl () ++
             str tab ++ str "if _v, _ok := " ++ pp_expr state env m ++
             str "[" ++ pp_expr state env k ++ str "]; _ok {" ++ fnl () ++
             str tab ++ str "\t" ++ lhs ++ str " = _v" ++ fnl () ++
             str tab ++ str "}" ++ fnl () ++
             pp_stmts tab new_env e2
         | _ ->
             let lhs = if is_dummy id || is_void_call e1 then mt ()
                       else pp_mlident id ++ str " := " in
             str tab ++ lhs ++ pp_expr state env e1 ++ fnl () ++
             pp_stmts tab new_env e2)
    | MLcons (_, r, []) when is_unit_tt r -> mt ()
    | e ->
        str tab ++ pp_expr state env e ++ fnl ()
  in
  let rec peel_catches tab env b =
    let head, all_args = collect_app b [] in
    let vis = List.filter (fun a -> not (is_erased a)) all_args in
    match head, vis with
    | MLglob r, [m; h] when String.equal (global_basename r) "catch" ->
        let ids, h_body = collect_lam h in
        let new_env = List.rev ids @ env in
        let p_id = match List.filter (fun id -> not (is_dummy id)) ids with
          | [id] -> pp_mlident id
          | _    -> str "_p"
        in
        let t = str tab in
        t ++ str "defer func() {" ++ fnl () ++
        t ++ str "\tif " ++ p_id ++ str " := recover(); " ++ p_id ++ str " != nil {" ++ fnl () ++
        pp_stmts (tab ^ "\t\t") new_env h_body ++
        t ++ str "\t}" ++ fnl () ++
        t ++ str "}()" ++ fnl () ++
        peel_catches tab env m
    | _ -> pp_stmts tab env b
  in
  peel_catches tab env body

(*s Declaration printer. *)

(** Emit a top-level function, collecting leading lambdas for the signature
    and using [typ] for parameter/return type annotations. *)
let pp_function state name body typ =
  let ids, inner_body = collect_lam body in
  let param_types, ret_type = collect_tarrs typ in
  (* Pair visible ids with their corresponding types, skipping erased args. *)
  let rec zip_params ids types =
    match ids, types with
    | [], _              -> []
    | id :: rest, _ when is_dummy id ->
        let rest_types = (match types with _ :: t -> t | [] -> []) in
        zip_params rest rest_types
    | id :: rest, t :: rest_types -> (id, t) :: zip_params rest rest_types
    | id :: rest, []              -> (id, Tunknown) :: zip_params rest []
  in
  let param_pairs = zip_params ids param_types in
  (* env includes all ids (with dummies) for de Bruijn; innermost first. *)
  let full_env = List.rev ids in
  let fn_sig =
    str "func " ++ str (go_export name) ++ str "(" ++
    prlist_with_sep (fun () -> str ", ")
      (fun (id, t) -> pp_mlident id ++ str " " ++ pp_type state t)
      param_pairs
  in
  (* IO-returning functions use pp_io_body; pure functions use return+expr *)
  match ret_type with
  | Tglob (r, [inner]) when is_IO_type r ->
      let go_ret = match inner with
        | Tglob (r2, []) when is_unit_type r2 -> mt ()   (* IO unit → void *)
        | t -> str " " ++ pp_type state t
      in
      fn_sig ++ str ")" ++ go_ret ++ str " {" ++ fnl () ++
      pp_io_body state "\t" full_env inner_body ++
      str "}" ++ fnl ()
  | _ ->
      fn_sig ++ str ") " ++ pp_type state ret_type ++ str " {" ++ fnl () ++
      str "\treturn " ++ pp_expr state full_env inner_body ++ fnl () ++
      str "}" ++ fnl ()

(*s Stdlib terms that are inlined at call sites — skip as top-level decls. *)

let is_inlined_ref r =
  is_nat_zero r || is_nat_succ r ||
  is_bool_true r || is_bool_false r ||
  is_print_ref r || is_println_ref r ||
  is_len_ref r || is_cap_ref r || is_append_ref r || is_panic_ref r ||
  is_type_assert_ref r || Option.has_some (classify_go_type_tag r) ||
  is_slice_of_list_ref r || is_slice_get_ref r ||
  is_go_map_type r || is_map_make_ref r || is_map_make_typed_ref r ||
  is_map_set_ref r || is_map_del_ref r || is_map_len_ref r || is_map_get_or_ref r ||
  is_IO_type r || is_ret_ref r || is_bind_ref r ||
  String.equal (global_basename r) "catch" ||
  String.equal (global_basename r) "with_defer" ||
  is_unit_tt r ||
  is_go_prim_type r || is_float64_type r ||
  List.exists (fun (name, _) -> is_float_op_ref r name) float_op_table ||
  is_existT_ref r || is_sigT_ref r ||
  List.exists (fun (name, _) -> is_nat_op_ref r name) nat_op_names ||
  List.exists (fun (name, _) -> is_int63_op_ref r name) nat_op_names

(*s Main-package wrapper. *)

(** Emit [func main() { _ = EntryFn() }] for the given entry-point name. *)
let pp_main_call fn_name =
  fnl () ++
  str "func main() {" ++ fnl () ++
  str ("\t" ^ go_export fn_name ^ "()") ++ fnl () ++
  str "}" ++ fnl ()

(** Emit [func main()] with the entry body inlined directly. *)
(** Emit [func main()] body as flat sequential statements.
    [MLletin] chains become [x := rhs] assignments rather than IIFEs. *)
(** Emit the body of any IO-returning function as flat sequential statements.
    Used by both [pp_main_body] and [pp_function] for IO-typed functions. *)
let pp_main_body state body =
  str "func main() {" ++ fnl () ++
  pp_io_body state "\t" [] body ++
  str "}" ++ fnl ()

(*s Declaration printer. *)

let pp_decl state decl =
  match decl with
  | Dterm (r, _, _) when is_inlined_ref r ->
      mt ()

  | Dterm (r, body, typ) ->
      let name = global_basename r in
      (match body with
       | MLlam _ ->
           pp_function state name body typ ++ fnl ()
       | _ ->
           match typ with
           | Tglob (r, []) when is_unit_type r ->
               str "func " ++ str (go_export name) ++ str "() {" ++ fnl () ++
               str "\t" ++ pp_expr state [] body ++ fnl () ++
               str "}" ++ fnl () ++ fnl ()
           | Tglob (r, [inner]) when is_IO_type r ->
               let go_ret = match inner with
                 | Tglob (r2, []) when is_unit_type r2 -> mt ()
                 | t -> str " " ++ pp_type state t
               in
               str "func " ++ str (go_export name) ++ str "()" ++ go_ret ++ str " {" ++ fnl () ++
               pp_io_body state "\t" [] body ++
               str "}" ++ fnl () ++ fnl ()
           | _ ->
               str "var " ++ str (go_export name) ++ str " " ++
               pp_type state typ ++ str " = " ++
               pp_expr state [] body ++ fnl () ++ fnl ())

  | Dfix (refs, bodies, types) ->
      if Array.exists is_inlined_ref refs then mt ()
      else
        prvecti
          (fun i _ -> pp_function state (global_basename refs.(i)) bodies.(i) types.(i))
          refs

  | Dind _ ->
      (* nat and bool are treated as builtins; other inductives are TODO *)
      mt ()

  | Dtype (r, _, _) when is_uint63_type r || is_go_prim_type r || is_float64_type r
    || is_IO_type r || is_go_map_type r
    || String.equal (global_basename r) "GoString"
    || String.equal (global_basename r) "GoSlice" -> mt ()
  | Dtype (_, _, Tglob (r, _)) when is_sigT_ref r    -> mt ()

  | Dtype (r, _, typ) ->
      str "type " ++ str (go_export (global_basename r)) ++
      str " = " ++ pp_type state typ ++ fnl ()

(*s Structure printer. *)

let pp_struct state struc =
  let pp_mod (mp, sel) =
    State.with_visibility state mp [] (fun state ->
      prlist
        (fun (_, elem) ->
           match elem with
           | SEdecl d      -> pp_decl state d
           | SEmodule _
           | SEmodtype _   -> mt ())
        sel)
  in
  prlist pp_mod struc

(*s Language descriptor. *)

let go_descr : Common.State.t language_descr = {
  keywords;
  file_suffix  = ".go";
  file_naming;
  preamble;
  pp_struct;
  sig_suffix   = None;
  sig_preamble;
  pp_sig;
  pp_decl;
}
