(* The one assumptions gate: the sole Print Assumptions target, compiled fresh against the built .vo. *)
From Fido Require Import Integer Float Complex FilePath Collections ModulePath Version Syntax Index Typing Compilable Safe Render Emit.

Print Assumptions Integer.equalb_spec.
Print Assumptions Integer.representableb_spec.
Print Assumptions Integer.int_bits_64.
Print Assumptions Integer.uint_bits_64.
Print Assumptions Integer.minimum_representable.
Print Assumptions Integer.maximum_representable.
Print Assumptions Integer.minimum_pred_not_representable.
Print Assumptions Integer.maximum_succ_not_representable.
Print Assumptions Integer.int_neq_int64.
Print Assumptions Integer.uint_neq_uint64.
Print Assumptions Integer.platform_minimum_val.
Print Assumptions Integer.platform_maximum_val.
Print Assumptions Integer.platform_unsigned_maximum_val.

Print Assumptions Float.kind_equalb_spec.
Print Assumptions Float.precision_f32.
Print Assumptions Float.precision_f64.
Print Assumptions Float.maximum_exponent_f32.
Print Assumptions Float.maximum_exponent_f64.
Print Assumptions Float.constant_canonical_intrinsic.
Print Assumptions Float.numerator_denominator_eq.
Print Assumptions Float.constant_equalb_eq.
Print Assumptions Float.constant_equalb_spec.
Print Assumptions Float.constant_of_Z_canonical.
Print Assumptions Float.reduce_constant_canonical.
Print Assumptions Float.reduce_constant_eq.
Print Assumptions Float.constant_canonical_unique.
Print Assumptions Float.representableb_spec.
Print Assumptions Float.decimal_equalb_spec.
Print Assumptions Float.decimal_value_canonical.
Print Assumptions Float.decimal_value_zero.
Print Assumptions Float.decimal_zero_unique.
Print Assumptions Float.round_ieee_zero.
Print Assumptions Typing.convert_constant_same_int.
Print Assumptions Typing.typed_int_value.
Print Assumptions Float.typed_runtime_not_neg_zero.
Print Assumptions Float.typed_runtime_not_nan.
Print Assumptions Float.typed_runtime_not_inf.
Print Assumptions Float.round_typed_float_representable.
Print Assumptions Float.round_constant_typed.
Print Assumptions Typing.convert_constant_same_float.
Print Assumptions Typing.typed_exact.
Print Assumptions Safe.typed_constant_to_value_type.
Print Assumptions Safe.typed_constant_to_value_well_formed.
Print Assumptions Safe.typed_constant_to_value_float.
Print Assumptions Safe.eval_expr_denotes.
Print Assumptions Safe.value_denotes_constant_runtime.
Print Assumptions Safe.float_nonconstant_no_denotes.

Print Assumptions Complex.kind_equalb_spec.
Print Assumptions Complex.component_c64.
Print Assumptions Complex.component_c128.
Print Assumptions Complex.constant_equalb_spec.
Print Assumptions Complex.decimal_value_real.
Print Assumptions Complex.decimal_value_imaginary.
Print Assumptions Complex.round_typed_components.
Print Assumptions Complex.round_typed_real_none.
Print Assumptions Complex.round_typed_imaginary_none.
Print Assumptions Complex.representableb_spec.
Print Assumptions Complex.typed_runtime_real_coherent.
Print Assumptions Complex.typed_runtime_real_shape.
Print Assumptions Complex.typed_runtime_imaginary_shape.
Print Assumptions Complex.typed_runtime_real_not_neg_zero.
Print Assumptions Complex.typed_runtime_real_not_nan.
Print Assumptions Complex.typed_runtime_real_not_inf.

Print Assumptions FilePath.equalb_spec.

Print Assumptions ModulePath.equalb_spec.

Print Assumptions Version.render_go1_23.
Print Assumptions Version.equalb_spec.

Print Assumptions Collections.file_path_text_inj.
Print Assumptions Collections.file_elements_equal.

Print Assumptions Typing.constant_info_zero_sign.
Print Assumptions Typing.constant_representableb_iff.
Print Assumptions Typing.resolve_sound.
Print Assumptions Typing.resolve_complete.
Print Assumptions Typing.resolve_deterministic.
Print Assumptions Typing.stmt_typedb_iff.
Print Assumptions Typing.program_typedb_iff.
Print Assumptions Typing.program_equal.
Print Assumptions Typing.program_typedb_equal.
Print Assumptions Typing.program_typedb_build_permutation.
Print Assumptions Compilable.occurrences_file_typedb_eq.
Print Assumptions Typing.constant_info_step_reflect.
Print Assumptions Typing.string_representable.
Print Assumptions Typing.string_representableb.
Print Assumptions Typing.convert_constant_same_complex.
Print Assumptions Typing.convert_complex_reuses_float_component.
Print Assumptions Typing.convert_float_reuses_complex_component.
Print Assumptions Typing.type_untyped_int_convert.
Print Assumptions Typing.type_untyped_float_convert.
Print Assumptions Typing.type_untyped_complex_convert.

Print Assumptions Syntax.files_of_nodes_success_iff_unique.
Print Assumptions Syntax.files_of_nodes_none_iff_duplicate.
Print Assumptions Syntax.files_of_nodes_in.
Print Assumptions Syntax.files_of_nodes_maps_to.
Print Assumptions Syntax.files_of_nodes_mapsto_source.
Print Assumptions Syntax.files_of_nodes_find.
Print Assumptions Syntax.files_of_nodes_duplicate_rejects.
Print Assumptions Syntax.files_of_nodes_duplicate_different_source_rejects.
Print Assumptions Syntax.files_of_nodes_permutation.
Print Assumptions Syntax.build_program_some_iff_unique.
Print Assumptions Syntax.files_equal_refl.
Print Assumptions Syntax.files_equal_sym.
Print Assumptions Syntax.files_equal_trans.

Print Assumptions Compilable.semantic_ok_b_source_program_valid.
Print Assumptions Compilable.compile_ok_valid.
Print Assumptions Compilable.compile_complete.
Print Assumptions Compilable.compilable_retains_phase.
Print Assumptions Compilable.compilable_retains_expr_facts.
Print Assumptions Compilable.compilable_retains_tnfacts.
Print Assumptions Compilable.program_of_admissible.
Print Assumptions Compilable.capability_source.
Print Assumptions Compilable.capability_is_compile_outcome.
Print Assumptions Compilable.compile_rejected_not_admissible.
Print Assumptions Emit.Mint.Token.
Print Assumptions Emit.Mint.issue.
Print Assumptions Emit.Mint.module_exact.
Print Assumptions Emit.Mint.files_exact.
Print Assumptions Emit.Image.
Print Assumptions Emit.safe.
Print Assumptions Emit.origin.
Print Assumptions Emit.module_bytes_exact.
Print Assumptions Emit.files_are_exact.
Print Assumptions Emit.provenance.
Print Assumptions Emit.of_safe.
Print Assumptions Emit.of_safe_retains.
Print Assumptions Emit.of_safe_module_bytes.
Print Assumptions Emit.of_safe_files.
Print Assumptions Emit.of_safe_at.
Print Assumptions Emit.of_safe_at_retains.
Print Assumptions Emit.of_safe_at_module_bytes.
Print Assumptions Emit.of_safe_at_files.
Print Assumptions Emit.of_safe_at_refl.
Print Assumptions Emit.of_safe_at_transport.
Print Assumptions Emit.accepted_path_emits_from_returned_capability.
Print Assumptions Emit.deep_nested_emit_fixture.
Print Assumptions Compilable.file_in_package.
Print Assumptions Compilable.package_no_empty.
Print Assumptions Compilable.package_summary_main_count.
Print Assumptions Compilable.package_summaries_empty.
Print Assumptions Compilable.package_summaries_equal.
Print Assumptions Compilable.package_summaries_build_permutation.
Print Assumptions Compilable.source_program_valid_files_equal.
Print Assumptions Compilable.reject_no_compile.
Print Assumptions Compilable.compilable_program_typed.
Print Assumptions Compilable.source_program_valid_empty.
Print Assumptions Compilable.package_ref_present.
Print Assumptions Compilable.package_ref_key_inj.
Print Assumptions Compilable.package_ref_of_binding_key.
Print Assumptions Compilable.package_ref_of_fileref_key.
Print Assumptions Compilable.diagnostic_code_primary_consistent.
Print Assumptions Compilable.occurrence_expr_diags_conv_sound.
Print Assumptions Compilable.occurrence_expr_diags_default_sound.
Print Assumptions Compilable.annotate_program_ctx_sound.
Print Assumptions Compilable.annotate_program_ctx_wf.
Print Assumptions Compilable.expression_diags_conversion_single_rounding_sound.
Print Assumptions Compilable.expression_diags_conversion_single_rounding_well_formed.
Print Assumptions Compilable.package_diag_of_bucket_missing_sound.
Print Assumptions Compilable.package_diag_of_bucket_dup_sound.
Print Assumptions Compilable.package_diags_dup_sound.
Print Assumptions Compilable.package_diags_dup_precedence.
Print Assumptions Compilable.package_diags_missing_sound.
Print Assumptions Compilable.keyed_visit_files_equal.
Print Assumptions Compilable.annotate_encl_erased.
Print Assumptions Compilable.program_package_erased_find.
Print Assumptions Compilable.erased_expr_diags_source.
Print Assumptions Compilable.erased_pkg_diags_files_equal.
Print Assumptions Compilable.erased_report_files_equal.
Print Assumptions Compilable.erase_diagnostic_output.
Print Assumptions Compilable.erased_output_iff_build_output.
Print Assumptions Compilable.erased_fresh_report_of_sole.
Print Assumptions Compilable.erased_report_build_permutation.
Print Assumptions Compilable.program_expr_facts_enum_files_equal.
Print Assumptions Compilable.visit_file_key_nodup.
Print Assumptions Compilable.program_visit_key_nodup.
Print Assumptions Compilable.program_expr_facts_find.
Print Assumptions Compilable.program_expr_facts_eq_spec.
Print Assumptions Compilable.occurrences_file_operand.
Print Assumptions Compilable.input_visit_ok.
Print Assumptions Compilable.type_name_fact_at_table_resolves.
Print Assumptions Compilable.build_type_name_map.
Print Assumptions Compilable.forest_items_exact.
Print Assumptions Compilable.forest_reverse.
Print Assumptions Compilable.forest_forward.
Print Assumptions Compilable.forest_keys_nodup.
Print Assumptions Compilable.forest_operand_in_tail.
Print Assumptions Compilable.work_index_map.
Print Assumptions Compilable.work_index_fresh.
Print Assumptions Compilable.work_index_add_fresh.
Print Assumptions Compilable.work_index_exact.
Print Assumptions Compilable.build_work_index.
Print Assumptions Compilable.forest_index.
Print Assumptions Compilable.index_exact.
Print Assumptions Compilable.index_domain.
Print Assumptions Compilable.index_key_inj.
Print Assumptions Compilable.forest_key_inj.
Print Assumptions Compilable.index_member_at.
Print Assumptions Compilable.index_member_at_retained.
Print Assumptions Compilable.index_no_foreign.
Print Assumptions Compilable.index_nonexpr_absent.
Print Assumptions Compilable.forest_index_member_at.
Print Assumptions Compilable.forest_index_member_at_retained.
Print Assumptions Compilable.forest_index_no_foreign.
Print Assumptions Compilable.build_conversion_work.
Print Assumptions Compilable.total_forest_outcome_cause.
Print Assumptions Compilable.final_operand_outcome.
Print Assumptions Compilable.retained_conversion_closure.
Print Assumptions Compilable.conversion_failure_cause_yields_step.
Print Assumptions Compilable.child_failure_cause_yields_member.
Print Assumptions Compilable.conversion_success_cause_yields_step.
Print Assumptions Compilable.build_outcome_trace.
Print Assumptions Compilable.trace_retained_cause.
Print Assumptions Compilable.trace_match.
Print Assumptions Compilable.build_conversion_step.
Print Assumptions Compilable.build_forest_outcome_table.
Print Assumptions Compilable.retained_convfail_diag.
Print Assumptions Compilable.outcome_trace_unique_step.
Print Assumptions Compilable.trace_currents_eq.
Print Assumptions Compilable.stepcause_matches.
Print Assumptions Compilable.total_forest_outcome_at_matches.
Print Assumptions Compilable.outcomes_present.
Print Assumptions Compilable.outcomes_domain_iff_forest.
Print Assumptions Compilable.outcomes_nonexpr_absent.
Print Assumptions Compilable.forest_facts_eq_spec.
Print Assumptions Compilable.forest_awork_diags_eq.
Print Assumptions Compilable.expression_diagnostics_eq_spec.
Print Assumptions Compilable.expression_diags_eq_spec.
Print Assumptions Compilable.build_annotated_work_forest.
Print Assumptions Compilable.annotated_align_eq.
Print Assumptions Compilable.annotated_forest_erased_source.
Print Assumptions Compilable.program_package_refs_present.
Print Assumptions Compilable.program_package_refs_bucket_len.
Print Assumptions Compilable.program_package_refs_singleton_on_success.
Print Assumptions Compilable.program_package_refs_belongs.
Print Assumptions Compilable.program_expr_facts_domain.
Print Assumptions Compilable.package_singleton.
Print Assumptions Compilable.expression_ref_fact_some.
Print Assumptions Compilable.expression_fact_at_find.
Print Assumptions Compilable.type_name_ref_fact_some.
Print Assumptions Compilable.type_name_fact_at_find.
Print Assumptions Compilable.type_name_fact_at_resolves.
Print Assumptions Compilable.tnfact_byte_uint8_same_type.
Print Assumptions Compilable.tnfact_rune_int32_same_type.
Print Assumptions Compilable.tsyn_byte_neq_uint8.
Print Assumptions Compilable.tsyn_rune_neq_int32.
Print Assumptions Compilable.predeclared_all_sixteen.
Print Assumptions Compilable.conversion_target_ref_conv.
Print Assumptions Compilable.conversion_operand_ref_conv.
Print Assumptions Compilable.facts_and_diags_share_phase.
Print Assumptions Compilable.core_seals_tnfacts.
Print Assumptions Compilable.expression_facts_is_facts.
Print Assumptions Compilable.erased_is_diagnostics.
Print Assumptions Compilable.phase_ot_consumes_work.
Print Assumptions Compilable.phase_awork_consumes_work.
Print Assumptions Compilable.phase_fact_table_consumes_work_outcomes.
Print Assumptions Compilable.phase_diag_consumes_awork_ot.
Print Assumptions Compilable.core_seals_facts.
Print Assumptions Compilable.repeated_name_distinct_refs.
Print Assumptions Compilable.two_uint8_distinct_target_refs.
Print Assumptions Compilable.deep_nested_compiles.
Print Assumptions Compilable.deep_nested_no_diags.
Print Assumptions Compilable.deep_fail_one_diag.
Print Assumptions Compilable.deep_nested_phase_no_diags.
Print Assumptions Compilable.deep_fail_phase_reports.
Print Assumptions Compilable.deep_fail_innermost_convfail.
Print Assumptions Compilable.deep_fail_outer_childfail.
Print Assumptions Compilable.deep_fail_exactly_one_diag.
Print Assumptions Compilable.deep_nested_all_ok.
Print Assumptions Compilable.over_program_failure_retains_rejected_core.
Print Assumptions Compilable.deep_nested_compile_fixture.
Print Assumptions Compilable.twin_capability_retains_distinct_occurrences.
Print Assumptions Compilable.deep_fail_compile_fixture.
Print Assumptions Compilable.forest_count_source.
Print Assumptions Compilable.member_at_in_forest.
Print Assumptions Compilable.core_prop_at_source.
Print Assumptions Compilable.core_refs_fold_own_visit.
Print Assumptions Compilable.core_raw_diagnostics_consume_retained_refs.
Print Assumptions Compilable.admissible_dec.
Print Assumptions Compilable.compile_rejected_of_inadmissible.
Print Assumptions Compilable.forest_count_source.
Print Assumptions Compilable.core_work_count_source.
Print Assumptions Compilable.member_at_in_forest.
Print Assumptions Compilable.twin_distinct_in_forest.
Print Assumptions Compilable.accepted_package_refs_are_decision_refs.
Print Assumptions Compilable.rejected_package_refs_are_decision_refs.
Print Assumptions Compilable.package_bucket_diagnostics_from_refs.
Print Assumptions Compilable.core_package_diags_canonical.
Print Assumptions Compilable.core_package_refs_canonical.
Print Assumptions Compilable.core_plan_is_fresh_build_plan.
Print Assumptions Compilable.core_raw_semantic.
Print Assumptions Compilable.core_diagnostics_eq_elaboration.
Print Assumptions Compilable.failure_diagnostics.
Print Assumptions Compilable.failure_core.
Print Assumptions Compilable.core_input.
Print Assumptions Compilable.phase.
Print Assumptions Compilable.core_package_refs_from_visit.
Print Assumptions Compilable.core_layout_exact.
Print Assumptions Compilable.core_plan_exact.
Print Assumptions Compilable.core_raw_diagnostics_exact.
Print Assumptions Compilable.core_diagnostics_exact.
Print Assumptions Compilable.accepted.
Print Assumptions Compilable.rejected.
Print Assumptions Compilable.capability_of_admissible.
Print Assumptions Compilable.capability_source.
Print Assumptions Compilable.capability_is_compile_outcome.
Print Assumptions Compilable.failure_nonempty.
Print Assumptions Compilable.phase_domain_exact.
Print Assumptions Compilable.deep_nested_convsuccess_at.
Print Assumptions Compilable.deep_nested_chain_success_evidence.
Print Assumptions Compilable.accepted_conversion_at.
Print Assumptions Compilable.childfail_conversion_at.
Print Assumptions Compilable.deep_fail_innermost_diag.
Print Assumptions Compilable.deep_fail_childfail_at.
Print Assumptions Compilable.rejected_conversion_cause.
Print Assumptions Compilable.retained_convfail_cause.
Print Assumptions Compilable.childfail_conversion_cause.
Print Assumptions Compilable.retained_childfail_cause.
Print Assumptions Compilable.core_diagnostics_of_node_singleton.
Print Assumptions Compilable.accepted_conversion_cause.
Print Assumptions Compilable.retained_convsuccess_cause.
Print Assumptions Compilable.occurrence_expr_diags_conv_sound.
Print Assumptions Compilable.byte_uint8_erased_differ.
Print Assumptions Compilable.rune_int32_erased_differ.
Print Assumptions Compilable.expression_all_ok_program_typedb.
Print Assumptions Compilable.expression_all_ok_iff_typed_program.
Print Assumptions Compilable.emits_none_program_typedb.
Print Assumptions Compilable.expression_diags_empty_iff.
Print Assumptions Compilable.sum_main_file.
Print Assumptions Compilable.redecl_diags_empty_iff_rules.
Print Assumptions Compilable.missing_diags_empty_iff_rules.
Print Assumptions Compilable.package_diags_empty_iff_rules.
Print Assumptions Compilable.semantic_diagnostics_empty_iff.
Print Assumptions Compilable.elaboration_accepted_iff_admissible.
Print Assumptions Compilable.elaboration_rejected_iff_inadmissible.

Print Assumptions Compilable.current_package_rules_exactly_one.
Print Assumptions Compilable.source_spec_package_rules_b_package_rules_valid.
Print Assumptions Compilable.source_spec_valid_b_iff.
Print Assumptions Compilable.preflight_fails_iff.
Print Assumptions Compilable.semantic_diagnostics_empty_iff_source_valid.
Print Assumptions Compilable.fresh_build_diagnostics_nil_iff.
Print Assumptions Compilable.fresh_build_diagnostics_fail_singleton.
Print Assumptions Compilable.elaboration_diagnostics_nil_iff_admissible.
Print Assumptions Compilable.elaboration_diagnostics_eq_semantic.
Print Assumptions Compilable.elaboration_diagnostics_fresh_failure.
Print Assumptions Compilable.root_layout_input_equal.
Print Assumptions Compilable.fresh_build_plan_input_equal.
Print Assumptions Compilable.erased_elaboration_report_input_equal.
Print Assumptions Compilable.bucket_keys_eq_selected.
Print Assumptions Compilable.fresh_build_plan_of_buckets.
Print Assumptions Compilable.program_build_plan_retained.
Print Assumptions Compilable.program_root_layout_retained.
Print Assumptions Compilable.root_entry_key_neq_gomod.
Print Assumptions Compilable.root_entry_hval.
Print Assumptions Compilable.root_layout_dir_iff.
Print Assumptions Compilable.root_layout_gomod.
Print Assumptions Compilable.root_layout_gomod_iff.
Print Assumptions Compilable.root_layout_source_iff.
Print Assumptions Compilable.root_layout_domain.
Print Assumptions Compilable.selected_iff_file.
Print Assumptions Compilable.selected_key_is_parent.
Print Assumptions Compilable.package_import_path_nested.
Print Assumptions Compilable.package_import_path_inj.
Print Assumptions Compilable.package_import_path_deterministic.
Print Assumptions Compilable.default_exec_name_nonempty.
Print Assumptions Compilable.fresh_build_plan_exec_nonempty.
Print Assumptions Compilable.fresh_build_plan_zero.
Print Assumptions Compilable.fresh_build_plan_multiple.
Print Assumptions Compilable.fresh_build_plan_single_target.

Print Assumptions Safe.eval_zero_sign_agnostic.
Print Assumptions Safe.eval_expr_resolved.
Print Assumptions Safe.eval_expr_resolved_type.
Print Assumptions Safe.resolved_constant_value_float.
Print Assumptions Safe.eval_expr_resolved_value.
Print Assumptions Safe.eval_projects_stored_float_runtime.
Print Assumptions Safe.value_well_formedb_iff.
Print Assumptions Safe.typed_constant_to_value_denotes.
Print Assumptions Safe.eval_string_value.
Print Assumptions Safe.eval_string_resolved_type.
Print Assumptions Safe.typed_constant_to_value_complex.
Print Assumptions Safe.value_denotes_complex_runtime.
Print Assumptions Safe.eval_projects_stored_complex_runtime.
Print Assumptions Safe.certify_retains_capability.
Print Assumptions Safe.certify_retains_core.

Print Assumptions Render.file_ascii.
Print Assumptions Render.source_imports_nil.
Print Assumptions Render.imports_nil_bytes.
Print Assumptions Render.expr_ascii.
Print Assumptions Render.const_info_denotes.
Print Assumptions Render.const_info_denotes_functional.
Print Assumptions Render.resolved_expr_denotes.
Print Assumptions Render.type_expr_inj.
Print Assumptions Render.conv_byte_neq_uint8.
Print Assumptions Render.conv_rune_neq_int32.
Print Assumptions Render.decimal_ascii.
Print Assumptions Render.decode_render_decimal.
Print Assumptions Render.float_denotes.
Print Assumptions Render.integer_decimal_faithful.
Print Assumptions Render.positive_no_leading_zero.
Print Assumptions Render.boundary_max.
Print Assumptions Render.boundary_min.
Print Assumptions Render.file_first_line.
Print Assumptions Render.module_file_exact.
Print Assumptions Render.module_file_first_line.
Print Assumptions Render.module_file_ascii.
Print Assumptions Render.string_roundtrip.
Print Assumptions Render.string_literal_ascii.
Print Assumptions Render.string_literal_no_nl_cr.
Print Assumptions Render.hex_escape_exact.
Print Assumptions Render.string_denotes.
Print Assumptions Render.resolved_string_denotes.
Print Assumptions Render.complex_literal_ascii.
Print Assumptions Render.decode_render_complex_literal.
Print Assumptions Render.cplx_denotes.

Print Assumptions Emit.of_safe_module_file_header.
Print Assumptions Emit.of_safe_module_file_ascii.
Print Assumptions Emit.of_safe_header.
Print Assumptions Emit.of_safe_ascii.
Print Assumptions Emit.image_keys_nodup.
Print Assumptions Emit.file_map_domain.
Print Assumptions Emit.file_map_binding.
Print Assumptions Emit.file_map_equal.
Print Assumptions Emit.entries_equal.
Print Assumptions Emit.transport_order_independent.
Print Assumptions Emit.realizes_fresh_layout.
Print Assumptions Emit.files_are_source_paths.
Print Assumptions Emit.realizes_retained_layout.
Print Assumptions Emit.output_target_of_retained_plan.

Print Assumptions Index.Table.get_empty.
Print Assumptions Index.Table.get_set_same.
Print Assumptions Index.Table.get_set_other.
Print Assumptions Index.build_file_count.
Print Assumptions Index.build_file_source_exact.
Print Assumptions Index.source_occurrence_meta.
Print Assumptions Index.meta_source_occurrence.
Print Assumptions Index.source_absence.
Print Assumptions Index.source_occurrence_unique.
Print Assumptions Index.source_kind_exact.
Print Assumptions Index.source_role_exact.
Print Assumptions Index.source_parent_exact.
Print Assumptions Index.source_subtree_end_exact.
Print Assumptions Index.build_file_wf.
Print Assumptions Index.root_id_canonical.
Print Assumptions Index.root_no_parent.
Print Assumptions Index.nonroot_has_parent.
Print Assumptions Index.parent_unique.
Print Assumptions Index.first_child.
Print Assumptions Index.next_child.
Print Assumptions Index.child_enum.
Print Assumptions Index.child_enum_sound.
Print Assumptions Index.child_enum_reaches.
Print Assumptions Index.child_has_parent.
Print Assumptions Index.parent_has_child.
Print Assumptions Index.children_sorted.
Print Assumptions Index.ancestor_complete.
Print Assumptions Index.interval_ancestry.
Print Assumptions Index.enumeration_nodup.
Print Assumptions Index.enumeration_complete.
Print Assumptions Index.enumeration_sound.
Print Assumptions Index.builder_no_structural_search.
Print Assumptions Index.meta_stores_no_subtree.
Print Assumptions Index.key_eq_dec.
Print Assumptions Index.key_equalb_spec.
Print Assumptions Index.outer_get_exact.
Print Assumptions Index.Snapshot.index_program.
Print Assumptions Index.Snapshot.file_of_path.
Print Assumptions Index.Snapshot.ref_of_key.
Print Assumptions Index.Snapshot.ref_meta.
Print Assumptions Index.Snapshot.node_kind.
Print Assumptions Index.Snapshot.parent_of.
Print Assumptions Index.Snapshot.children_of.
Print Assumptions Index.Snapshot.node_at.
Print Assumptions Index.Snapshot.source_occurrence_of_ref.
Print Assumptions Index.Snapshot.node_ref_ext.
Print Assumptions Index.Snapshot.node_kind_spec.
Print Assumptions Index.Snapshot.node_role_spec.
Print Assumptions Index.Snapshot.ref_meta_built.
Print Assumptions Index.Snapshot.containing_file_spec.
Print Assumptions Index.Snapshot.node_ref_key_inj.
Print Assumptions Index.Snapshot.file_ref_path_inj.
Print Assumptions Index.Snapshot.parent_root.
Print Assumptions Index.Snapshot.parent_nonroot.
Print Assumptions Index.Snapshot.parent_same_file.
Print Assumptions Index.Snapshot.children_same_file.
Print Assumptions Index.Snapshot.child_parent.
Print Assumptions Index.Snapshot.parent_child.
Print Assumptions Index.Snapshot.children_of_source_order.
Print Assumptions Index.Snapshot.children_of_nodup.
Print Assumptions Index.Snapshot.ref_of_key_sound.
Print Assumptions Index.Snapshot.ref_of_key_complete.
Print Assumptions Index.Snapshot.file_of_path_complete.
Print Assumptions Index.Snapshot.file_of_path_source.
Print Assumptions Index.Snapshot.ref_of_key_source.
Print Assumptions Index.Snapshot.is_ancestor_ref.
Print Assumptions Index.Snapshot.ref_ancestry.
Print Assumptions Index.Snapshot.ref_meta_matches_source.
Print Assumptions Index.Snapshot.node_kind_matches_source.
Print Assumptions Index.Snapshot.node_role_matches_source.
Print Assumptions Index.Snapshot.node_parent_matches_source.
Print Assumptions Index.Snapshot.node_subtree_end_matches_source.
Print Assumptions Index.Snapshot.source_occ_of_ref_eq.
Print Assumptions Index.Snapshot.node_at_matches_source_view.
Print Assumptions Index.Snapshot.node_parent_ref_matches_source.
Print Assumptions Index.erase_as_kind.
Print Assumptions Index.as_kind_complete.
Print Assumptions Index.as_kind_mismatch.
Print Assumptions Index.noderefof_kind.
Print Assumptions Index.noderefof_key_inj.
Print Assumptions Index.Snapshot.file_of_path_sound.
Print Assumptions Index.Snapshot.file_of_path_source_exact.
Print Assumptions Index.Snapshot.ref_of_key_invalid_path.
Print Assumptions Index.Snapshot.ref_of_key_invalid_local.
Print Assumptions Index.Snapshot.noderef_eq_dec.
Print Assumptions Index.Snapshot.file_root_ref_local.
Print Assumptions Index.Snapshot.file_root_ref_file.
Print Assumptions Index.Snapshot.file_refs_same_file.
Print Assumptions Index.Snapshot.file_refs_complete.
Print Assumptions Index.Snapshot.file_refs_nodup.
Print Assumptions Index.Snapshot.file_refs_source_order.
Print Assumptions Index.Snapshot.file_root_ref_in_refs.
Print Assumptions Index.Snapshot.reachable_from_root.
Print Assumptions Index.Snapshot.refs_reachable.
Print Assumptions Index.occurrences_file_exact.
Print Assumptions Index.occurrences_file_sorted.
Print Assumptions Index.Snapshot.visit_file_view.
Print Assumptions Index.Snapshot.visit_file_complete.
Print Assumptions Index.Snapshot.visit_file_order.
Print Assumptions Index.Snapshot.visit_file_nodup.
Print Assumptions Index.Snapshot.node_ref_key_eq.
Print Assumptions Index.view_expr_kind.
Print Assumptions Index.kind_view_expr.
Print Assumptions Index.index_program_syntax.
Print Assumptions Index.indexed_syntax_proj.
Print Assumptions Index.key_compare_equal.
Print Assumptions Index.key_map_add_equal.
Print Assumptions Index.key_map_add_unequal.
Print Assumptions Index.key_map_elements_equal.
Print Assumptions Compilable.expression_fact_at_exact.
Print Assumptions Compilable.collect_node_input_nodup.
Print Assumptions Compilable.collect_node_buckets_singleton.
Print Assumptions Compilable.semantic_diagnostics_node_strict.
Print Assumptions Compilable.collect_diagnostics_in.
Print Assumptions Compilable.erased_report_src_eq.
