lib: [
  "_build/install/default/lib/rocq-go-extraction/META"
  "_build/install/default/lib/rocq-go-extraction/dune-package"
  "_build/install/default/lib/rocq-go-extraction/g_go_extraction.ml"
  "_build/install/default/lib/rocq-go-extraction/go.ml"
  "_build/install/default/lib/rocq-go-extraction/opam"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.a"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.cma"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.cmi"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.cmt"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.cmx"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.cmxa"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.ml"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin__G_go_extraction.cmi"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin__G_go_extraction.cmt"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin__G_go_extraction.cmx"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin__Go.cmi"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin__Go.cmt"
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin__Go.cmx"
]
libexec: [
  "_build/install/default/lib/rocq-go-extraction/rocq_go_extraction_plugin.cmxs"
]
